### ISSUE TITLE
aggregations support?

### ISSUE THREAD

**Issue by jsebrien** [Stratio/cassandra-lucene-index#10]
Hello,

is there any plan to add aggregations support?

Regards,

Julien

**Comment by adelapena** [comment]
Aggregations are in our roadmap, but not in a near future. There are several problems with Cassandra architecture to be addressed before we can start working on this. Shortly, aggregations should be done after after replica agreement, so they should be performed in the coordinator node, which would produce scalability problems.

**Comment by jsebrien** [comment]
ok, I see.

Thanks

Julien
