### ISSUE TITLE
Issues inserting using JSON

### ISSUE THREAD

**Issue by dannz12** [Stratio/cassandra-lucene-index#107]
I just started using this plugin recently so I am still learning, but i have been running into some issues that I cant find a solution to. After following the example steps for creating a table and a custom index I started inserting data into the table. The issue i am running into right now is that when I try inserting into a table using a JSON, after creating a lucene index on the table, the console spits this error back at me.

**Traceback (most recent call last):
  File "/usr/bin/cqlsh.py", line 1249, in perform_simple_statement
    result = future.result()
  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-3.0.0-6af642d.zip/cassandra-driver-3.0.0-6af642d/cassandra/cluster.py", line 3122, in result
    raise self._final_exception
WriteFailure: code=1500 [Replica(s) failed to execute write] message="Operation failed - received 0 responses and 1 failures" info={'failures': 1, 'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}**

Despite getting that error, the insert does go through and the entry is in the table. The problem is that if I try to search using the plugin I wont get any of the entries that were added using JSONs. It seems like the system cant replicate the data when it tries to insert it  this way so it never looks through it when trying to search. I am wondering if there is any way around this or if i am not setting something correctly. 

I am using the current version of lucene and Cassandra 3.0.3

These were the steps i used to make the table and index:

**CREATE KEYSPACE demo
WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};
USE demo;
CREATE TABLE tweets (
    id INT PRIMARY KEY,
    user TEXT,
    body TEXT,
    time TIMESTAMP,
    latitude FLOAT,
    longitude FLOAT
);**

**CREATE CUSTOM INDEX tweets_index ON tweets ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            id    : {type : "integer"},
            user  : {type : "string"},
            body  : {type : "text", analyzer : "english"},
            time  : {type : "date", pattern : "yyyy/MM/dd", sorted : true},
            place : {type : "geo_point", latitude:"latitude", longitude:"longitude"}
        }
    }'
};**

And the insert statement that is causing issues is like this:

**INSERT INTO tweets JSON '{"id":12345,"body":"some kind of text"}';**

**Comment by adelapena** [comment]
Hi,

This is a bug. The JSON format is introducing explicitly null values for latitude and longitude columns. The bad management of these null values is throwing a NPE that produces a server-side failure after the validation phase. Indeed, the same error happens with this non-JSON query:
```
INSERT INTO tweets(id,body,latitude,longitude) VALUES ( 1235,'text',null,null);
``` 
We have fixed it at [branch-3.0.3](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.3), [branch-3.0.4](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.4) and [branch-2.2.5](https://github.com/Stratio/cassandra-lucene-index/tree/branch-2.2.5). 

Thanks for reporting.
