### ISSUE TITLE
support for ticktock 3.x releases

### ISSUE THREAD

**Issue by masumsoft** [Stratio/cassandra-lucene-index#112]
Any roadmap plans to support the ticktock 3.x releases?

**Comment by adelapena** [comment]
We don't have any plans to add support for all the tick tock releases, but we could eventually support some of them.

**Comment by mmatloka** [comment]
Are currently know any incompatibilities with 3.1, 3.2, 3.3, or 3.4? or it may just work with them? :)

**Comment by adelapena** [comment]
We haven't tested them, but you can try running [the embedded acceptance tests](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.4/testsAT) by yourself over different patched cluster deployments. [CCM](https://github.com/pcmanus/ccm) can be useful.

**Comment by adelapena** [comment]
We have released [cassandra-lucene-index 3.5.0](https://github.com/Stratio/cassandra-lucene-index/tree/3.5.0), intended to be used with Apache Cassandra 3.5. Whereas it could be useful for testing new features, we encourage you to use a more stable version of C* in production environments.
