### ISSUE TITLE
Speed up writes - Question

### ISSUE THREAD

**Issue by alvarofe** [Stratio/cassandra-lucene-index#114]
Sorry if this is not the appropriate channel to ask this.

I am experimenting with lucene 2.2.5 and cassandra and it takes a lot of time to insert a row into the database and i think is due to the lucene indexes. The table that i created is something like this.

```
CREATE TABLE keyspace.table (
    country text PRIMARY KEY,
    descr text,
    inetnum text,
    lucene text
```
```
CREATE CUSTOM INDEX table_index ON keyspace.table (lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds': '2', 'schema': '{
fields: {
descr : {type: "string"}
}
}'};
```

The idea of this is to latter make searches using regexp over descr field something like

```
SELECT * FROM ripe WHERE lucene = '{filter : {type:"regexp", field:"descr", value: ".*whatever.*"}}';
```

But the writes takes a huge amount of time. So i don't know is there is a better option to do this or it just works like that i am very novice using this.

I'm using ccm (https://github.com/pcmanus/ccm) with threes nodes in localhost.

**Comment by adelapena** [comment]
How much is a huge amount of time? Could you provide some information your hardware? Which is your write speed with and without index? Are you using the [asynchronous indexing feature](https://github.com/Stratio/cassandra-lucene-index/blob/branch-2.2.5/doc/documentation.rst#indexing)?

**Comment by alvarofe** [comment]
nothing was my mistake after researching further i was overwritten entries :( but the indexing threads looks awesome. Thanks and sorry for bothering you.

**Comment by adelapena** [comment]
No problem :)
