### ISSUE TITLE
2.2.5.3 UUID-> DATE or LONG or INTEGER mapper

### ISSUE THREAD

**Issue by charliy101** [Stratio/cassandra-lucene-index#115]
Hi @adelapena 

Is any chance to create lucene index by column of uuid data type  with mapper DATE or LONG or INTEGER in order to have the possibility to retrieve data by range for plugin of version 2.2.5.* ?

**The question is not about timeuuid data type.**
Thanks in advance.

**Comment by adelapena** [comment]
Hi @charliy101,

From [version 2.2.5.3](https://github.com/Stratio/cassandra-lucene-index/blob/branch-2.2.5/CHANGELOG.md), Cassandra time-UUIDs are supported by date, date_range and bitemporal mappers. So, for example, you can index a TimeUUID column with a date mapper with yyyyMMdd pattern and search with a range filter:
```
CREATE CUSTOM INDEX users_index on users(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            id : { type : "date", pattern : "yyyy/MM/dd" }
        }
    }'
};

SELECT * FROM users
WHERE lucene = '{filter : {
                        type          : "range",
                        field         : "id",
                        lower         : "2014/01/01",
                        upper         : "2014/01/02",
                        include_lower : true,
                        include_upper : true }}';
```

**Comment by charliy101** [comment]
Hi @adelapena 
Thank you a lot for your detail description, but the question was about type **uuid ** and **not about TIMEUUID.**
As far as I understand correct, there is not way to make date or long or integer mapper for pure **uuid **  type. Correct?

Thanks in advance.

**Comment by adelapena** [comment]
I see. No, generic UUIDs are indexed as untokenized text, so you can only search by exact value, wildcard, regex or a range of alphabetically sorted values.

Which date, long or integer value do you want to extract from not-time UUIDs? Which [type of UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier#Variants_and_Versions) are you indexing? Maybe are you storing time-based UUIDs using CQL generic UUID type?

**Comment by charliy101** [comment]
Thank you very much for your recommendation.
Hence, I'm closing this ticket.
