### ISSUE TITLE
Build Failure: org.apache.maven.plugin.MojoFailureException (3.0.4)

### ISSUE THREAD

**Issue by SamdeVega** [Stratio/cassandra-lucene-index#117]
Hello,

I tried to build a jar using maven 3.3.9 but I receive an error from tests. Could it be a problem with dependencies?

Regards.
![screenshot](https://cloud.githubusercontent.com/assets/10880609/14527073/5fca7726-023f-11e6-9ac6-bc34b14cf1e3.PNG)

**Comment by adelapena** [comment]
Hi @SamdeVega,

Can you please provide the surefire-reports fire mentioned by the error message? Which JDK version are you using? Are you using Windows?
