### ISSUE TITLE
'No viable alternative' error when creating tweets index

### ISSUE THREAD

**Issue by JohnCunningham** [Stratio/cassandra-lucene-index#118]
I am unable to create a custom lucene index unless I specify an index-identifier.  I can't specify an index-identifier because I want to set up a geospatial index  involving two fields.  

Walking through an example, specifically, the tweets example described here ( https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.4/doc/documentation.rst#example ):

```
-- table creation works fine
CREATE TABLE tweets (
    id INT PRIMARY KEY,
    user TEXT,
    body TEXT,
    time TIMESTAMP,
    latitude FLOAT,
    longitude FLOAT
);
```

```
-- this will not work 
CREATE CUSTOM INDEX tweets_index ON tweets ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            id    : {type : "integer"},
            user  : {type : "string"},
            body  : {type : "text", analyzer : "english"},
            time  : {type : "date", pattern : "yyyy/MM/dd", sorted : true},
            place : {type : "geo_point", latitude:"latitude", longitude:"longitude"}
        }
    }'
};
```

Running the create index statement generates the error message:
_SyntaxException: ErrorMessage code=2000 [Syntax error in CQL query] message="line 1:44 no viable alternative at input ')' (... INDEX tweets_index ON tweets ([)]USING...)"_

It appears from the error message that I need to add index identifier fields in between the parenthesis. 

If I add an index identifier, say latitude, the create index statement works: 

CREATE CUSTOM INDEX tweets_index ON tweets (**latitude**) 
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            id    : {type : "integer"},
            user  : {type : "string"},
            body  : {type : "text", analyzer : "english"},
            time  : {type : "date", pattern : "yyyy/MM/dd", sorted : true},
            place : {type : "geo_point", latitude:"latitude", longitude:"longitude"}
        }
    }'
};

Will the above statement produce indexes that work?  If not, how should I correct the problem?

We are currently using the datastax max bundle.  (We are not in production and intend to move away from datastax in the near future).  The version numbers when I enter cqlsh are:
_cqlsh 5.0.1 | Cassandra 2.1.13.1218 | DSE 4.8.6 | CQL spec 3.2.1 _

We are using the cassandra-lucene-index-plugin-2.1.13.0.jar downloaded from the maven repo.

Thanks,

John

**Comment by adelapena** [comment]
Hi @JohnCunningham,

You are reading the documentation of the 3.0.4 branch, which is aimed to be used with the version 3.0.4 of Cassandra. However, you are using Cassandra 2.1.13.1218 and the version 2.1.13.0 of the plugin, so you should read the documentation for this version: (https://github.com/Stratio/cassandra-lucene-index/blob/2.1.13.0/doc/src/site/sphinx/documentation.rst)

Cassandra 2.x requires to create the index over a fake column, as you will see in the examples of the aforementioned documentation. The support for pure per-row indexes was added after [the secondary indexes redesign produced in C* 3.x](https://issues.apache.org/jira/browse/CASSANDRA-9459).

Additionally, the plugin is only tested against open source Apache Cassandra releases, while you are using a DataStax distribution. Probably DSE Cassandra 2.1.13.1218 will not very different from Apache Cassandra 2.1.13, but we can't guarantee it.
