### ISSUE TITLE
Indexing Collections Elements

### ISSUE THREAD

**Issue by jsebrien** [Stratio/cassandra-lucene-index#12]
hello, 

Is it possible to index collections (precisely a set) elements?
For example, I have a field, which is a set containing these values : "5", "7", "9"

Is it possible to search rows where "8" is contained (or not) in this set?

Julien

**Comment by ealonsodb** [comment]
Yes, it is posible to index collections. Just use the basic type mapper. Here is an example:

Create the table.
```
CREATE TABLE users (
           user_id text PRIMARY KEY,
           first_name text,
           last_name text,
           emails set<text>,
           lucene text
       );
```

create the custom index using StringMapper:
```
CREATE CUSTOM INDEX users_index ON users(lucene) USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds'    : '1',
    'schema' : '{
        fields : {
            first_name   : {type     : "string"},
            last_name : {type     : "string"},
            emails : {type     : "string"}
        }
    }'
};
```
Insert some Data
```
INSERT INTO users (user_id, first_name, last_name, emails)
       VALUES('frodo', 'Frodo', 'Baggins', {'frodo@baggins.com', 'frodo_baggins@gmail.com'});


INSERT INTO users (user_id, first_name, last_name, emails)
       VALUES('sam', 'Samsagaz', 'Gamyi', {'sam@gamyi.com', 'sam@gmail.com'});

INSERT INTO users (user_id, first_name, last_name, emails)
       VALUES('bilbo', 'Bilbo', 'Baggins', {'bilbo@baggins.com'});

```


You can query for example by wildcard looking for all users with any email from gmail.com
```
SELECT * FROM users
WHERE lucene = '{query : {
                        type  : "wildcard",
                        field : "emails",
                        value : "*gmail.com" }}';
```
With StringMapper you can use regexp, prefix, etc...

Hope you find this useful, 
thank you

**Comment by jsebrien** [comment]
This is great, thanks

**Comment by jsebrien** [comment]
Just one last question: if my email set is: {'frodo@baggins.com', 'frodo_baggins@gmail.com'}

Can I use a contains query to get rows where the email set contains both frodo@baggins.com AND frodo_baggins@gmail.com ?

**Comment by ealonsodb** [comment]
yes, you should use a Boolean query like this:
```
SELECT * FROM users WHERE lucene  = '{query : { type : "boolean",
                        must : [{type : "wildcard", field : "emails", value : "*gamyi.com"},
                                {type : "wildcard", field : "emails", value : "*gmail*"}]}}';
```
using 'must' it is like AND, in this previous case it must have an email finishing in gamyi.com and one that contains "gmail". 

using 'should' is like an OR

```
SELECT * FROM users WHERE lucene  = '{query : { type : "boolean",
                        should : [{type : "wildcard", field : "emails", value : "*gamyi.com"},
                                {type : "wildcard", field : "emails", value : "*gmail*"}]}}';
```

All this is well explained here: explained here: https://github.com/Stratio/cassandra-lucene-index/blob/branch-2.1.7/doc/src/site/sphinx/documentation.rst#boolean-query

Thanks

**Comment by jsebrien** [comment]
Ok, thanks a lot

**Comment by totalwar** [comment]
hi
I try to index set of bigints, but i get error on inserting a set contains more than one elem:
    
    create table test(id uuid, someSet set<bigint>);
    insert into test (id, someSet) values (uuid(), {1}); // fine
    insert into test (id, someSet) values (uuid(), {1, 2, 3}); // error

    WriteTimeout: code=1100 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out - received only 0 responses." info={'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}

Exception extracted from /var/log/cassandra/system.log pasted here http://pastebin.com/zFNktUYJ

**Comment by adelapena** [comment]
Hi,

It's a bug related to numeric collections DocValues. It's fixed at [master branch](https://github.com/Stratio/cassandra-lucene-index/tree/master), and the fix will be present in the next release.

However, as a walk around, if you are not interested in sorting results by "someset" column, you can disable sorting in its mapper:
```
CREATE CUSTOM INDEX test_index ON test(lucene) USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds': '1',
    'schema' : '{
        fields : {
            someset : {type : "long", sorted : false}
        }
    }'
};
```
This way the error will not happen and you will have a smaller and possibly faster index.

Thanks!

**Comment by HEMANTA999** [comment]
Can we index list elements ???
