### ISSUE TITLE
Cassandra 3.5 compatibility?

### ISSUE THREAD

**Issue by jerzygangi** [Stratio/cassandra-lucene-index#120]
Is cassandra-lucene-index compatible with Cassandra 3.5?

**Comment by adelapena** [comment]
Hi @jerzygangi ,

Although we are reluctant to provide support to [so unstable releases](http://mail-archives.apache.org/mod_mbox/cassandra-user/201604.mbox/browser), we are about to release [a 3.5-based release](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.5). This will be available along this week.

**Comment by jerzygangi** [comment]
@adelapena Thanks for the info. I'm a new Cassandra user, so I wasn't aware of the 3.5 "drama." Keep up the hard work on this plugin.

**Comment by adelapena** [comment]
We have released [cassandra-lucene-index 3.5.0](https://github.com/Stratio/cassandra-lucene-index/tree/3.5.0), intended to be used with Apache Cassandra 3.5. Whereas it could be useful for testing new features, we encourage you to use a more stable version of C* in production environments.

**Comment by jerzygangi** [comment]
Thanks for your help on this @adelapena
