### ISSUE TITLE
Support columns with TTL

### ISSUE THREAD

**Issue by jerro99** [Stratio/cassandra-lucene-index#121]
Current docs list columns with TTL as "not yet supported".  Any ETA on when this feature might be supported?

**Comment by ealonsodb** [comment]
Hi @jerro99 

Indexing TTL rows and removing from index when expired depends on [CASSANDRA-11329](https://issues.apache.org/jira/browse/CASSANDRA-11329).
We have already a working implementation of this feature, but this only works with futures cassandra 3.0.6, 3.6 release.

So, if cassandra continues with their tick-tock releases it seems this functionality will be included in cassandra-lucene-index 3.0.6.0 in mid June.

**Comment by adelapena** [comment]
Thanks to  [CASSANDRA-11329](https://issues.apache.org/jira/browse/CASSANDRA-11329) and @ealonsodb, [the new 3.0.6.0 release](https://github.com/Stratio/cassandra-lucene-index/tree/3.0.6.0) properly supports columns with TTL, and future versions targeted to Apache Cassandra >= 3.0.6 and 3.6.0 will do so.
