### ISSUE TITLE
Is there a mailing or forum for cassandra-lucene-index ?

### ISSUE THREAD

**Issue by tobiaseriksson** [Stratio/cassandra-lucene-index#126]
I have some questions and I am not sure this is the place, yet I did see [question] in the title of some of the "issues".
Is there a good mailing list or forum that one can use ?

-Tobias

**Comment by adelapena** [comment]
Hi @tobiaseriksson ,

There is no mailing list for this project yet. You can open an issue per each question you have, we will do our best to answer them.
