### ISSUE TITLE
branch-2.1.14 is for 2.1.14 version of casaandra?

### ISSUE THREAD

**Issue by dejwsz** [Stratio/cassandra-lucene-index#129]
I'm asking because after building it it shows up as 2.1.13 - version id was not updated in that branch? Can it be used without problem with 2.1.14 of cassandra?

**Comment by ealonsodb** [comment]
Hi @dejwsz. We use the branches named 'branch-X.X.X' to develop the index different versions. You, as a user, should use the 'X.X.X' tagged releases. 

So, please wait, we will release it ASAP.

**Comment by dejwsz** [comment]
OK thx

**Comment by ealonsodb** [comment]
It's already released. It is available here [2.1.14.0](https://github.com/Stratio/cassandra-lucene-index/releases/tag/2.1.14.0)

Regards

**Comment by dejwsz** [comment]
Thanks again.
