### ISSUE TITLE
Collection set doesn't refresh correctly on removal of item

### ISSUE THREAD

**Issue by nlacey** [Stratio/cassandra-lucene-index#132]
If you have a clustering key, lucene doesn't refresh correctly when using set collection.
(cassandra-lucene-index-plugin-2.2.3.3-RC1)

drop keyspace if exists testset2;
CREATE KEYSPACE IF NOT EXISTS testset2 WITH REPLICATION = { 'class': 'SimpleStrategy', 'replication_factor': 1 };
use testset2;

Create table test (
    name           Text,
    sec            Text,
    myset          Set gt Text lt,  I'm sorry the greater than sign doesn't show up in githup?
    lucene         Text,
    Primary Key (name,sec)
);

CREATE CUSTOM INDEX test_index ON test(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds': '1',
    'schema': '{
        fields : {
            myset  : {type : "string"}
        }
    }'
};

insert into test (name, sec,myset) values ('test1','continue', {'home'});
--------- (everything works)  
select name, myset from test where lucene = '{"query":{"type":"boolean","must":[{"type":"wildcard","field":"myset","value":"hom*"}]}}';

 name  | myset
-------+----------
 test1 | {'home'}

-----------------

update test set myset = myset - {'home'} where name='test1' and sec = 'continue';
------- invalid, returned incorrect match
select name, myset from test where lucene = '{"query":{"type":"boolean","must":[{"type":"wildcard","field":"myset","value":"hom*"}]}}';

 name  | myset
-------+-------
 test1 |  null

(1 rows)

The same table ( with clustering key (sec) ) removed seemed to work.
If I add another value to myset,  the filter returns correctly.

Thanks for your help!

**Comment by ealonsodb** [comment]
Hi @nlacey:

We thinks this is fixed in [2.2.5.4](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.5.4)

Cheers

**Comment by adelapena** [comment]
Indeed, it is fixed is [2.2.5.4](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.5.4).
