### ISSUE TITLE
Springdata cassandara support ?

### ISSUE THREAD

**Issue by Prasanthmv** [Stratio/cassandra-lucene-index#137]
Hi,
Is it possible to use this with springdata Cassandra .?

**Comment by adelapena** [comment]
Hi @Prasanthmv,

We don't provide explicit support for Spring Data, but it should work provided that you pass the Lucene expressions as strings to the Cassandra Java driver, as discussed in [your issue about this same topic](https://github.com/Stratio/cassandra-lucene-index/issues/138). Neither Spring Data or the Java driver have knowledge about the Lucene semantics, so the custom index expressions should be always managed as column values.
