### ISSUE TITLE
paging over relevance searches (queries and sorts)

### ISSUE THREAD

**Issue by jsebrien** [Stratio/cassandra-lucene-index#14]
Hello,

Do you have an idea of when it will be possible to page over relevance searches (queries and sorts)?

Regards,

Julien

**Comment by adelapena** [comment]
Hi,

Paging over relevance searches is in our roadmap with high priority. However, current Apache Cassandra 2i API seems insufficient to achieve this. The problem is that CQL pager assumes that the rows are always sorted by token and clustering key. This limitation could be overcome by modifying the way in which Cassandra does paging or maybe with a strong reflection work. Thus, getting this working would take some time, especially if we have to submit a patch and wait to its approval and inclusion in a future Apache Cassandra release.

Alternatively, some kind of non CQL based paging could be addressed, something like:
```
SELECT * FROM tweets WHERE lucene='{
    query : {type:"phrase", field:"body", value:"big data gives organizations"},
    after : "32783c34-295c-11e5-b345-feff819cdc9f"
}' limit 100;
```

Regards

**Comment by jsebrien** [comment]
Your example is interesting. "32783c34-295c-11e5-b345-feff819cdc9f" is the value of which filed? id? Don't we need to specify the fieldname with the after clause?

**Comment by adelapena** [comment]
The idea is having an auto-generated document identifier which would be returned inside the 'lucene' column. Thus, the id would be stored in a hidden Lucene field:

```
SELECT * FROM tweets WHERE lucene='{
    query : {type:"match", field:"age", value:18}
}' limit 100;

age  | lucene
-----+------------------------------------------------------------------------
18   | {score:10,id:"bb7223be-2a02-11e5-b345-feff819cdc9f"}
18   | {score:10,id:"bb7226fc-2a02-11e5-b345-feff819cdc9f"}
18   | {score:9,id:"bb722904-2a02-11e5-b345-feff819cdc9f"}
18   | {score:7,id:"bb722e40-2a02-11e5-b345-feff819cdc9f"}

SELECT * FROM tweets WHERE lucene='{
    query : {type:"phrase", field:"body", value:"big data gives organizations"},
    after : "bb722e40-2a02-11e5-b345-feff819cdc9f"
}' limit 100;

age  | lucene
-----+------------------------------------------------------------------------
18   | {score:5,id:"bb7230ac-2a02-11e5-b345-feff819cdc9f"}
18   | {score:4,id:"bb723214-2a02-11e5-b345-feff819cdc9f"}
```
However, this is a little bit awkward solution, it would be preferable modify CQL paging. Working on it.

**Comment by jsebrien** [comment]
Ok I see, thanks.

**Comment by adelapena** [comment]
Hi,

Just to let you know that we have just added experimental full support for automatic CQL paging, even for queries and sorts. With the new CQL handler you can page over search results in the same way it is done with regular C* queries:
```
String query = "SELECT * FROM tweets WHERE lucene='{query:{type:"match", field:"age", value:18}}'";
Statement stmt = new SimpleStatement(query);
stmt.limit(10000);
stmt.setFetchSize(100);
ResultSet rs = session.execute(stmt);

// Iterate over the ResultSet here 
```
The changes have been done in [master branch](https://github.com/Stratio/cassandra-lucene-index/tree/master), and they will be present in the next release.

I hope it will be useful.

**Comment by jsebrien** [comment]
This is very good news, I will try that asap. Thanks!

**Comment by jsebrien** [comment]
Just a quick question : how do you specify a starting key (offset) here?  In CQL, you have to use the token function. How does it interact with lucene query results?

**Comment by adelapena** [comment]
The paging mechanism does not use neither token function nor offset, it's based on CQL native protocol automatic paging feature. You can simply use the ``Iterator<Row>``provided by the driver, and it will page results in transparently. 

However, you could be interested in using the query's ``PagingState`` as an offset [as described here](http://docs.datastax.com/en/drivers/java/2.1/com/datastax/driver/core/Statement.html#setPagingState(com.datastax.driver.core.PagingState)).

**Comment by jsebrien** [comment]
Excellent, thanks!

**Comment by daniyel** [comment]
Is there a comparable example in nodejs?

**Comment by moammadj** [comment]
I'm sorry for adding question here , can any one say that how can I get the score of each result in "phrase search" ? Before version 3.0.3 we could get the score from \<magic_column\> .

**Comment by adelapena** [comment]
Hi @mjshabani,

We are very close to publish [a new 3.0.5.1 release](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.5) compatible with the old <magic_column> syntax. You can read more about the two alternative syntaxes [here](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.5/doc/documentation.rst#alternative-syntaxes).

By the way, did you have any problem to create a new issue? This one is closed and also related to another topic.
