### ISSUE TITLE
Cassandra Lucene index commercial support

### ISSUE THREAD

**Issue by eshadei** [Stratio/cassandra-lucene-index#144]
Hello Team,

We want to use Cassandra Lucene index. Can you please confirm if you have commercial support available for Cassandra Lucene index or we have only community support for the same?

Regards
Deepti

**Comment by adelapena** [comment]
Hello @eshadei,

Yes, Stratio offers commercial support for the project. Please feel free to send a mail to [contact@stratio.com](mailto:contact@stratio.com). Thanks for your interest.

Regards,

**Comment by eshadei** [comment]
Hello, 
Thanks for your response. Can you please confirm what are the options (Standard, Premium etc. ) available in commercial support?

Regards
Deepti
