### ISSUE TITLE
How lucene indexes are impacted on node failure in a cluster?

### ISSUE THREAD

**Issue by vinayrpatil** [Stratio/cassandra-lucene-index#15]
Hello,

During a node failure in a cluster, what is the impact on the secondary indexes stored on that node? Are the indexes lost? If they are lost, are they reconstructed again?

Regards,
Vinay

**Comment by adelapena** [comment]
Hello,

The indexes are managed in the same way as the C* column families, so they are replicated according to your replication factor. When a node is lost its replicas can guarantee the high availability and, when the failing node is replaced, its index shard replica is automatically rebuilt in background.

Regards,

**Comment by vinayrpatil** [comment]
Thank you!
