### ISSUE TITLE
 Discarding immense term in field='feedbacklists', Lucene only allows terms with at most 32766 bytes in length; got 42776

### ISSUE THREAD

**Issue by Prasanthmv** [Stratio/cassandra-lucene-index#151]
Hi,
While iserting the data i got this error in console .
`ERROR 05:07:51 Discarding immense term in field='feedbacklists', Lucene only all                                                                                        ows terms with at most 32766 bytes in length; got 42776`

My table structure is
`CREATE TABLE netspectivestature.feedbacks (
    physicianid text,
    feedbackid text,
    createdat timestamp,
    deletestatus boolean,
    docexpiry text,
    doctype text,
    feedbacklists list<text>,
    lastupdatedon timestamp,
    lucene text,
    PRIMARY KEY (physicianid, feedbackid)
) WITH CLUSTERING ORDER BY (feedbackid DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
CREATE CUSTOM INDEX feedbacks_index ON netspectivestature.feedbacks (lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds': '1', 'schema': '{fields : {feedbacklists : { type : "string"},physicianid:{type:"text"},doctype:{type:"text"}}}'};
`

Why this error coming ? How can i solve this problem ?

**Comment by adelapena** [comment]
This is related to #27. As the message says, one of the values contained in ``feedbacklists`` contains a term exceeding the max size of 32766 bytes imposed by Apache Lucene, so the analyzer is discarding it logging a warning to avoid a failure in Lucene. All the other terms in the ``feedbacklists`` values under 32766 bytes will be indexed.
