### ISSUE TITLE
"No mapper found for sortFields mapper 'geo_point'

### ISSUE THREAD

**Issue by lapcchan** [Stratio/cassandra-lucene-index#152]
i tried with the example from document, trying to sort the result by distance. with the error
"No mapper found for sortFields mapper 'geo_point'

SELECT * FROM users WHERE expr(users_index, '{
    filter : {
        type          : "geo_distance",
        field         : "place",
        latitude      : 40.225479,
        longitude     : -3.999278,
        max_distance  : "1km"  },
    sort   : {
        fields: [ {
            type      : "geo_distance",
            mapper    : "geo_point",
            reverse   : false,
            latitude  : 40.225479,
            longitude : -3.999278} ] }
}');

**Comment by ealonsodb** [comment]
Hi @lapcchan: 
In order to investigate and reproduce this issue i need: 

1.- Cassandra and cassandra-lucene-index versions 
2.- CREATE KEYSPACE, TABLE and CUSTOM INDEX queries. 
3.- SOME INSERTS..

Cheers

**Comment by lapcchan** [comment]
pls close this issue. on 3.0.6 it works fine.
