### ISSUE TITLE
filter match request on map field fails for value containing "-" character

### ISSUE THREAD

**Issue by forumjava** [Stratio/cassandra-lucene-index#16]
Hi,

Tried with both 2.1.6 and 2.1.8 in different environments and for both of them i am seeing below exception stack when the criteria is more than 12 characters:

Query: select * from <table Name> where cassandra_lucene_index = '{filter : {type: "match", field: "<map field>", value: "<greater then 12 characters>"}}';

Works fine for creiteria valus that are <= 12 characters.

====
Traceback (most recent call last):
  File "./cqlsh.py", line 1150, in perform_simple_statement
    rows = future.result(self.session.default_timeout)
  File "/<some path>/apache-cassandra-2.2.0_i1/bin/../lib/cassandra-driver-internal-only-2.6.0c2.post.zip/cassandra-driver-2.6.0c2.post/cassandra/cluster.py", line 3296, in result
    raise self._final_exception
ReadFailure: code=1300 [Replica(s) failed to execute read] message="Operation failed - received 0 responses and 1 failures" info={'failures': 1, 'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}
======

Please let me know in you need any additional information.

**Comment by adelapena** [comment]
Can you please show a full failing example, with the index schema, one row insertion and one failing query? This way it would be easier to reproduce the issue.

Thanks

**Comment by forumjava** [comment]
Hi,

I have updated title which now correctly reflects the issue.

Below the steps to reproduce:

//create table
create table mytesttable (idcol int, testtextcol text, testmapcol map<text,text>, cassandra_lucene_index text, primary key (idcol));

//create index
CREATE CUSTOM INDEX IF NOT EXISTS lucene_test_idx ON mytesttable (cassandra_lucene_index) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds' : '1', 'schema' : '{ fields : {testtextcol: {type: "string"}, testmapcol: {type: "string"}}}'};

//insert sample data
insert into mytesttable (idcol, testtextcol, testmapcol) values (1, 'row1', {'attb1': 'row1attb1Val', 'attb2': 'row1attb2Val', 'attb3': 'row1attb3Val'});
insert into mytesttable (idcol, testtextcol, testmapcol) values (2, 'someLongRow2Value', {'attb1': 'someLongattb1Val', 'attb2': 'attb2Val', 'attb3': 'attb3Val'});
insert into mytesttable (idcol, testtextcol, testmapcol) values (3, 'row3', {'attb1': 'row2attb1Val', 'attb2': 'row2attb2Val', 'attb3': 'row2attb3Val'});
insert into mytesttable (idcol, testtextcol, testmapcol) values (4, 'row4', {'attb2': 'row3attb2Val', 'attb3': 'row3attb3Val'});

//this query works
select * from mytesttable where cassandra_lucene_index = '{filter : {type: "match", field: "testtextcol", value: "val1"}}';

//this query errors
select * from mytesttable where cassandra_lucene_index = '{filter : {type: "match", field: "testmapcol.attb1", value: "ro-1"}}';

**Comment by adelapena** [comment]
Hi,

It was a bug related to match query mapping, which was trying to perform a phrase query over the not tokenized field. It's solved at master branch, and the fix will  be present at the next release.

**Comment by forumjava** [comment]
Thanks! this works now with the fix for #18.

**Comment by Sahasrara** [comment]
I'm seeing a similar error on a date range query.  

http://stackoverflow.com/questions/37560268/cassandra-stratio-failed-to-execute-read

I'm using version 3.0.3.1-RC1-SNAPSHOT.  Would that be the same issue?

**Comment by adelapena** [comment]
No, it isn't the same issue.

``date_range`` searches are intended to be used with data indexed with ``date_range`` mapper, which indexes time durations composed by a start and stop date using a spatial approach.

For searching simple dates inside a time duration you should use a ``range`` search:
```
select * from profiles where expr(profiles_index, '{ 
  filter: { 
    type: "range", 
    field: "age", 
    lower: "1984/01/01", 
    upper: "2010/01/01", 
    include_lower: true,
    include_upper:true 
  } 
}');
```
