### ISSUE TITLE
"nodetool cleanup" on cassandra breaks lucene index

### ISSUE THREAD

**Issue by vineet01** [Stratio/cassandra-lucene-index#160]
A "nodetool cleanup" operation is [recommended](http://docs.datastax.com/en/cassandra/2.2/cassandra/operations/opsAddNodeToCluster.html) by cassandra after adding a new node.

This operation seems incompatible with lucene index and breaks it, i end up doing a re-indexing to make it work whenever a cleanup is done.

Errors from cassandra during cleanup operation :-

ERROR [CompactionExecutor:2014] 2016-06-04 22:40:20,663 Index.java:139 - Error deleting row in Lucene index KEYSPACE_NAME.TABLE_NAME.user_lucene_index
java.lang.NullPointerException: null

Cassandra and lucene plugin versions being used : 2.2.4

**Comment by ealonsodb** [comment]
Hi @vineet01: 

In order to investigate this issue i need some info:
Could you please tell us which exact version of the plugin are you using? 
Is it [2.2.4.4](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.4.4)?

Cheers

**Comment by vineet01** [comment]
It is 2.2.4.0.

**Comment by ealonsodb** [comment]
Hi @vineet01 

It is a known bug. I have tested with a ccm cluster both in 2.2.4.0 and 2.2.4.4 versions.

It is resolved in [2.2.4.4](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.4.4). 
As you can see in [upgrade](https://github.com/Stratio/cassandra-lucene-index/blob/2.2.4.4/doc/documentation.rst#upgrade) documentation upgrading from 2.2.4.0 to 2.2.4.4 does not require reindexing, so replace one jar by another and it will be resolved.

Please let us know if the solution is correct.

**Comment by vineet01** [comment]
Thanks @ealonsodb , i will try it out and update.
