### ISSUE TITLE
Searching at different tables in one query

### ISSUE THREAD

**Issue by nataschaa** [Stratio/cassandra-lucene-index#162]
Hello,
I have just installed Stratio Cassandra-Lucene-Index and started working with it. 
I'm wondering now: Is it also possible to search at different tables in one query?
Thanks in advance :)

**Comment by adelapena** [comment]
Hi @nataschaa ,

No, it is not possible to search at multiple tables with the same query. Usually the alternatives are either denormalize the data model to make it fit in a single table or using Spark if you are in an analytical use case.

**Comment by nataschaa** [comment]
Thank you!
