### ISSUE TITLE
Indexing collection.object yields error message "'schema' is invalid : No column definition 'col.obj' for mapper 'col.obj'"

### ISSUE THREAD

**Issue by jbsturgeon** [Stratio/cassandra-lucene-index#165]
This only seems to be an error if the UDT collection is part of the 'CLUSTERING ORDER BY' clause.  An example that causes the issue is below.

DROP KEYSPACE IF EXISTS jbs_test;
CREATE KEYSPACE IF NOT EXISTS jbs_test WITH replication = { 'class': 'SimpleStrategy', 'replication_factor': 1 };
USE jbs_test;

CREATE TYPE location (
    street TEXT,
    city TEXT,
    zip INT
);

CREATE TABLE user_profiles (
    login TEXT,
    mailing FROZEN<location>,
    lucene TEXT,
    PRIMARY KEY (login, mailing)
) WITH CLUSTERING ORDER BY(mailing DESC);

DROP INDEX IF EXISTS user_index;
CREATE CUSTOM INDEX user_index ON user_profiles(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            login : {type : "string"},
            "mailing.zip" : {type : "integer"}
        }
    }'
};

**Comment by ealonsodb** [comment]
Hi @jbsturgeon: 

Yes, you are right, this is a bug affecting all versions. We have fixed it at [branch-2.2.6](https://github.com/Stratio/cassandra-lucene-index/commit/4523c258b815180c0694c04317ce6a3792a6c5ab), [branch-3.0.7](https://github.com/Stratio/cassandra-lucene-index/commit/69564b3999c5eb0dd617e130a6001c0d1d093c0b) and [branch-3.7](https://github.com/Stratio/cassandra-lucene-index/commit/a5e58735899f7e17348462475585f196bffba6ca)

We have plans to release all versions this week. In the meantime, you can try downloading and compiling branch-X.X[.X] as stated in doc [Installation](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.7/doc/documentation.rst#installation) section.

Thank you for reporting.

**Comment by ealonsodb** [comment]
It is fixed in [2.2.6.2](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.6.2), [3.0.7.2](https://github.com/Stratio/cassandra-lucene-index/tree/3.0.7.2) and [3.7.1](https://github.com/Stratio/cassandra-lucene-index/tree/3.7.1) releases.
