### ISSUE TITLE
For index on set type column, query always see errors

### ISSUE THREAD

**Issue by wanghong230** [Stratio/cassandra-lucene-index#167]
(40 rows)
Failed to format value SortedSet([u'master']) : 'NoneType' object has no attribute 'get_n_sub_types'
Failed to format value SortedSet([u'master']) : 'NoneType' object has no attribute 'get_n_sub_types'
38 more decoding errors suppressed.

**Comment by ealonsodb** [comment]
Hi @wanghong230:

Which cassandra and index version are you using??
Can you give us a detailed example of this issue with table creation, index creation, some inserts and query statements?

**Comment by adelapena** [comment]
See #210
