### ISSUE TITLE
TimestampType can not be mapped to Long

### ISSUE THREAD

**Issue by wanghong230** [Stratio/cassandra-lucene-index#177]
2016/07/19 15:39:19 table.go:513: CREATE TABLE test_TestKeyValueTableLuceneCreate (val4 boolean, val7 timestamp, val8 uuid, val1 text, val11 set<text>, val3 bigint, val5 list<text>, val6 map<text, text>, val9 text, val10 timeuuid, val2 double, PRIMARY KEY(val1, val2))
2016/07/19 15:39:19 table.go:222: 
CREATE CUSTOM INDEX test_TestKeyValueTableLuceneCreate_lucene_idx ON test_TestKeyValueTableLuceneCreate()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{fields:{val1:{type:"string",validated:true},val10:{type:"string",validated:true},val11:{type:"string",validated:true},val2:{type:"double",validated:true},val3:{type:"long",validated:true},val4:{type:"boolean",validated:true},val5:{type:"string",validated:true},val6:{type:"string",validated:true},val7:{type:"long",validated:true},val8:{type:"string",validated:true},val9:{type:"string",validated:true}}}'
};

2016/07/19 15:39:20 db.go:93: failed to run query: 
CREATE CUSTOM INDEX test_TestKeyValueTableLuceneCreate_lucene_idx ON test_TestKeyValueTableLuceneCreate()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{fields:{val1:{type:"string",validated:true},val10:{type:"string",validated:true},val11:{type:"string",validated:true},val2:{type:"double",validated:true},val3:{type:"long",validated:true},val4:{type:"boolean",validated:true},val5:{type:"string",validated:true},val6:{type:"string",validated:true},val7:{type:"long",validated:true},val8:{type:"string",validated:true},val9:{type:"string",validated:true}}}'
};
2016/07/19 15:39:20 db.go:94: 'schema' is invalid : Type 'org.apache.cassandra.db.marshal.TimestampType' in column 'val7' is not supported by mapper 'val7'
2016/07/19 15:39:20 table.go:225:error on query: 
CREATE CUSTOM INDEX test_TestKeyValueTableLuceneCreate_lucene_idx ON test_TestKeyValueTableLuceneCreate()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{fields:{val1:{type:"string",validated:true},val10:{type:"string",validated:true},val11:{type:"string",validated:true},val2:{type:"double",validated:true},val3:{type:"long",validated:true},val4:{type:"boolean",validated:true},val5:{type:"string",validated:true},val6:{type:"string",validated:true},val7:{type:"long",validated:true},val8:{type:"string",validated:true},val9:{type:"string",validated:true}}}'
};
, underlying DB error 'schema' is invalid : Type 'org.apache.cassandra.db.marshal.TimestampType' in column 'val7' is not supported by mapper 'val7'

val7 is timestamp type in cassandra, it can not be mapped to "long" type in lucene index.

This is not consistent with the doc https://github.com/Stratio/cassandra-lucene-index/blob/3.7.0/doc/documentation.rst#long-mapper

**Comment by adelapena** [comment]
Hi @wanghong230, 

You are right, and the same happens with `date` columns. We [have just fixed it](https://github.com/Stratio/cassandra-lucene-index/commit/39b1207518e70b86975021cc7e5ba1227c9604b5) at [branch 3.0.8](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.8), in such a way that `timestamp` and `date` columns can be indexed with `long` and `integer` mappers. `long` mapper indexes the number of milliseconds, and `integer` mapper indexes the number of days. 

Thanks for reporting,
