### ISSUE TITLE
How to query a Time Range of +10 and -10 minutes? 

### ISSUE THREAD

**Issue by kifkif1** [Stratio/cassandra-lucene-index#178]
Hi,

I'm trying to read out data of a time range of +10 and -10 minutes of a timestamp that I pass. 
Example:

I have a query that returns a timestamp, for example '2015-10-07 07:18:43+0000'.
I want to use that timestamp to read out all data that lies within 10 minutes earlier and 10 minutes later than this timestamp. 

I think I can calculate the timestamp by substracting/adding 10*1000 (10 minutes) and then use https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.6/doc/documentation.rst#date-range-search but is there a built in way for this? When looking at the geospatial queries, there is a built in query that allows to search data within a distance of i.e. 5km.  Or would you suggest me to calculate the time myself and then use the date-range search?

My table looks like this:

```
CREATE TABLE test.data (
    id text,
    date text,
    ts timestamp,
    latitude float,
    longitude float,
    payload map<text, text>,
    PRIMARY KEY ((id, date), ts)
) 
```

My lucene index:
```
CREATE CUSTOM INDEX lucene_index ON data ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '60',
    'schema' : '{
        fields : {
			ts  : {type : "date", pattern : "yyyy-MM-dd"},
			payload : { type : "string"},
			place : {type : "geo_point", latitude:"latitude", longitude:"longitude"}
        }
    }'
};
```

Another question:
I am currently running a geospatial query on my data. The query will return some timestamps and I need more data around that point in the data (as described above). Can I combine the two queries? For example: First run the geospatial query, then use the found data points to retrieve more data based on the time range. Is it possible to combine the query? Or is it a good idea to split up the query? 

Thanks for the great work of this indexing solution btw!

**Comment by adelapena** [comment]
Hi @kifkif1,

You are indexing the timestamp column with a precission of days. Instead, you should index it with a precision of minutes:

```
CREATE CUSTOM INDEX lucene_index ON data ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '60',
    'schema' : '{
        fields : {
            ts  : {type : "date", pattern : "yyyy-MM-dd HH:mm"},
            payload : { type : "string"},
            place : {type : "geo_point", latitude:"latitude", longitude:"longitude"}
        }
    }'
};
```
(note the hours and the minutes added to the date mapper pattern)

Date range search is intended to be used with [date range mapper](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/doc/documentation.rst#date-range-mapper), which indexes time durations comprising a start date and a stop date. I have just updated [date range search documentation](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/doc/documentation.rst#date-range-search) to be clearer about this.

You can search for dates within a ten  minutes range with a regular [range search](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/doc/documentation.rst#range-search), for example:
```
INSERT INTO data(id, date, ts) VALUES ('a', 'a', '2016-07-21 10:30');
INSERT INTO data(id, date, ts) VALUES ('b', 'b', '2016-07-21 10:40');
INSERT INTO data(id, date, ts) VALUES ('c', 'c', '2016-07-21 10:50');

SELECT * FROM test.data WHERE expr(lucene_index, '{filter:{
	type: "range", 
	field: "ts", 
	lower: "2016-07-21 10:37", 
	upper: "2016-07-21 10:47", 
	include_lower: true
}}');
```
You can combine any number of search clauses inside a [boolean search](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/doc/documentation.rst#boolean-search). However, using the values of a result set to search for another set of rows (that is not a subset of the first result set) would be a join operation, which is not supported. As you probably know, join operations are well known by their scalability problems, and they are usually avoided in NoSQL scalable databases in favour of denormalization. Said that, I think that you can happily use the two-phase approach if the number of sub-queries produced by the first query is not very large.

I hope it helps,

**Comment by kifkif1** [comment]
Hi @adelapena, 

this is perfect. Thanks for your fast support dude!
