### ISSUE TITLE
filter match request does not work with map field

### ISSUE THREAD

**Issue by forumjava** [Stratio/cassandra-lucene-index#18]
Hi,

Using filter match request with map field does not retrieve the value correctly.

Below the steps to reproduce:

//create table
create table mytesttable (idcol int, testtextcol text, testmapcol map<text,text>, cassandra_lucene_index text, primary key (idcol));

//create index
CREATE CUSTOM INDEX IF NOT EXISTS lucene_test_idx ON mytesttable (cassandra_lucene_index) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds' : '1', 'schema' : '{ fields : {testtextcol: {type: "string"}, testmapcol: {type: "string"}}}'};

//create test data
insert into mytesttable (idcol, testtextcol, testmapcol) values (1, 'row1', {'attb1': 'row1attb1Val', 'attb2': 'row1attb2Val', 'attb3': 'row1attb3Val'});
insert into mytesttable (idcol, testtextcol, testmapcol) values (2, 'someLongRow2Value', {'attb1': 'someLongattb1Val', 'attb2': 'attb2Val', 'attb3': 'attb3Val'});
insert into mytesttable (idcol, testtextcol, testmapcol) values (3, 'row3', {'attb1': 'row2attb1Val', 'attb2': 'row2attb2Val', 'attb3': 'row2attb3Val'});
insert into mytesttable (idcol, testtextcol, testmapcol) values (4, 'row4', {'attb2': 'row3attb2Val', 'attb3': 'row3attb3Val'});

//this query retrieves the data fine
select * from mytesttable where cassandra_lucene_index = '{filter : {type: "match", field: "testtextcol", value: "row1"}}';

//but this query does not
select * from mytesttable where cassandra_lucene_index = '{filter : {type: "match", field: "testmapcol.attb1", value: "row1attb1Val"}}';

Please let me know if you need any other details.

**Comment by adelapena** [comment]
Hi,

This issue has the same cause as [issue#16](https://github.com/Stratio/cassandra-lucene-index/issues/16), and it has been fixed at [master branch](https://github.com/Stratio/cassandra-lucene-index/commit/e9025dda3feee0a5d1d0b2d4a92d5eaddeb15334).

Thanks

**Comment by forumjava** [comment]
Thanks, this works now!

**Comment by forumjava** [comment]
Can you please confirm, this was working fine with 2.1.8.1-SNAPSHOT but has stopped working again in 2.1.8.2.

**Comment by adelapena** [comment]
It's failing due to a bug introduced with issue #27. It is applying the default analyzer to the map fields, instead of the desired keyword analyzer, so the field was being indexed with lower case. I have just fixed it in master branch, and I have added some tests.

**Comment by forumjava** [comment]
Cool. Tried from the master and it works fine now.

Thanks!
