### ISSUE TITLE
How to determine if building the index finished?

### ISSUE THREAD

**Issue by juvlarN** [Stratio/cassandra-lucene-index#180]
Hi,

is there a way to check whether the index has been successfully built on my table? 
I have a lot of rows and indexing the data takes some time. 

Are any logs written when something goes wrong? 

Thanks

**Comment by adelapena** [comment]
Hi,

Unfortunately Cassandra doesn't offer a friendly way to check when a secondary index build has finished.

You can check if an index is completely built checking if it appears in the JMX property org.apache.cassandra.db.Table.[KEYSPACE_NAME].[TABLE_NAME].BuiltIndexes.

You can find [an example of how to programmatically check](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/testsAT/src/test/java/com/stratio/cassandra/lucene/testsAT/util/CassandraUtils.java#L412) index creation in the acceptance test package. You can also use a visual JMX client such as JConsole or Java Mission Control.

I hope it helps.

**Comment by juvlarN** [comment]
Just in case someone else runs into this:

Accessing Cassandra with a JMX Client does not work out of the box.
You have to alter `cassandra-env.sh` with the following changes:

- Set variable `LOCAL_JMX=no`
- Set authentication settings according to http://docs.datastax.com/en/cassandra/2.1/cassandra/security or set the authentication to false for the time of your development if you're lazy: `JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.authenticate=false" `. 
- Set `JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=YOUR_NODE_IP_HERE"`
- Restart Cassandra `sudo service cassandra restart`

You should be able to connect with, for example, JClient by entering the IP of the node as well as the JMX port (7199 by default).
