### ISSUE TITLE
geo_shape query in Cassandra 3.0.8

### ISSUE THREAD

**Issue by guyneedham** [Stratio/cassandra-lucene-index#189]
I'm using Cassandra 3.0.8 and built from branch 3.0.8.1. I'm able to get geo_bbox queries and geo_distance queries to work, however I'm unable to get geo_shape queries to run.

```
-- this works
select * from hotspots where expr(point_idx, '{
 filter: {
       type: "geo_bbox",
       field: "geo_point",
       min_latitude: -90.0,
       max_latitude: 90.0,
       min_longitude: -180.0,
       max_longitude: 180.0
 }
}');

-- this works
select * from hotspots where expr(point_idx, '{
filter: {
    type: "geo_distance", 
    field: "geo_point", 
    latitude: 40.3930, 
    longitude: -3.7328, 
    max_distance: "1km"}
}');

-- this fails
select * from hotspots where expr(point_idx, '{
filter: {
    type: "geo_shape", 
    field: "geo_point", 
    shape: {
	type: "wkt",
	value: "POLYGON((-0.07 51.63, 0.03 51.54, 0.05 51.65, -0.07 51.63))"
    }, 
    operation: "contains"
}}');
```

The error is:
`
InvalidRequest: code=2200 [Invalid query] message="Unparseable JSON search: {
filter: {
    type: "geo_shape", 
    field: "geo_point", 
    shape: {
type: "wkt",
value: "POLYGON((-0.07 51.63, 0.03 51.54, 0.05 51.65, -0.07 51.63))"
    }, 
    operation: "contains"
}}"
`

I'm wondering if this is expected behaviour?

**Comment by adelapena** [comment]
Hi @guyneedham,

The failing query is using the new syntax that [was added in 3.0.8.2 to allow associativity in search-time geospatial transformations](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/CHANGELOG.md#3082-august-29-2016). With 3.0.8.1 you should use [the old syntax](https://github.com/Stratio/cassandra-lucene-index/blob/3.0.8.1/doc/documentation.rst#geo-shape-search):
```
select * from hotspots where expr(point_idx, '{
filter: {
    type: "geo_shape", 
    field: "geo_point", 
    shape: "POLYGON((-0.07 51.63, 0.03 51.54, 0.05 51.65, -0.07 51.63))", 
    operation: "contains"
}}');
```
I hope this helps.

**Comment by guyneedham** [comment]
Thanks very much @adelapena this resolves my issue.
