### ISSUE TITLE
Timeout on malformed query

### ISSUE THREAD

**Issue by totalwar** [Stratio/cassandra-lucene-index#20]
Hello,
I got timeout if parts of Boolean query is null, for example:

    SELECT * FROM table WHERE lucene='{"query":{"type":"boolean", must:null}}'; // timeout
    // OperationTimedOut: errors={}, last_host=127.0.0.1

But,

    SELECT * FROM table WHERE lucene='{"query":{"type":"boolean", must:{}}}'; 
    //InvalidRequest: code=2200 [Invalid query] message="Unformateable JSON search: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token at [Source: java.io.StringReader@48575ddc; line: 1, column: 27] (through reference chain: com.stratio.cassandra.lucene.search.SearchBuilder["query"]->com.stratio.cassandra.lucene.search.condition.builder.BooleanConditionBuilder["must"])"

Can you add some validations?

**Comment by ealonsodb** [comment]
I have added some validations in BooleanQuery, 

Now BooleanQuery treats null values like missing, so: 

```SELECT * FROM table WHERE lucene='{"query":{"type":"boolean", must:null}}';```
is treated just like 
```SELECT * FROM table WHERE lucene='{"query":{"type":"boolean"}}';```

and now throws a IllegalArgumentException because it is a empty query.

The fixes are in the master branch, in near future in the next release.

Thank you.

**Comment by totalwar** [comment]
Thanks
