### ISSUE TITLE
Problems with batch statements and cassandra-lucene-index

### ISSUE THREAD

**Issue by ddieterly** [Stratio/cassandra-lucene-index#205]
We are seeing inserts dropped when using batch statements and cassandra-lucene-index. Not all insert statements are resulting in rows being added to the database. Anyone else seeing this? Is this a known issue? Thanks.

**Comment by ddieterly** [comment]
Seems that when we set the timeout on the session to longer period, we stop losing the rows. So, the problem was probably that we were getting timeouts on the session and not handling them correctly.

**Comment by adelapena** [comment]
Hi @ddieterly,

So, is it not an problem? Can we close this issue?
