### ISSUE TITLE
Indexed time is offset in Date Mapper

### ISSUE THREAD

**Issue by juvlarN** [Stratio/cassandra-lucene-index#206]
Hi,

I have a Date mapper in my index. When I query that field, the output is not as expected:

In cqlsh, `select * from ...; ` shows some rows with the following timestamp:
`2016-09-07 15:10:10+0000`

However, when I run the following query, the output shows 0 results but there should be at least several thousand rows for the time range.

```
select * from ... WHERE expr(lucene_idx, '{filter:{
    type: "range", 
    field: "time", 
    lower: "2016-09-07 14:00", 
    upper: "2016-09-07 16:00", 
    include_lower: true
}}');
```

`upper: "2016-09-07 17:00"` does still show no results.

`upper: "2016-09-07 18:00"` finally shows results.

Why is this happening? How am I seeing the output of 15:10:10+0000 in cqlsh, but I am only able to query the data when i increase the upper bound to 18:00? 

My index:
```
CREATE CUSTOM INDEX lucene_idx ON ... () USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds': '1', 'schema': '{
        fields : {
              time  : {type : "date", pattern : "yyyy-MM-dd HH:mm"},
               ...
        }
    }'};
```

The field time is of type timestamp in my schema: `time timestamp`

When I query `SELECT time, blobAsBigint(timestampAsBlob(time)) FROM ...;`  the internal timestamps seem to be correct, for example: 
```
 time                       | system.blobasbigint(system.timestampasblob(time))
--------------------------+-------------------------------------------------
 2016-09-07 15:10:09+0000 |                                   1473261009900
```
I am ingesting UTC timestamps.

I am using version cassandra-lucene-index-plugin-3.0.8.2 and cassandra 3.0.8.
From the changelogs I can see that something happened to the date mappers recently, especially https://github.com/Stratio/cassandra-lucene-index/issues/177. Maybe this is related?

**Comment by ealonsodb** [comment]
Hi @juvlarN:
The main problem with dates is the timezone and the machine timezone settings.
I have tested this with the next example:
```

CREATE KEYSPACE issue_206 with replication = {'class' : 'SimpleStrategy', 'replication_factor' : '1' }; 

CREATE TABLE issue_206.test (
    id int, 
    a_timestamp timestamp, 
    lucene text, 
    PRIMARY KEY ((id))
); 

CREATE CUSTOM INDEX idx ON issue_206.test  (lucene) 
USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
	'refresh_seconds':'1',
	'indexing_threads':'0',
	'schema':'{
		"fields":{
			a_timestamp  : {type : "date", pattern : "yyyy-MM-dd HH:mm"}
		}
	}'
}; 
INSERT INTO issue_206.test (id, a_timestamp ) VALUES(1,'2016-09-07 15:10:10+0000'); 

SELECT * FROM issue_206.test WHERE expr(idx, '{filter:{
    type: "range", 
    field: "a_timestamp", 
    lower: "2016-09-07 14:00", 
    upper: "2016-09-07 16:00", 
    include_lower: true
}}');

```
The problem is cassandra-lucene-index parses the query dates using machine local timezone, So in my personal case 2016-09-07 16:00 (UTC+2) is equal to 2016-09-07 14:00(UTC). 

So, the solution to this is to use TimeZones in the queries too.

```

CREATE KEYSPACE issue_206 with replication = {'class' : 'SimpleStrategy', 'replication_factor' : '1' }; 

CREATE TABLE issue_206.test (
    id int, 
    a_timestamp timestamp, 
    lucene text, 
    PRIMARY KEY ((id))
); 

CREATE CUSTOM INDEX idx ON issue_206.test  (lucene) 
USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
	'refresh_seconds':'1',
	'indexing_threads':'0',
	'schema':'{
		"fields":{
			a_timestamp  : {type : "date", pattern : "yyyy-MM-dd HH:mmZ"}
		}
	}'
}; 

```

**Comment by juvlarN** [comment]
@ealonsodb 
It works, thanks. I couldn't find anything about the timezone in the documentation. Maybe it might be a good idea to add it there.

**Comment by ealonsodb** [comment]
Good idea @juvlarN , thank you.
