### ISSUE TITLE
Documentation is wrong for BBox geo shape search

### ISSUE THREAD

**Issue by juvlarN** [Stratio/cassandra-lucene-index#207]
When taking the BBox query straight from the documentation, the following error occurs:

```
ServerError: <ErrorMessage code=0000 [Server error] message="com.stratio.cassandra.lucene.IndexException: Unparseable JSON search: {
   filter: {
      type: "geo_shape",
      field: "place",
      relation: "intersects",
      shape: {
         type: "bbox",
         shape: {
            type: "wkt",
            value: "LINESTRING(-80.90 29.05, -80.51 28.47, -80.60 28.12, -80.00 26.85, -80.05 26.37)"
         }
      }
   }
}">

```

The query run was taken from here https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/doc/documentation.rst#wkt-shape
```
SELECT * FROM x WHERE expr(lucene_idx,'{
   filter: {
      type: "geo_shape",
      field: "place",
      relation: "intersects",
      shape: {
         type: "bbox",
         shape: {
            type: "wkt",
            value: "LINESTRING(-80.90 29.05, -80.51 28.47, -80.60 28.12, -80.00 26.85, -80.05 26.37)"
         }
      }
   }
}');
```

How to fix this? 

Also, I have another question:
Is the performance of https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/doc/documentation.rst#geo-bbox-search better than the query above?

**Comment by adelapena** [comment]
Hi, @juvlarN,

You are right, the documentation is wrong. The proper syntax is:
```
SELECT * FROM places WHERE expr(places_idx,'{
   filter: {
      type: "geo_shape",
      field: "place",
      operation: "intersects",
      shape: {
         type: "bbox",
         shape: {
            type: "wkt",
            value: "LINESTRING(-80.90 29.05, -80.51 28.47, -80.60 28.12, -80.00 26.85, -80.05 26.37)"
         }
      }
   }
}');
```
I have just [fixed](https://github.com/Stratio/cassandra-lucene-index/commit/7120cfcc52a914a509bd6de62d27a200516da3de) it.

About ``geo_bbox`` search, this is just syntactic sugar for a ``geo_shape`` search defining a rectangle, but it is not able to calculate a bounding box around a line string as it is done in the example.

Thanks for reporting.
