### ISSUE TITLE
Add  a new column on existing keyspace, how to extend the Lucene index?

### ISSUE THREAD

**Issue by lucevers** [Stratio/cassandra-lucene-index#21]
If I add a new field (Column) and I like to use this column in the Lucene index.
 How can I add a new field to the existing Lucene index?

 Possible option = delete the Custum index and create the index again with the new field.
 But how can I restart the index process on the old data?

**Comment by adelapena** [comment]
The only way to add an new mapping is to drop the index, even if it's not yet built, and create a new one with new schema. This will stop any running indexing process. All the stored data will be indexed again with the new schema.

**Comment by lucevers** [comment]
Thanks for info!
