### ISSUE TITLE
Was RangeCondition.range method removed ?

### ISSUE THREAD

**Issue by ipvpbr** [Stratio/cassandra-lucene-index#212]
Hi,
First of all thanks very much for providing the cassandra-lucene-index.

I just upgraded to 3.9.
Eclipse is reporting a compile error saying that com.stratio.cassandra.lucene.builder.search.condition.RangeCondition.range does not exist.

Was the .range method removed ?

Thanks
IPVP

**Comment by adelapena** [comment]
Hi @ipvpbr,

No it hasn't be removed. Are you trying to compile the query builder from the sources, or just importing the dependency from Maven? It seems that something has gone wrong with out continuous delivery system and [we have published the 3.9.0 and 3.8.0 artefacts with a ``-RELEASE``suffix appended](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.stratio.cassandra%22%20AND%20a%3A%22cassandra-lucene-index-builder%22), we hope to fix it along today.

**Comment by ipvpbr** [comment]
The issue happens with both: building from sources and getting the jar from Maven.

The jar file was obtained from Maven at :
https://mvnrepository.com/artifact/com.stratio.cassandra/cassandra-lucene-index-builder/3.9.0-RELEASE

The source were compiled following the steps described at : 
https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.9/doc/documentation.rst#installation

The issue is with the builder only.  It does not find the RangeCondition.range method. So the java classes building search criteria using RangeCondition.range method are all broken and wont compile.

The  3.9 plugin seems to be working fine. I built it from the sources.

Everything works fine when I move back to the version(cassandra-lucene-index-builder-3.7.2-RC1-SNAPSHOT.jar)  that was using before upgrading to 3.9.

Thanks
IPVP

**Comment by ealonsodb** [comment]
Hi @ipvpbr: 

[com.stratio.cassandra.lucene.builder.search.condition.RangeCondition](https://github.com/Stratio/cassandra-lucene-index/blob/3.7.2/builder/src/main/java/com/stratio/cassandra/lucene/builder/search/condition/RangeCondition.java) has never had a range method. 

If you refer to **range** method to build a RangeCondition query, it is in [com.stratio.cassandra.lucene.builder.Builder]() both on [3.7.2](https://github.com/Stratio/cassandra-lucene-index/blob/3.7.2/builder/src/main/java/com/stratio/cassandra/lucene/builder/Builder.java#L403) and (future) 3.9.0. 

I am resolving the CD problem and we will release both 3.8.0 and 3.9.0 today.

**Comment by ipvpbr** [comment]
Just to clarify... that is the .range() method call that is  not compiling on 3.9

`....
RangeCondition condition = RangeCondition.range("updatedate").lower(dfISO.format(fromUpdateDateBegin)).upper(dfISO.format(toUpdateDateEnd)).includeLower(true).includeUpper(true);
....`

**Comment by adelapena** [comment]
I see.

We don't remember this method at all, and it doesn't appear [in GitHub history](https://github.com/Stratio/cassandra-lucene-index/commits/branch-3.9/builder/src/main/java/com/stratio/cassandra/lucene/builder/search/condition/RangeCondition.java) either...

It seems to always have been in [com.stratio.cassandra.lucene.builder.Builder.range](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.9/builder/src/main/java/com/stratio/cassandra/lucene/builder/Builder.java#L403), together with all the other static query methods.

In which version have you seen these method?

**Comment by adelapena** [comment]
Mmmh, I see what is happening. 

Indeed, the ``range`` method has always been in com.stratio.cassandra.lucene.builder.Builder. But RangeCondition inherited if from Builder before 3.0.8, and now RangeCondition is not a child of Builder anymore.

**Comment by ipvpbr** [comment]
Until 3.7.2  it was working fine.

I can adjust my code, if that is the long term direction. Please let me know.

**Comment by adelapena** [comment]
Yes, this is the long term direction. The original purpose has always been to use ``Builder.range``, as it is shown in the [documentation examples](https://github.com/Stratio/cassandra-lucene-index/blob/3.7.1/doc/documentation.rst#range-search). The inheritance of the static methods has been an unexpected an undesired lateral effect, as it also allowed to do confusing things such as ``RangeCondition.fuzzy`` or, even worst, ``RangeCondition.index``.

**Comment by ipvpbr** [comment]
OK. I will adjust my code.

Thanks for the promptly answers and thanks for providing this extremely useful solution.

IPVP

**Comment by adelapena** [comment]
You are very welcome.
