### ISSUE TITLE
How to query data with pagination in cassandra-lucene-index?

### ISSUE THREAD

**Issue by lynchlee** [Stratio/cassandra-lucene-index#213]
Faced a problem: How to query data with pagination in cassandra-lucene-index?
Should someone help me, thx !!

**Comment by lynchlee** [comment]
Cassandra support limit query like 'select * from table limit 100', well, how could query data like sql in mysql 'select * from table limit 1,100' to fetch data of page two.

**Comment by lynchlee** [comment]
And how could we get the total items of one table with cassandra-lucene-index?

**Comment by adelapena** [comment]
Hi @lynchlee,

Pagination with the Lucene index works exactly in the same way as regular Cassandra queries. Instead of using an offset, deep paging is achieved providing a pointer to the last visited row. This is done automatically by CQL providing a fetch size. For example, with ``cqlsh`` you can request 100 rows in pages of 10 rows each:
```sql
PAGING 10
SELECT * FROM test LIMIT 100;
```
There is more information about this in [CQL documentation](http://docs.datastax.com/en/cql/3.1/cql/cql_reference/paging.html).

You can do the same with DataStax Java driver:
```
// At initialization:
Cluster cluster = Cluster.builder()
    .addContactPoint("127.0.0.1")
    .withQueryOptions(new QueryOptions().setFetchSize(2000))
    .build();

// Or at runtime:
cluster.getConfiguration().getQueryOptions().setFetchSize(2000);

// Or per query:
Statement statement = new SimpleStatement("SELECT * FROM test");
statement.setFetchSize(2000);
```
You can find more info about this in [the Java driver documentation](https://datastax.github.io/java-driver/2.1.8/features/paging/).

About counting rows, it works in the same way as Cassandra. You can use [SELECT COUNT(*)](https://docs.datastax.com/en/cql/3.1/cql/cql_reference/select_r.html), but this is probably a bad idea in a production cluster due to the performance cost. You should use Spark or Hadoop for this kind of distributed aggregations, or keep the count of items in a different system (maybe a counter column?). As a work around, you can also use the index [JMX interface](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.9/doc/documentation.rst#jmx-interface) to see the number of indexed documents in each node, and do the math to calculate the number of logical rows.

**Comment by lynchlee** [comment]
@adelapena Thanks very much !!
 Using SELECT COUNT(*) in a production env is realy a bad idea . Instead, I am using counter column .

Also, I got bad performance of cassandra-lucene-index, here is my cluster env and my method, could you take a look and point out my fault ?? Thx !

OS: CentOS Linux release 7.2.1511
Nodes: 3
Cassandra version: 3.7
Runtime JVM : -Xms8192M -Xmx8192M -Xmn2048M
cassandra-lucene-index: 3.7.2
CPU: 8 cores / node
Mem: 32G / node
Disk: 50G / node

Table:
CREATE TABLE usertable.usertable (
    y_id text PRIMARY KEY,
    field0 text,
    field1 text,
    field2 text,
    field3 text,
    field4 text,
    field5 text,
    field6 text,
    field7 text,
    field8 text,
    field9 text,
    lucene text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX usertable_index ON usertable.usertable (lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds': '1', 'schema': '{
    fields: {
      y_id: {type: "string"},
      field0: {type: "string"},
      field1: {type : "text", analyzer : "english"}
    }
  }'};

Stress test tool: YCSB-0.11.0
config/cassandra.properties:
hosts = 172.17.18.171,172.17.18.172,172.17.18.173
port = 9042
cassandra.keyspace = usertable
cassandra.username =
cassandra.password =
cassandra.readconsistencylevel = QUORUM
cassandra.writeconsistencylevel = QUORUM
cassandra.coreconnections = 100
cassandra.maxconnections = 200
cassandra.connecttimeoutmillis = 1000000000
cassandra.readtimeoutmillis  = 1000000000
workloads/workloadlucene:
recordcount=500000
operationcount=500000
workload=com.yahoo.ycsb.workloads.CoreWorkload
readallfields=true
readproportion=1
updateproportion=0
scanproportion=0
insertproportion=0
requestdistribution=zipfian
requestdistribution=zipfian

Command  to run: ./bin/ycsb run cassandra-cql -P workloads/workloadlucene -P configs/cassandra.properties -p columnfamily=usertable -s -threads 50 > ./50threadsRContain50w-log.log
Threads :  50
Read keys: 50w
CQL to run: SELECT * FROM usertable WHERE expr(usertable_index, '{"filter":[{"type":"boolean","must":[{"type":"wildcard","field":"field0","value":"*a"}]}]}') limit 1;
Result:
[OVERALL], RunTime(ms), 5760943.0
[OVERALL], Throughput(ops/sec), 86.79134648615687
[TOTAL_GCS_PS_Scavenge], Count, 87.0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 192.0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0033327877050684236
[TOTAL_GCS_PS_MarkSweep], Count, 0.0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 87.0
[TOTAL_GC_TIME], Time(ms), 192.0
[TOTAL_GC_TIME_%], Time(%), 0.0033327877050684236
[READ], Operations, 0.0
[READ], AverageLatency(us), NaN
[READ], MinLatency(us), 9.223372036854776E18
[READ], MaxLatency(us), 0.0
[READ], 95thPercentileLatency(us), 0.0
[READ], 99thPercentileLatency(us), 0.0
[READ], Return=NOT_FOUND, 500000
[CLEANUP], Operations, 50.0
[CLEANUP], AverageLatency(us), 45693.84
[CLEANUP], MinLatency(us), 2.0
[CLEANUP], MaxLatency(us), 2285567.0
[CLEANUP], 95thPercentileLatency(us), 4.0
[CLEANUP], 99thPercentileLatency(us), 2285567.0
[READ-FAILED], Operations, 500000.0
[READ-FAILED], AverageLatency(us), 575023.83296
[READ-FAILED], MinLatency(us), 53984.0
[READ-FAILED], MaxLatency(us), 2621439.0
[READ-FAILED], 95thPercentileLatency(us), 1000447.0
[READ-FAILED], 99thPercentileLatency(us), 1336319.0

**Comment by adelapena** [comment]
Could you please provide benchmark results without Lucene indexes in order to have a reference point?

By the way, the query:
```sql
SELECT * FROM usertable WHERE expr(usertable_index, '{"filter":[{"type":"boolean","must":[{"type":"wildcard","field":"field0","value":"*a"}]}]}') limit 1;
```
Is a leading wildcard, one of the worst types of query for Apache Lucene, disabled by default in several implementations:
http://wiki.apache.org/lucene-java/LuceneFAQ#What_wildcard_search_support_is_available_from_Lucene.3F
http://stackoverflow.com/questions/11766351/understanding-lucene-leading-wildcard-performance
http://www.gossamer-threads.com/lists/lucene/java-user/175734
http://elasticsearch-users.115913.n3.nabble.com/Leading-Wildcard-Performance-td2213543.html
Leading wildcard queries full-scan each of the involved per-node indexes. Even worst, the query is not directed to any specific partition, so, depending of your data, it could be full-scanning each node in the cluster...

**Comment by lynchlee** [comment]
OK。 I will test again using Prefix queries, thank you.

**Comment by lynchlee** [comment]
Results without Lucene indexes:
CQL：

    SELECT * FROM usertable limit 1;

TRACING:
    
    Tracing session: d622c000-921c-11e6-b285-cf1ef6f91596

     activity                                                                                                                  | timestamp                  | source        | source_elapsed | client
    ---------------------------------------------------------------------------------------------------------------------------+----------------------------+---------------+----------------+---------------
                                                                                                        Execute CQL3 query | 2016-10-14 22:45:23.076000 | 172.17.18.171 |              0 | 172.17.18.171
                               RANGE_SLICE message received from /172.17.18.171 [MessagingService-Incoming-/172.17.18.171] | 2016-10-14 22:45:04.717000 | 172.17.18.173 |            903 | 172.17.18.171
     Executing seq scan across 1 sstables for (min(-9223372036854775808), min(-9223372036854775808)] [SharedPool-Worker-1] | 2016-10-14 22:45:04.719000 | 172.17.18.173 |           2897 | 172.17.18.171
                                                                   Read 1 live and 0 tombstone cells [SharedPool-Worker-1] | 2016-10-14 22:45:04.720000 | 172.17.18.173 |           3609 | 172.17.18.171
                                                                Enqueuing response to /172.17.18.171 [SharedPool-Worker-1] | 2016-10-14 22:45:04.720000 | 172.17.18.173 |           3833 | 172.17.18.171
                             Sending REQUEST_RESPONSE message to /172.17.18.171 [MessagingService-Outgoing-/172.17.18.171] | 2016-10-14 22:45:04.721000 | 172.17.18.173 |           4662 | 172.17.18.171
                                                          Parsing SELECT * FROM usertable limit 1\n; [SharedPool-Worker-1] | 2016-10-14 22:45:23.078000 | 172.17.18.171 |           3365 | 172.17.18.171
                                                                                 Preparing statement [SharedPool-Worker-1] | 2016-10-14 22:45:23.078000 | 172.17.18.171 |           3848 | 172.17.18.171
                                                                           Computing ranges to query [SharedPool-Worker-1] | 2016-10-14 22:45:23.079000 | 172.17.18.171 |           4388 | 172.17.18.171
 Submitting range requests on 769 ranges with a concurrency of 1 (472.63638 rows per range expected) [SharedPool-Worker-1] | 2016-10-14 22:45:23.080000 | 172.17.18.171 |           5050 | 172.17.18.171
                                                                 Enqueuing request to /172.17.18.173 [SharedPool-Worker-1] | 2016-10-14 22:45:23.081000 | 172.17.18.171 |           6567 | 172.17.18.171
                                                               Submitted 1 concurrent range requests [SharedPool-Worker-1] | 2016-10-14 22:45:23.082000 | 172.17.18.171 |           7239 | 172.17.18.171
                                  Sending RANGE_SLICE message to /172.17.18.173 [MessagingService-Outgoing-/172.17.18.173] | 2016-10-14 22:45:23.082000 | 172.17.18.171 |           7590 | 172.17.18.171
                          REQUEST_RESPONSE message received from /172.17.18.173 [MessagingService-Incoming-/172.17.18.173] | 2016-10-14 22:45:23.092000 | 172.17.18.171 |          17030 | 172.17.18.171
                                                             Processing response from /172.17.18.173 [SharedPool-Worker-3] | 2016-10-14 22:45:23.092000 | 172.17.18.171 |          17386 | 172.17.18.171
                                                                                                          Request complete | 2016-10-14 22:45:23.094102 | 172.17.18.171 |          18102 | 172.17.18.171

Report: 

    [OVERALL], RunTime(ms), 251115.0
    [OVERALL], Throughput(ops/sec), 1991.1196065547658
    [TOTAL_GCS_PS_Scavenge], Count, 116.0
    [TOTAL_GC_TIME_PS_Scavenge], Time(ms), 199.0
    [TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.07924656034087968
    [TOTAL_GCS_PS_MarkSweep], Count, 0.0
    [TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
    [TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
    [TOTAL_GCs], Count, 116.0
    [TOTAL_GC_TIME], Time(ms), 199.0
    [TOTAL_GC_TIME_%], Time(%), 0.07924656034087968
    [READ], Operations, 500000.0
    [READ], AverageLatency(us), 24645.036296
    [READ], MinLatency(us), 5088.0
    [READ], MaxLatency(us), 1814527.0
    [READ], 95thPercentileLatency(us), 62751.0
    [READ], 99thPercentileLatency(us), 121535.0
    [READ], Return=OK, 500000
    [CLEANUP], Operations, 50.0
    [CLEANUP], AverageLatency(us), 45203.06
    [CLEANUP], MinLatency(us), 1.0
    [CLEANUP], MaxLatency(us), 2260991.0
    [CLEANUP], 95thPercentileLatency(us), 17.0
    [CLEANUP], 99thPercentileLatency(us), 2260991.0

**Comment by lynchlee** [comment]
Results with Lucene indexes using Prefix Query:

CQL：
    
    SELECT * FROM usertable limit 1;

TRACING:

    Tracing session: 71ba9920-921d-11e6-b285-cf1ef6f91596

     activity                                                                                                                                       |     timestamp                  | source        | source_elapsed | client
    ------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------+---------------+----------------+---------------
                                                                                                                                 Execute CQL3 query | 2016-10-14 22:49:44.114000 | 172.17.18.171 |              0 | 172.17.18.171
                                                       RANGE_SLICE message received from /172.17.18.171 [MessagingService-Incoming-/172.17.18.171] | 2016-10-14 22:49:25.925000 | 172.17.18.173 |             78 | 172.17.18.171
                                                                                                      Building Lucene search [SharedPool-Worker-3] | 2016-10-14 22:49:25.926000 | 172.17.18.173 |           1580 | 172.17.18.171
                                                                                          Lucene index searching for 100 rows [SharedPool-Worker-3] | 2016-10-14 22:49:26.052000 | 172.17.18.173 |         127677 | 172.17.18.171
                                                               Executing read on usertable.usertable using index usertable_index [SharedPool-Worker-3] | 2016-10-14 22:49:26.058000 | 172.17.18.173 |         133936 | 172.17.18.171
                                                                                             Lucene index fetches 0 documents [SharedPool-Worker-3] | 2016-10-14 22:49:26.116000 | 172.17.18.173 |         191156 | 172.17.18.171
                                                                                            Read 0 live and 0 tombstone cells [SharedPool-Worker-3] | 2016-10-14 22:49:26.116000 | 172.17.18.173 |         191504 | 172.17.18.171
                                                                                         Enqueuing response to /172.17.18.171 [SharedPool-Worker-3] | 2016-10-14 22:49:26.116000 | 172.17.18.173 |         191610 | 172.17.18.171
                                                      Sending REQUEST_RESPONSE message to /172.17.18.171 [MessagingService-Outgoing-/172.17.18.171] | 2016-10-14 22:49:26.117000 | 172.17.18.173 |         192357 | 172.17.18.171
     Parsing SELECT * FROM usertable WHERE expr(usertable_index, '{query : {type: "prefix", field: "field0", value: "a" }}'); [SharedPool-Worker-1] | 2016-10-14 22:49:44.115000 | 172.17.18.171 |            476 | 172.17.18.171
                                                                                                          Preparing statement [SharedPool-Worker-1] | 2016-10-14 22:49:44.117000 | 172.17.18.171 |           2843 | 172.17.18.171
                                               Command contains a custom index expression, using target index usertable_index [SharedPool-Worker-1] | 2016-10-14 22:49:44.226000 | 172.17.18.171 |         111039 | 172.17.18.171
                                                                                                    Computing ranges to query [SharedPool-Worker-1] | 2016-10-14 22:49:44.280000 | 172.17.18.171 |         165568 | 172.17.18.171
                      Submitting range requests on 769 ranges with a concurrency of 769 (0.001171875 rows per range expected) [SharedPool-Worker-1] | 2016-10-14 22:49:44.281000 | 172.17.18.171 |         166272 | 172.17.18.171
                                                                                          Enqueuing request to /172.17.18.173 [SharedPool-Worker-1] | 2016-10-14 22:49:44.284000 | 172.17.18.171 |         169851 | 172.17.18.171
                                                                                        Submitted 1 concurrent range requests [SharedPool-Worker-1] | 2016-10-14 22:49:44.286000 | 172.17.18.171 |         171862 | 172.17.18.171
                                                           Sending RANGE_SLICE message to /172.17.18.173 [MessagingService-Outgoing-/172.17.18.173] | 2016-10-14 22:49:44.287000 | 172.17.18.171 |         172090 | 172.17.18.171
                                                   REQUEST_RESPONSE message received from /172.17.18.173 [MessagingService-Incoming-/172.17.18.173] | 2016-10-14 22:49:44.488000 | 172.17.18.171 |         373509 | 172.17.18.171
                                                                                      Processing response from /172.17.18.173 [SharedPool-Worker-2] | 2016-10-14 22:49:44.488000 | 172.17.18.171 |         373773 | 172.17.18.171
                                                                                                                                  Request complete | 2016-10-14 22:49:44.508211 | 172.17.18.171 |         394211 | 172.17.18.171

Report:

    [OVERALL], RunTime(ms), 463630.0
    [OVERALL], Throughput(ops/sec), 1078.446174751418
    [TOTAL_GCS_PS_Scavenge], Count, 69.0
    [TOTAL_GC_TIME_PS_Scavenge], Time(ms), 147.0
    [TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.031706317537691694
    [TOTAL_GCS_PS_MarkSweep], Count, 0.0
    [TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
    [TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
    [TOTAL_GCs], Count, 69.0
    [TOTAL_GC_TIME], Time(ms), 147.0
    [TOTAL_GC_TIME_%], Time(%), 0.031706317537691694
    [READ], Operations, 0.0
    [READ], AverageLatency(us), NaN
    [READ], MinLatency(us), 9.223372036854776E18
    [READ], MaxLatency(us), 0.0
    [READ], 95thPercentileLatency(us), 0.0
    [READ], 99thPercentileLatency(us), 0.0
    [READ], Return=NOT_FOUND, 500000
    [CLEANUP], Operations, 50.0
    [CLEANUP], AverageLatency(us), 45243.78
    [CLEANUP], MinLatency(us), 2.0
    [CLEANUP], MaxLatency(us), 2263039.0
    [CLEANUP], 95thPercentileLatency(us), 9.0
    [CLEANUP], 99thPercentileLatency(us), 2263039.0
    [READ-FAILED], Operations, 500000.0    
    [READ-FAILED], AverageLatency(us), 45784.831272
    [READ-FAILED], MinLatency(us), 6680.0
    [READ-FAILED], MaxLatency(us), 932351.0
    [READ-FAILED], 95thPercentileLatency(us), 109951.0
    [READ-FAILED], 99thPercentileLatency(us), 190847.0

AverageLatency is NAN, READ 95thPercentileLatency and 99thPercentileLatency are 0.0 , Ehn.... this seems ...

**Comment by lynchlee** [comment]
Wow, it seems like my fault. Result set of 'SELECT * FROM usertable WHERE expr(usertable_index, '{query : {type: "prefix", field: "field0", value: "a" }}');' is empty, so Return=NOT_FOUND.

Again:

Results with Lucene indexes using Prefix Query:

CQL：

    SELECT * FROM usertable WHERE expr(usertable_index, '{query : {type: "prefix", field: "field0", value: "=" }}') limit 1;

TRACING:

Report:

  [OVERALL], RunTime(ms), 3043807.0
  [OVERALL], Throughput(ops/sec), 164.2679709981612
  [TOTAL_GCS_PS_Scavenge], Count, 138.0
  [TOTAL_GC_TIME_PS_Scavenge], Time(ms), 245.0
  [TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.008049130578909899
  [TOTAL_GCS_PS_MarkSweep], Count, 0.0
  [TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
  [TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
  [TOTAL_GCs], Count, 138.0
  [TOTAL_GC_TIME], Time(ms), 245.0
  [TOTAL_GC_TIME_%], Time(%), 0.008049130578909899
  [READ], Operations, 500000.0
  [READ], AverageLatency(us), 303509.785456
  [READ], MinLatency(us), 32000.0
  [READ], MaxLatency(us), 3962879.0
  [READ], 95thPercentileLatency(us), 572927.0
  [READ], 99thPercentileLatency(us), 783359.0
  [READ], Return=OK, 500000
  [CLEANUP], Operations, 50.0
  [CLEANUP], AverageLatency(us), 45000.08
  [CLEANUP], MinLatency(us), 1.0
  [CLEANUP], MaxLatency(us), 2250751.0
  [CLEANUP], 95thPercentileLatency(us), 28.0
  [CLEANUP], 99thPercentileLatency(us), 2250751.0

**Comment by adelapena** [comment]
What does it seems? The trace of the Lucene query is showing that there are not any results satisfying the Lucene prefix query, and YCSB output shows that absolutely all the commands have failed. 

Also, YCSB doesn't produce Lucene commands, it only runs primary key queries, unless you have modified it to produce Lucene queries. Have you done so? Or is the presence of the index producing the failure of any unrelated CQL command?

**Comment by lynchlee** [comment]
Yeah, the last test produces Lucene queries , right ？

**Comment by lynchlee** [comment]
YCSB doesn't produce Lucene commands, it only runs primary key queries, unless you have modified it to produce Lucene queries.
------>> I have modified it to to produce Lucene queries before running tests.

**Comment by adelapena** [comment]
If your workload is repeating the aforementioned query:
```sql
SELECT * FROM usertable WHERE expr(usertable_index, '{query : {type: "prefix", field: "field0", value: "=" }}') limit 1;
```
I think it isn't seem a very realistic workload.

Anyway, the results seem reasonable to me given that:
* You are using Cassandra as a key-value store, with the YCSB default table (which doesn't use wide rows) and with a query limit of 1. Cassandra is [more than a key-value store](https://www.mail-archive.com/search?l=user@cassandra.apache.org&q=subject:%22Cassandra+data+model+right+definition%22&o=newest).
* You are using Lucene index to use Cassandra as a pure search engine. That means that the searches are routed to all the cluster token sub-ranges/nodes. This is perfectly valid but, if you don't route your searches to specific partitions, you are going to get the performance results of a search engine, which are notably worst than those of a key-value store. 
* Virtual nodes are [not recommended for analytics/search applications](http://docs.datastax.com/en/datastax_enterprise/4.0/datastax_enterprise/ana/anaNdeOps.html), as [you can read in the documentation](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.9/doc/documentation.rst#disable-virtual-nodes). You have them enabled so, as you can read in the trace, each not-partition-directed query is being routed to 769 token ranges, meaning lots of index lookups per query.

**Comment by lynchlee** [comment]
@adelapena You mean that I only use Cassandra with the lucene index plugin as a pure search engine. So, I should use the "Cassandra with Lucene" with the advantages both of Cassandra and Lucene, Rigth?

**Comment by adelapena** [comment]
I mean that if you use Cassandra as a pure key-value store (without wide rows) combined with Lucene (unable to route searches to specific partitions), which is a perfectly valid use case, you are going to get the benefits and the drawbacks of a search engine: great search expressiveness with worst performance than the provided by a key-value store.

An alternative use of this project, and of Cassandra secondary indexes in general, is to do some denormalization work to have the best of both worlds, for example:
```sql
CREATE TABLE tweets(
  user text,
  date timestamp,
  body text,
  PRIMARY KEY((user),date) -- Partition by user
);
CREATE CUSTOM INDEX tweets_index ON tweets ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds': '1',
   'schema': '{
      fields: {
         body: {type: "text", analyzer: "english"}
      }
   }'
};
SELECT * FROM tweets WHERE expr(tweets_index, '{
   filter: {type: "phrase", field: "body", value: "cassandra version"}
}') AND user='jsmith' AND date >= '2016-01-01';
```
The table is storing tweets grouped by user name. This way, text searches can be routed to the specific partition containing the tweets of a certain user. This query is going to hit a single node (even with virtual nodes enabled), with increased performance.

**Comment by lynchlee** [comment]
@adelapena OKay, I see what you want to tell me . Thanks, Adelapena !!
