### ISSUE TITLE
prefix filter not working right

### ISSUE THREAD

**Issue by jjengla** [Stratio/cassandra-lucene-index#215]
This is a multi-part question I guess.  Here's the issue:
cassandra-lucene-index-3.0.5.0 with cassandra 3.0.5

I've got a table (> 1 million rows) that I found an interesting behavior with: 
A prefix search for foo_bar_X returns results for foo_bar_X1 and foo_bar_X2.
A prefix search for foo_bar only returns the results for foo_bar_X1 (not foo_bar_X2).

Something seems wrong with the index, but I don't know how to debug it.
Is there an easy way to recreate the index to test if had been corrupted?
What would be the best way to upgrade to cassandra-lucene-3.0.5.2 to test it out?

-JE

**Comment by ealonsodb** [comment]
Hi @jjengla:

Would you be kind enough to show us the CREATE TABLE, CREATE INDEX AND prefix search query?

Cheers

**Comment by jjengla** [comment]
So this is a job database of sorts (I've scrubbed many columns for
simplification).

CREATE TABLE jobs (
        job_prefix text,
        job text,
        user text,
        node text,
        start_time timestamp,
        end_time timestamp,
        output_url text,
        run_state text,
        exit_status int,
        PRIMARY KEY (job_prefix, job)
);
CREATE CUSTOM INDEX jobs_index ON jobs ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'directory_path' : '/var/lib/cassandra/index/jobs',
    'schema' : '{
        fields : {
            job_prefix : {type : "string"},
            job : {type : "string"},
            user : {type : "string"},
            node : {type : "string"},
            start_time : {type : "date", pattern : "yyyyMMdd-HH:mm:ss"},
            end_time : {type : "date", pattern : "yyyyMMdd-HH:mm:ss"},
            output_url : {type : "string"},
            run_state : {type : "string"},
            exit_status : {type : "integer"},
        }
    }'
};

Here is the query that works:

SELECT job,user,node,start_time,end_time,output_url,run_state,exit_status
FROM jobs WHERE expr(jobs_index, '{filter : {type : "boolean", must :
[{"field": "job_prefix", "type": "match", "value": "foo"},{"field": "job",
"type": "prefix", "value": "foo_bar_biz"}]}}')

and the one that returns incomplete results:

SELECT job,user,node,start_time,end_time,output_url,run_state,exit_status
FROM jobs WHERE expr(jobs_index, '{filter : {type : "boolean", must :
[{"field": "job_prefix", "type": "match", "value": "foo"},{"field": "job",
"type": "prefix", "value": "foo_bar"}]}}')


Job names are often of the format 'foo_bar_biz_X' and 'foo_bar_biz_Y',
where 'foo' is the job_prefix.  The faulty query returns results for all
the _X jobs, but not the _Y jobs.

-JE

**Comment by ealonsodb** [comment]
Hi @jjengla: 

1.- In order to try to reproduce the issue i need some data. Could you show us this query results:
```
    SELECT * FROM jobs WHERE job_prefix='foo';
```
2.- Deleting and creating again the index will rebuild it. This is used in [upgrade](https://github.com/Stratio/cassandra-lucene-index/blob/3.0.5.2/doc/documentation.rst#upgrade) too.

3.- If your repair the cluster (via nodetool repair), your data will be consistent. 

Apart from your questions:

As you are using 'job_prefix' as partition key in the table, you can change your query: 
```
    SELECT job,user,node,start_time,end_time,output_url,run_state,exit_status
    FROM jobs 
    WHERE expr(jobs_index, '{filter : 
                                                    {type : "boolean", must :
[{"field": "job_prefix", "type": "match", "value": "foo"},{"field": "job",
"type": "prefix", "value": "foo_bar"}]}}');
```
to:
```
SELECT job,user,node,start_time,end_time,output_url,run_state,exit_status
FROM jobs WHERE expr(jobs_index, '{filter : {"field": "job",
"type": "prefix", "value": "foo_bar"}}') AND job_prefix='foo';
```

These queries produces the same results but second ask only to affected nodes(nodes with job_prefix=='foo') instead of asking to every node in the cluster consuming less resources. 

Looking forward your inserts.

**Comment by jjengla** [comment]
Thank you for the updated query.  That was my intent with the first query
but didn't know if it was right.  I'll try recreating the index to see if
that helps.  I do repair nodes regularly and they have all been up for a
while so I think data consistency is ok.  I'll get you some scrubbed
sample output from your query later today.

-JE

**Comment by jjengla** [comment]
Re-creating the index does not seem to help.  I'll build a test instance
with latest software and import the data into that to try it out.

Attached is some sample data that will hopefully help reproduce the
problem.  Be aware that this is only about 55k rows out of 1M+ in the
database (in case that matters).  In this data, you should see that using a
longer substring prefix of the job name will return results for both _foo
and _bar jobs, but using a shorter substring prefix will only return 1 of
the records.

Let me know if I can provide any more data to help debug.

-JE

**Comment by ealonsodb** [comment]
Hi @jjengla: 

I cannot see any attached data. Could you please be so kind to send it to me?

eduardoalonso[at]stratio.com

**Comment by ealonsodb** [comment]
Hi @jjengla: 

I have been testing this issue against data you sent me and ia cannot reproduce this issue. 
Another way to ask for a prefix is use wildcard query, 

Can you run this query against your cluster and tell us if these two queries produces same results?
```
    SELECT job,user,node,start_time,end_time,output_url,run_state,exit_status 
    FROM jobs 
    WHERE job_prefix='foo'
    AND expr(jobs_index, 
        '{filter : {"field": "job", "type": "prefix", "value": "foo_bar"}}');
```

```
    SELECT job,user,node,start_time,end_time,output_url,run_state,exit_status 
    FROM jobs 
    WHERE job_prefix='foo'
    AND expr(jobs_index, 
        '{filter : {"field": "job", "type": "wildcard", "value": "foo_bar*"}}');
```

**Comment by jjengla** [comment]
That's a bummer.  That data is somewhat scrubbed from the original so I
haven't verified if the problem happens with that exact data either.  I've
got a test instance built and will try to reproduce the problem and/or see
if an upgrade fixes it and let you know.

I have tried wildcard, regex, etc and they all returned just 1 record
instead of two.  Are there any settings on the Cassandra side that would
have an effect on the index?

-JE

**Comment by adelapena** [comment]
Can you rebuild the index over the problematic data?

**Comment by jjengla** [comment]
Rebuilding the index seems to fix the problem temporarily.  Then it degrades again to returning incomplete results.  I'm experimenting now to see if I can find what causes the index to degrade.

-JE

**Comment by jjengla** [comment]
BTW, I upgraded to 3.0.5.2 and it behaves the same way.

-JE

**Comment by jjengla** [comment]
I upgraded to 3.0.5.2 and recreated the index and it seems to have made the
problem go away.  I'll do some more testing and then call it good.

-JE


On Fri, Oct 21, 2016 at 2:31 AM, Andrés de la Peña <notifications@github.com
