### ISSUE TITLE
broken links 

### ISSUE THREAD

**Issue by ealonsodb** [Stratio/cassandra-lucene-index#22]
In documentation here:
https://github.com/Stratio/cassandra-lucene-index/blob/branch-2.1.8/doc/src/site/sphinx/documentation.rst#example-1

the test-users-create.cql link is broken

**Comment by adelapena** [comment]
Fixed at [master branch](https://github.com/Stratio/cassandra-lucene-index/blob/a47b0d2c40a3f6840f0dadefcf9ec08bad1b0f77/doc/src/site/sphinx/documentation.rst#example-1).
