### ISSUE TITLE
Checking progress of index creation

### ISSUE THREAD

**Issue by PseudoSean** [Stratio/cassandra-lucene-index#220]
I'm indexing a rather large and complicated GIS dataset which has been running for over 2 weeks - is there any way to check the progress of an index?

**Comment by adelapena** [comment]
Hi @PseudoSean,

You can use the [JMX API](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.9/doc/documentation.rst#jmx-interface) to check the number of indexed rows in each node. The total number of indexed rows is the sum of the number of indexed rows per node divided by the replication factor.

Anyway, 2 weeks seems to be a lot of time. If you are indexing complex polygons you may consider reducing the number of geohash levels, as explained [here](http://www.slideshare.net/DataStax/stratios-cassandra-lucene-index-geospatial-use-cases-andrs-de-la-pea-jonathan-nappee-nephila-c-summit-2016). It can have a dramatical impact in indexing speed.

You can also [increase the number of indexing threads](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.9/doc/documentation.rst#indexing) if the nodes doesn't seem very loaded during the indexing process.

I hope that helps.

**Comment by ealonsodb** [comment]
Hi @PseudoSean: 

If you insert all data and after that you create the index, there is a system table called "IndexInfo" you can consult for completely built indexes.
```
SELECT * FROM system."IndexInfo";
```

**Comment by PseudoSean** [comment]
I increased the indexing thread count by a factor of 4 and I reduced the geohash levels significantly and the index was created in a matter of hours! The geohash level was the key to solving this; I really appreciate your help on this - I had not seen that slideshow you linked, so this was incredibly helpful.

**Comment by adelapena** [comment]
You can also check index creation status with ``nodetool compactionstats``.
