### ISSUE TITLE
What is the difference between query and filter when searching?

### ISSUE THREAD

**Issue by didip** [Stratio/cassandra-lucene-index#224]
Hi, first of all, great project. This indexer really solves the problem of needing a more flexible secondary indexing.

What is the difference between `query` and `filter` when running `SELECT`? Syntax-wise, they are interchangeable.

**Comment by didip** [comment]
Oh there's an entire section on performance: https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.9/doc/documentation.rst#performance-tips

Thanks! Also, great job on the docs, I am able to understand the analyzers, mappers, and searches very quickly.

**Comment by adelapena** [comment]
You are very welcome.
