### ISSUE TITLE
Spark Cassandra Table returns wrong partitions size while working with Cassandra Lucene Index 

### ISSUE THREAD

**Issue by tmatyashovsky** [Stratio/cassandra-lucene-index#228]
Hi,

Maybe it is not an issue of an index, but of a Spark Cassandra connector, so please let me know and I will ask this question in their mailing list too. 

We are using lucene index on metrics table (_com.localhost.cpu, com.localhost.memory, etc._) in order to filter metrics by name. 

`CREATE CUSTOM INDEX IF NOT EXISTS metric_index ON ks.metric (lucene)
            USING 'com.stratio.cassandra.lucene.Index'
            WITH OPTIONS = {
                'refresh_seconds' : '1',
                'schema' : '{
                    fields : {
                        metric    : {type : "string"}
                    }
                }'
            };`

Where the metric table is created simply as:

`CREATE TABLE IF NOT EXISTS ks.metric (metric text PRIMARY KEY ,dt int,lucene text);`

Search is working great from **correctness** perspective.

But when we try to use index via `cassandraTable` (from https://github.com/datastax/spark-cassandra-connector) having only 1 record:

```
val where = " lucene = '{filter : {type:\"boolean\", must:[{type: \"wildcard\", field:\"metric\", value : \"localtest.host1.test1\" }]}}'"
 val metricTable = spark.sparkContext.cassandraTable(keyspace, "metric").where(where)
```

It returns one row as **expected**, but **more partitions size**: 
`metricTable.partitions.size == 9`

If we change this logic to do a simple select without usage of an index, then it returns 1 partition, so `metricTable.partitions.size==1`. 

Can you please advise what can be wrong?

Cassandra connector version is: spark-cassandra-connector_2.11:2.0.0-M3 (we will test with latest version too)
Spark version is: 2.0.0
Lucene index version is: 2.2.5.3

Thank you,
Taras

**Comment by adelapena** [comment]
This is [answered at C* Spark connector list](https://groups.google.com/a/lists.datastax.com/forum/#!topic/spark-connector-user/S_YgEXdV3bo).
