### ISSUE TITLE
Custom index and consistency clarification

### ISSUE THREAD

**Issue by mbriot** [Stratio/cassandra-lucene-index#23]
Hello,

I simulated the situation of a down node for a "long time" and returning alive.

So I've set a 3 nodes cluster with RF3 replication, hinted_hand_off deactivated
I insert a row such as : 

    { id : 1 , user : manu, tweet : hello world } 

with an appropriate custom index

I put my node 3 offline and update the content of "tweet"

    Update documents set tweet="hello paris" where id=1

I bring my node 3 online and perform this request : 

    SELECT * FROM documents WHERE lucene='{query : {type:"phrase", field:"tweet", value:"hello world", slop:1}}';

returning me 0 or 1 row depending on the responding nodes.

Is there a solution to prevent a comportment like that or it's totaly normal ?

**Comment by adelapena** [comment]
No, it's not the expected behavior. I can't reproduce it with master branch. Which version are you using? Which is the consistency level both for writes and reads? How is your custom index schema?

I'm trying to reproduce the issue this way:
```
CREATE KEYSPACE test
         WITH REPLICATION = {'class' : 'SimpleStrategy',  'replication_factor': 3};
USE test;

CREATE TABLE documents (
  id int, 
  user text, 
  tweet text, 
  lucene text, 
  PRIMARY KEY (id));

CREATE CUSTOM INDEX documents_idx ON documents (lucene) 
USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
 'refresh_seconds':'1', 
 'schema':'
 {fields:{
 	id:{type:"integer"}, 
 	user:{type:"string"},
 	tweet:{type:"string"}
 	}
 }'};

CONSISTENCY QUORUM;
INSERT INTO documents (id,  user, tweet) VALUES ( 1,  'manu',  'hello world');

SELECT * FROM documents WHERE lucene='{query : {type:"phrase", field:"tweet", value:"hello world", slop:1}}';

-- Put node 3 offline
CONSISTENCY QUORUM;
UPDATE documents SET tweet='hello paris' WHERE id=1;

-- Put node 3 online and query to all three nodes
CONSISTENCY QUORUM;
SELECT * FROM documents WHERE lucene='{query : {type:"phrase", field:"tweet", value:"hello world", slop:1}}';
SELECT * FROM documents WHERE lucene='{query : {type:"phrase", field:"tweet", value:"hello paris", slop:1}}';
```

**Comment by mbriot** [comment]
I am using the version 2.1.8 with QUORUM for both write and read.
The goal is to simulate a node down for a long time and needing a nodetool repair to resynchronize.
That's why we deactivate the hinted_hand_off and the read_repair_chance mechanism.

    hinted_hand_off: false in cassandra.yaml
    ALTER TABLE documents WITH read_repair_chance = 0.0;
	
Maybe you missed that ?

My schema is quite similar except for the tweet column : 

    CREATE CUSTOM INDEX documents_idx ON documents (lucene) 
    USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
     'refresh_seconds':'1', 
     'schema':'
     {fields:{
        id:{type:"integer"}, 
        user:{type:"string"},
        tweet:{type : "text", analyzer : "french", sorted: "false"}
        }
    }'};

Just after bringing node 3 onlines if I put node 1 offline and process the following request :

    CONSISTENCY QUORUM;
	SELECT * FROM documents WHERE lucene='{query : {type:"phrase", field:"tweet", value:"hello world", slop:1}}';
	
I'm retrieving my obsolete value "hello world" each time.

**Comment by adelapena** [comment]
Yes, you are right, I missed that. I think that it's presenting the same behavior as regular Apache Cassandra. You can reproduce the same issue with a standard index:
```
CREATE KEYSPACE test
         WITH REPLICATION = {'class' : 'SimpleStrategy',  'replication_factor': 3};
USE test;
CONSISTENCY QUORUM;

CREATE TABLE documents (
  id int, 
  user text, 
  tweet text, 
  lucene text, 
  PRIMARY KEY (id));
ALTER TABLE documents WITH read_repair_chance = 0.0;

-- Create a non-custom index
CREATE INDEX documents_idx ON documents (tweet);

INSERT INTO documents (id,  user, tweet) VALUES ( 1,  'manu',  'hello world');
SELECT * FROM documents WHERE tweet='hello world';

-- Put node 3 offline
UPDATE documents SET tweet='hello paris' WHERE id=1;

-- Put node 3 online, put node 1 offline, and query to all three nodes
SELECT * FROM documents WHERE tweet='hello world';
-- The obsolete value "hello world" is retrieved again
```
So, if I'm not wrong, I think that this issue is related to [Apache Cassandra](https://issues.apache.org/jira/browse/cassandra) project, don't you think so?

**Comment by mbriot** [comment]
I agree, casssandra secondary index are not consistent and it's something to keep in mind if big decision are made based on a return query...

Thanks for your help
