### ISSUE TITLE
Questiong Is there any plan to support map <text> [ set<text> ] within lucene

### ISSUE THREAD

**Issue by nlacey** [Stratio/cassandra-lucene-index#235]
Using Cassandra 2.2.3  I'm unable to create lucene index on a map<text> [ set<text> ]

I'm wondering if I'll be able to do so in one of the other / future releases?

Thanks for making an awesome product!

**Comment by ealonsodb** [comment]
Hi @nlacey:

Do you mean you want to index a map\<text,set\<text\>\> or map\<text\> and set\<text\>?

Collections are supported in cassandra-lucene-index version [2.2.3.0](https://github.com/Stratio/cassandra-lucene-index/blob/2.2.3.0/doc/src/site/sphinx/documentation.rst#collections)

We apply bug fixing patches to last cassandra version in 2.2.x branch but not for 2.2.3. Maybe you should try with [2.2.8.0](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.8.0) but remember cassandra 2.2.x [is only supported until November 2016](http://cassandra.apache.org/download/) 

What problems are you facing? 
Cheers

**Comment by nlacey** [comment]
Sorry for not being clear.
I'm currently indexing lots of maps well map<text,int> ,  map<text,text> (with different cassandra analyzers)
But I couldn't do map<text,set<text>>
We are testing 2.2.8.0.
Thanks for the support warning!

**Comment by ealonsodb** [comment]
Hi @nlacey:

I have tested this against a one node cassandra cluster version 2.2.8 with cassandra-lucene-index [2.2.8.0](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.8.0) and it works ok. 


```
CREATE KEYSPACE IF NOT EXISTS test 
WITH REPLICATION = {
       'class' : 'SimpleStrategy', 
       'replication_factor': 1
};

CREATE TABLE test.demo (
  id bigint,
  text_map map<text,frozen<set<text>>>,
  lucene text,
  PRIMARY KEY(id)
);

CREATE CUSTOM INDEX demo_index ON test.demo (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds': '10',
   'schema': '{
      fields: {
         text_map: {type: "string"}
      }
   }'
};

INSERT INTO test.demo(id,text_map) VALUES (1, { 'a'  : {'1','2'}, 'b' : {'3','4'}, 'c': {'5','6'}});
INSERT INTO test.demo(id,text_map) VALUES (2, { 'a'  : {'a','A'}, 'b' : {'b','B'}, 'c': {'c','C'}});

--returns 0 rows 
SELECT * from test.demo WHERE lucene='{filter:{type:"match", field:"text_map$a", value:"b" }}';

--return 1 row [id=2]
SELECT * from test.demo WHERE lucene='{filter:{type:"match", field:"text_map$a", value:"a" }}';

--return 1 row [id=2]
SELECT * from test.demo WHERE lucene='{filter:{type:"match", field:"text_map$a", value:"A" }}';

--return 1 row [id=1]
SELECT * from test.demo WHERE lucene='{filter:{type:"match", field:"text_map$a", value:"1" }}';

--return 1 row [id=1]
SELECT * from test.demo WHERE lucene='{filter:{type:"match", field:"text_map$a", value:"2" }}';

--returns 0 rows 
SELECT * from test.demo WHERE lucene='{filter:{type:"match", field:"text_map$a", value:"3" }}';

--returns 0 rows 
SELECT * from test.demo WHERE lucene='{filter:{type:"match", field:"text_map$a", value:"4" }}';

```


What do you mean when you say you cannot do 'map<text,set<text>>'?  What fails? How? 
Could you be kind enough to show us a basic failing CQL example?
