### ISSUE TITLE
Long delays when explicitly refreshing indexes

### ISSUE THREAD

**Issue by karlbunnell** [Stratio/cassandra-lucene-index#240]
We are using Cassandra 3.8 with the 3.8 version of the plugin.

Our use case requires us to create a new table, populate it with data, then explicitly force an refresh of the index on the table (with consistency all) so the new table can be queried using Lucene index. This can happen every 3-5 seconds or so. What we observe is that the first 3-5 iterations of inserting rows (again, each iteration happening in 2-3 seconds) happen quickly but then one of the explicit refreshes will pause up to 3 minutes or more before continuing, then process 4-5 more iterations before pausing a long time again. 
Any idea what is causing these long pauses? Any suggestions on how to  reduce the length of the pauses? These are happening even when the data inserted if small ( 10 - 20 new rows of data). 
Thanks!

**Comment by karlbunnell** [comment]
I should mention that the delay only happens if the lucene indexed tables are being queried. If only the refresh takes place then no delay is observed, however, the delay definitely happens when invoking a refresh against an indexed table.

**Comment by adelapena** [comment]
Hi @karlbunnell,

Are you using asynchronous indexing? If so, which are the values of ``indexing_threads`` and ``indexing_queues_size``? Which is the value of ``max_cached_mb``? The refresh operation blocks writers and waits for the completion of the indexing queues. This may take some time, but 3 minutes is definitely too much.

We are trying to reproduce the scenario doing refresh operations while the index is under heavy write load. The refreshes take some time, but they are far away from the aforementioned 3 minutes. Any help to reproduce the issue will be very useful.

By the way, there is no 3.8 version of the plugin, the releases for Apache Cassandra x.y are labeled with the format x.y.z.

**Comment by karlbunnell** [comment]
Hello, 
I'm just using the  defaults so I'm not using async indexing. I'm also going with the defaults for the other values you mention (indexing_threads, indexing_queues_size and max_cached_mb). 
Recommendations for these settings would be much appreciated.

The artifact we build from source is cassandra-lucene-index-plugin-3.8.1-RC1-SNAPSHOT.jar - we are building from branch-3.8 and running on Cassandra 3.8

BTW, 3 minutes was the longest delay we experienced. A more typical delay is 90-120 seconds.

**Comment by adelapena** [comment]
Hi,

It is a good idea to use tested [releases](https://github.com/Stratio/cassandra-lucene-index/releases) such as [3.8.1](https://github.com/Stratio/cassandra-lucene-index/releases/tag/3.8.1) instead of snapshots, although I don't think it is is the cause of this particular problem.

As you can read in [documentation](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.8/doc/documentation.rst#indexing), ``indexing_threads`` is set by default to the number of processors available to the JVM, so you are using this kind of indexing. The default value for ``indexing_queues_size`` is a very conservative 50, so I think it isn't the cause of the problem either, unless you are indexing very large documents.

About issue reproduction, we are running this toy program to insert rows:
```scala
import java.util.Random

import com.datastax.driver.core.Cluster
import com.datastax.driver.core.querybuilder.QueryBuilder
import com.datastax.driver.core.querybuilder.QueryBuilder._

object LoaderWide extends App {

  val START_PARTITION = 1
  val NUM_PARTITIONS = 10000
  val PARTITION_SIZE = 10000

  val cluster = Cluster.builder.addContactPoint("localhost").build
  val session = cluster.connect

  session.execute(
    """CREATE KEYSPACE IF NOT EXISTS test
      | WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};
      | """.stripMargin)
  session.execute("USE test")
  session.execute(
    """CREATE TABLE IF NOT EXISTS wide(
      | pk int,
      | ck int,
      | rc1 bigint,
      | rc2 bigint,
      | rc3 bigint,
      | lucene text,
      | PRIMARY KEY (pk, ck));""".stripMargin)
  session.execute(
    """CREATE CUSTOM INDEX IF NOT EXISTS wide_idx ON wide(lucene)
      | USING 'com.stratio.cassandra.lucene.Index'
      | WITH OPTIONS = {
      |    'refresh_seconds' : '60',
      |    'schema' : '{
      |       fields : {
      |          pk  : {type: "integer"},
      |          ck  : {type: "integer"},
      |          rc1 : {type: "long"},
      |          rc2 : {type: "long"},
      |          rc3 : {type: "long"}
      |       }
      |    }'
      |};""".stripMargin)

  val random = new Random

  var totalWrites = (START_PARTITION - 1) * PARTITION_SIZE
  var iterationWrites = 0
  var totalStart = System.currentTimeMillis()
  var iterationStart = System.currentTimeMillis()

  for (i <- START_PARTITION to NUM_PARTITIONS) {
    for (j <- 1 to PARTITION_SIZE) {

      totalWrites += 1
      iterationWrites += 1

      if (totalWrites % 1000 == 0) {

        // Print output about write speed
        val time = System.currentTimeMillis - iterationStart
        val rate = (iterationWrites.doubleValue / time.doubleValue) * 1000
        println(s"Written $totalWrites rows at $rate r/s")
        iterationWrites = 0
        iterationStart = System.currentTimeMillis()

        // Refresh the index
        val refreshStart = System.currentTimeMillis
        session.execute(select().from("wide").where(QueryBuilder.eq("lucene", "{refresh:true}")))
        val refreshTime = System.currentTimeMillis - refreshStart
        println(s"Refreshed in $refreshTime ms")
      }

      // Write one single row
      session.execute(QueryBuilder.insertInto("wide")
        .value("pk", i)
        .value("ck", j)
        .value("rc1", random.nextInt(100))
        .value("rc2", random.nextInt(1000))
        .value("rc3", random.nextInt(10000)))
    }
  }

  // Print final writing stats
  val time = System.currentTimeMillis - totalStart
  val rate = (totalWrites.doubleValue / time.doubleValue) * 1000
  println(s"TOTAL: Written $totalWrites rows at $rate r/s in $time ms")

  session.close()
  cluster.close()
  System.exit(0)
}
```
It runs a refresh each 1000 rows, and this is the output by now:
```
Written 1000 rows at 321.9575016097875 r/s
Refreshed in 630 ms
Written 2000 rows at 419.1114836546521 r/s
Refreshed in 128 ms
Written 3000 rows at 563.063063063063 r/s
Refreshed in 135 ms
Written 4000 rows at 695.8942240779401 r/s
Refreshed in 134 ms
...
Refreshed in 83 ms
Written 2248000 rows at 1858.736059479554 r/s
Refreshed in 68 ms
Written 2249000 rows at 2197.802197802198 r/s
Refreshed in 72 ms
...
Written 3740000 rows at 2127.659574468085 r/s
Refreshed in 68 ms
Written 3741000 rows at 2028.3975659229209 r/s
Refreshed in 73 ms
Written 3742000 rows at 2049.180327868852 r/s
Refreshed in 72 ms
Written 3743000 rows at 1689.1891891891892 r/s
Refreshed in 78 ms
...
Written 5065000 rows at 2222.222222222222 r/s
Refreshed in 70 ms
Written 5066000 rows at 2118.64406779661 r/s
Refreshed in 76 ms
Written 5067000 rows at 1872.6591760299625 r/s
Refreshed in 65 ms
```
As you can see, the write speed is quite low because we are not using any parallelism or pipelining, so the row generator is the bottleneck here. However, you can see that the refresh times are acceptable and stable. 

Please let us know if the program properly reproduces your use case, and feel free to do any modifications and/or test it in your environment.

**Comment by adelapena** [comment]
There are the final results:
```
Written 99989000 rows at 2570.694087403599 r/s
Refreshed in 62 ms
Written 99990000 rows at 2624.6719160104985 r/s
Refreshed in 61 ms
Written 99991000 rows at 2398.0815347721823 r/s
Refreshed in 70 ms
Written 99992000 rows at 2457.002457002457 r/s
Refreshed in 64 ms
Written 99993000 rows at 2570.694087403599 r/s
Refreshed in 66 ms
Written 99994000 rows at 2531.6455696202534 r/s
Refreshed in 78 ms
Written 99995000 rows at 2320.185614849188 r/s
Refreshed in 61 ms
Written 99996000 rows at 2570.694087403599 r/s
Refreshed in 65 ms
Written 99997000 rows at 2538.0710659898477 r/s
Refreshed in 71 ms
Written 99998000 rows at 2493.7655860349128 r/s
Refreshed in 62 ms
Written 99999000 rows at 2570.694087403599 r/s
Refreshed in 70 ms
Written 100000000 rows at 2336.448598130841 r/s
Refreshed in 65 ms
TOTAL: Written 100000000 rows at 2290.536821203994 r/s in 43657888 ms
```
The longer observed refresh operation time is a peak of 593ms.
