### ISSUE TITLE
Question: Multiple Filters with Builder in Java lib

### ISSUE THREAD

**Issue by zyxer** [Stratio/cassandra-lucene-index#244]
Hello, my question is pretty simple, or I should say 'silly':
How can be build a request query that will contain multiple filters with library 'cassandra-lucene-index-builder'?

I'm using Cassandra 3.7 and appropriate plugin, and I have explored your library, and realized, that 
```
Search search = search();
search.filter(phrase("student", "student42")
search.build()
```
will produce String
```
{"filter":{"type":"phrase","field":"student","value":"student42"}}
```

and

```
Search search = search();
search.filter(phrase("student", "student42")
search.filter(phrase("question", "What was the question?")
search.build()
```
will produce String
```
{"filter":{"type":"phrase","field":"question","value":"What was the question?"}}
```
but not String with two filters, and its OK accordint to implementation of Search.

But as I understand from main page of project, queries with multiple filters are allowed! 
So, I should use other mechanism for building queries. And it's no problem to create custom Class based on List of filters-conditions and then decode it to String, but.. I think, I'm not the one with this necessity, so maybe something has been done in this direction, and I didn't notice it.

Thanks!

**Comment by ealonsodb** [comment]
Hi @zyxer: 

There are some examples in [boolean search](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.7/doc/documentation.rst#boolean-search). 

I have tested with cassandra-lucene-index-bilder verison [3.7.3](https://github.com/Stratio/cassandra-lucene-index/tree/3.7.3)


As you can see in [boolean search](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.7/doc/documentation.rst#boolean-search) examples in Doc: 

```
@Test
    public void testAlone() throws IOException {
        Search search = new Search();
        search.filter(phrase("student", "student42"));
        search.filter(phrase("question", "What was the question?"));
        System.out.println(search.build());
    }
```
that produces:
```
{"filter":[{"type":"phrase","field":"student","value":"student42"},{"type":"phrase","field":"question","value":"What was the question?"}]}
```

And :
```
@Test
    public void testTogether() throws IOException {
        Search search = new Search();
        search.filter(phrase("student", "student42"),phrase("question", "What was the question?"));
        System.out.println(search.build());
    }
```

that produces: 
```
{"filter":[{"type":"phrase","field":"student","value":"student42"},{"type":"phrase","field":"question","value":"What was the question?"}]}
```


Which version are you using?

**Comment by adelapena** [comment]
Hi @zyxer ,

If you are using 3.7.0 or 3.7.1, you can build the query adding the phrase queries as clauses of a boolean filter, this way:
```java
Search search = search();
search.filter(bool().must(
   phrase("student", "student42"), 
   phrase("question", "What was the question?")));
search.build();
```
You can find more examples in the [documentation for the specific version](https://github.com/Stratio/cassandra-lucene-index/blob/3.7.1/doc/documentation.rst#boolean-search) of the builder that you are using.
This syntax is also supported in all later releases. 
Versions from 3.7.2 and beyond also support the two alternative approaches mentioned by @ealonsodb, which are syntactic sugar for the classic boolean filter approach.

**Comment by zyxer** [comment]
Thanks for quick response, this is what I was looking for!

I'm using 3.7.0 version of library, but there's no problem of using 3.7.3. Boolean filter method isn't obvious for me, because I have just started digging in Cassandra Lucene Index (but I'm really infatuated with it).

Thanks again, have a nice day.

**Comment by adelapena** [comment]
We are glad it was helpful. 

Just remember that the grammar should be supported server side so, if you upgrade to any newer version of the builder, you should have the same version of the plugin in Cassandra. 

One additional warning: [3.7.3](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.9/CHANGELOG.md#373-october-07-2016) broke index format backward compatibility to provide much more efficient queries, so if you upgrade you should previously drop the indexes, stop Cassandra, replace the plugin JAR file, start Cassandra and create the indexes again, as described in [upgrade documentation](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.7/doc/documentation.rst#upgrade).

We will publish a 3.7.4 very soon, backwards compatible with 3.7.3.

**Comment by zyxer** [comment]
Thanks for such important reminder!
