### ISSUE TITLE
Map<text,text> is returned as OrderedMapSerializedKey([(u'foo', u'bar')]), is this expected?

### ISSUE THREAD

**Issue by didip** [Stratio/cassandra-lucene-index#245]
When performing `SELECT` with Lucene index, any Map<text, text> fields are returned as `OrderedMapSerializedKey([(u'foo', u'bar')])` instead of native map format.

Shouldn't it returned in native format? I tested this on `cqlsh` and Cassandra 3.7.

**Comment by ealonsodb** [comment]
Hi @didip:

I think it is [CASSANDRA-11534](https://issues.apache.org/jira/browse/CASSANDRA-11534)

**Comment by didip** [comment]
Ah, yeah, i think it is that issue.
