### ISSUE TITLE
Unable to range over Map values?

### ISSUE THREAD

**Issue by didip** [Stratio/cassandra-lucene-index#246]
I have a simple table:
```
CREATE TABLE IF NOT EXISTS foo (
    id text,
    updated bigint,
    data map<text, text>,
    lucene text,
    PRIMARY KEY (id)
);
```

And this is my index:
```
CREATE CUSTOM INDEX IF NOT EXISTS idx_foo ON foo (lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
    'schema' : '{
        fields : {
            id : {type : "string"},
            updated: {type : "integer"},
            data_string : { type : "string", column: "data"},
            data_float : { type : "float", column: "data"}
        }
    }'
};
```
**Notice** that the `data` field uses 2 different mappers based on what I read here: https://github.com/Stratio/cassandra-lucene-index/issues/179
(I need multiple mappers because the JSON blob I received is arbitrary by nature and out of my control).

That said, I am trying to perform range on the data. Example:
```
SELECT id, updated, data FROM foo WHERE expr(idx_foo, '{
    filter: {
        type: "boolean",
        must: [
            {type: "match", field: "id", value: "awesome"},
            {type: "range", field:"updated", lower:1480166330, include_lower: true},
            {type: "range", field: "data_float$/you.are.awesome", lower: 10}
        ]
    }
}');
```
The map key that I am interested in, is indeed: `/you.are.awesome`.

Above query never returns anything even though the data exists. If I took out the `data_float range`, I get results.

Am I doing something wrong?

**Comment by ealonsodb** [comment]
Hi @didip:

I think you are having problems with [lucene queryparser spacial characters](https://lucene.apache.org/core/5_3_1/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Escaping_Special_Characters).

'/' is an special character in lucene syntax and you need to espace it. 

Please, try with this query and tell us if it works
```
SELECT id, updated, data FROM foo WHERE expr(idx_foo, '{
    filter: {
        type: "boolean",
        must: [
            {type: "match", field: "id", value: "awesome"},
            {type: "range", field:"updated", lower:1480166330, include_lower: true},
            {type: "range", field: "data_float$\/you.are.awesome", lower: 10}
        ]
    }
}');
```
We definitely need to include a section in documentation.

**Comment by didip** [comment]
Just tried it, unfortunately, it didn't work. I still get no results. :(

**Comment by ealonsodb** [comment]
which version of cassandra and cassandra-lucene-index are you using?

**Comment by didip** [comment]
Cassandra: 3.7
Lucene Index: cassandra-lucene-index-plugin-3.7.3-RC1-SNAPSHOT.jar

**Comment by ealonsodb** [comment]
Hi @didip: 

I have modified a bit your sentences and this works correctly.

```
CREATE KEYSPACE test with replication = {
    'class' : 'SimpleStrategy', 
    'replication_factor' : '1' 
}; 
USE test;
CREATE TABLE IF NOT EXISTS foo (
    id text,
    updated bigint,
    data map<text, text>,
    lucene text,
    PRIMARY KEY (id)
);
CREATE CUSTOM INDEX IF NOT EXISTS idx_foo ON foo (lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
    'schema' : '{
        fields : {
            id : {type : "string"},
            updated: {type : "integer"},
            data_string : { type : "string", column: "data"},
            data_float : { type : "float", column: "data"}
        }
    }'
};

INSERT INTO test.foo(id, updated, data) VALUES('1',1,{'/you.are.awesome':'1'});
INSERT INTO test.foo(id, updated, data) VALUES('2',1,{'/you.are.awesome':'20'});
INSERT INTO test.foo(id, updated, data) VALUES('3',1,{'/you.are.awesome':'22'});
INSERT INTO test.foo(id, updated, data) VALUES('4',1,{'/you.are.awesome':'12'});
INSERT INTO test.foo(id, updated, data) VALUES('5',1,{'/you.are.awesome':'7'});
INSERT INTO test.foo(id, updated, data) VALUES('6',1,{'/you.are.awesome':'68'});
INSERT INTO test.foo(id, updated, data) VALUES('7',1,{'/you.are.awesome':'54'});
INSERT INTO test.foo(id, updated, data) VALUES('8',1,{'/you.are.awesome':'32'});
INSERT INTO test.foo(id, updated, data) VALUES('9',1,{'/you.are.awesome':'35'});
INSERT INTO test.foo(id, updated, data) VALUES('10',1,{'/you.are.awesome':'38'});

SELECT id, updated, data FROM foo WHERE expr(idx_foo, '{
    filter: {type: "range", field: "data_float$\/you.are.awesome", lower: 10}
,refresh : true}');
```

I have seen you are using index to index partition key (id) and query through lucene. 
I think you should know this:

```
SELECT id, updated, data FROM foo WHERE expr(idx_foo, '{
    filter: {
        type: "boolean",
        must: [
            {type: "match", field: "id", value: "awesome"},
            {type: "range", field:"updated", lower:1480166330, include_lower: true},
            {type: "range", field: "data_float$/you.are.awesome", lower: 10}
        ]
    }
}');
```
would be better so:
```
SELECT id, updated, data FROM foo WHERE id='awesome' AND expr(idx_foo, '{
    filter: {
        type: "boolean",
        must: [
            {type: "range", field:"updated", lower:1480166330, include_lower: true},
            {type: "range", field: "data_float$/you.are.awesome", lower: 10}
        ]
    }
}');
```

With the first query all nodes in cluster will search for the data, with the second cassandra will only redirect the query to affected nodes.

**Comment by didip** [comment]
Hm... I am still not getting any results :(

But, interestingly, `data_string` matcher works without `/` escaping. This works:
```
SELECT id, updated, data FROM foo WHERE expr(idx_foo, '{filter: {type: "match", field: "data_string$/you.are.awesome", value: "2.198"}, refresh : true }');
```
and this doesn't work:
```
SELECT id, updated, data FROM foo WHERE expr(idx_foo, '{filter: {type: "match", field: "data_float$\/you.are.awesome", value: 2.198}, refresh : true }');
```

**Comment by didip** [comment]
Out of curiosity, I upgraded Cassandra to 3.9 and use the `branch-3.9` JAR. The problem still persists :(

**Comment by ealonsodb** [comment]
Hi @didip: 

1.- Have you tested my previous example? Did it work? 

2.-Can you show me your data? 
    2a.- SELECT * FROM foo; 
    2b.- INSERTS?

3.-Are you building cassandra-lucene-index jar from sources?
   If so, can you show me the output of a 'git log' in the root project path?

**Comment by didip** [comment]
1. Yes, the foo example works :)

2. This is my schema: https://gist.github.com/didip/4fe99538a4acfa9bc31952ac06edcc39.

    * SELECT * FROM hosts: https://gist.github.com/didip/780f9d0cd2da4b866876ee4013cc857d

    * Insert is just a regular insert with the large JSON blob.

3. Yes, I build the JAR from source using `mvn clean package`. This is what I am using now: `cassandra-lucene-index-plugin-3.9.4-RC1-SNAPSHOT.jar`.

    * This is the top most `git log`:

        ```
		commit 50ad5970b5a3ab63f19a72fe273949f74d50492c
		Author: Andrés De la Peña <a.penya.garcia@gmail.com>
		Date:   Tue Nov 29 16:58:03 2016 +0000

		    Optimize columns mapping (improves indexing performance)

		commit 7ae4cd4198680f626f4a503357c2b6dc4ed9c32f
		Author: stratiocommit <asistemas@stratio.com>
		Date:   Thu Nov 24 16:22:55 2016 +0000

		    Prepare for next version

		commit 33ce6d173d089da1ddbab578bd87e81d1af386fd
		Author: stratiocommit <asistemas@stratio.com>
		Date:   Thu Nov 24 16:16:03 2016 +0000

		    [RELEASE] 3.9.3

		commit c3283426de41184a7bc4ef1be1d34d933b179b1d
		Author: Javier Delgado <witokondoria@gmail.com>
		Date:   Wed Nov 23 16:18:13 2016 +0100

		    [QA-228] new jenkinsfile (#241)
		    
		    * [QA-228] new jenkinsfile
		    
		    * including AT services and parameters
		    
		    * missing comma
		    
		    * Delete .jenkins.yml

		commit 88c692f3c26aba1223b7dc339e17460f43289e99
		Author: Andrés de la Peña <adelapena@users.noreply.github.com>
		Date:   Tue Nov 22 13:52:54 2016 +0000

		    Upgrade to Scala 2.12.0 (#242)
        ```

**Comment by ealonsodb** [comment]
Hi @didip 

When any mapper is notified by cassandra with a new row insertion, the mapper reads its column value, try to parse it and build a Lucene Field  with that info. 

When a mapper cannot parse the cell value (for example a float mapper trying to parse 'you.are.awesome') it show a warning in log and ignores that value. 

What happens in your case is that data_float mapper tries to parse '' (empty string), fails and does not continue indexing other map values. So, at the end, that row Lucene Document does not contain any data_float field at all. 

The foo example works perfect because it does not contain any non-parseable float. 

This is a bug, so, we will fix it as soon as posible

Thank you so much @didip

**Comment by didip** [comment]
Wow thank you so much for y'all persistence.

**Comment by adelapena** [comment]
Hi @didip,

We have just committed a [hotfix](https://github.com/Stratio/cassandra-lucene-index/tree/hotfix/issue_246). We hope to merge it early next week.

**Comment by adelapena** [comment]
By the way, given the amount of columns not containing the type of data expected by the mappers, maybe it could be a good idea to have a separate map column per type of data:
```sql
CREATE TABLE IF NOT EXISTS foo (
    id text,
    updated bigint,
    data_string map<text, text>,
    data_float map<text, float>,
    lucene text,
    PRIMARY KEY (id)
);

CREATE CUSTOM INDEX IF NOT EXISTS idx_foo ON foo (lucene) 
USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
    'schema' : '{
        fields : {
            id : {type : "string"},
            updated: {type : "integer"},
            data_string : { type : "string"},
            data_float : { type : "float"}
        }
    }'
};
```

**Comment by didip** [comment]
Wow, super fast, very impressed.

@adelapena yeah, I thought of that as well based on reading this ticket: https://github.com/Stratio/cassandra-lucene-index/issues/179

That would require application side to spend CPU cycles separating fields that are or are not float64.

I am currently benchmarking, on which side do I want to spend the CPU expense. :)

**Comment by adelapena** [comment]
We have just merged the hotfix to branches 3.0.10, 3.9. 3.8 and 3.7. 

I think it would be probably faster to separate fields at client side. Server side, the work would be done in the coordinator and in each replica node, multiplying resources consumption.

**Comment by didip** [comment]
Just tested it, it works. :)

Thank you for the quick turn around.

**Comment by adelapena** [comment]
You are very welcome
