### ISSUE TITLE
Wildcard filter performance

### ISSUE THREAD

**Issue by maxim5** [Stratio/cassandra-lucene-index#247]
We are using Lucene to index file names and overall it works great, but we are looking for ways to improve search performance for queries like `*file*name*`.
Do you have any tips for this? For instance, a particular custom analyzer to help the search engine?
Thanks a lot!

**Comment by adelapena** [comment]
Hi @maxim5,

The performance problems of leading wildcards are due to Lucene itself, and not to the integration between Cassandra and Lucene, so any Lucene/Solr/ElasticSearch literature about the topic should be applicable here.

Probably Lucene wildcard queries are quite optimized, but maybe you could take advantage of some domain-specific characteristic of your data and/or queries. Could you please elaborate more about the use case? Have the queries leading and trailing wildcards at the same time? Are the wildcard queries combined with other queries?

**Comment by maxim5** [comment]
Sure.

Our database is ~170M, including the index, of file names. Without the path, i.e. the base name as it's called in Unix. There is some structure in these files, for example, we know file naming conventions, common extensions, etc.

The task is to find the best files given some partial information. Currently we construct the query with potentially lots of asterisks, search for the candidates and then select the best ones using certain score function. For example, the input might be `[build, except]`, from which we make `*build*except*` in order to find `BuilderException.java`. In the case I describe that's the only Lucene query.

We try to balance search quality and speed, so we could get rid of the leading `*`, or limit the number of them in the middle, if that helps Lucene engine.

**Comment by adelapena** [comment]
Lucene index is based on a prefix tree (trie) that translates ``BuilderException.java`` to ``B``, ``Bu``, ``Bui``, ``Buil``, ``Build``, ``Builde``, ``Builder``, ``BuilderE``, ``BuilderE``, etc.

The prefix of the wildcard queries (everything to the left of the first wildcard) is used to quickly seek in the search tree. Then, all the nodes under the prefix should be scanned, which is the slow part of the search. Thus, anything to make the prefix longer will make the index faster. 

The size of the indexed terms is also relevant, so maybe it could be possible to put the extension of the file in a separate file if the searches are ever refined to a certain file type.

Another option is to use a [text mapper](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#text-mapper) with a [custom analyzer](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#classpath-analyzer), as you suggested.  This analyzer should include a [tokenizer](https://lucene.apache.org/core/5_4_0/core/org/apache/lucene/analysis/Tokenizer.html) to split the file extension and the name components, and maybe a stemmer to lower case them. Thus, ``BuilderException.java`` will be translated to ``builder``,``exception``, ``.java``. Then, the query could be split in a list of wildcard queries with a longer prefix:
```sql
SELECT * FROM paths WHERE expr(paths_idx, '{filter:[
  {type:"wildcard", field:"path", value:"build*"},
  {type:"wildcard", field:"path", value:"except*"}
]}');
```
The problem with this approach is that ``ExceptionBuilder`` will also be matched. To avoid this, you could use a more aggressive stemming to translate ``BuilderException.java`` to ``build``,``except``, ``.java`` and run a phrase query:
```sql
SELECT * FROM paths WHERE expr(paths_idx, '{filter:[
  {type:"phrase", field:"path", value:"build except"}
]}');
-- equivalent to:
SELECT * FROM paths WHERE expr(paths_idx, '{filter:[
  {type:"phrase", field:"path", value:"builder exception"}
]}');
-- equivalent to:
SELECT * FROM paths WHERE expr(paths_idx, '{filter:[
  {type:"phrase", field:"path", value:"builder except"}
]}');
-- equivalent to:
SELECT * FROM paths WHERE expr(paths_idx, '{filter:[
  {type:"phrase", field:"path", value:"build except"}
]}');
```

What do you think? Does it make sense?

**Comment by maxim5** [comment]
Thanks a lot, @adelapena, it makes sense. I'll try to implement your suggestions and get back with the result.

**Comment by maxim5** [comment]
Just want to report that prefix retain really speed things up. Thanks again.

**Comment by adelapena** [comment]
These are very good news :)

Are you going to develop a custom analyzer or is it good enough with the prefixes?

**Comment by maxim5** [comment]
It looks good enough right now. But I don't want to simply throw away the chance to boost it even further.

The only complication is that `Tokenizer` contract seems somewhat tricky. We would like to have behaviour similar to `CharTokenizer`, but in some cases include the separator character in the next token.
So for instance `BuilderException.java` to become `[builder, exception, java]`.
Would you recommend to implement `incrementToken` from scratch, similar to `CharTokenizer`, or there is an out-of-the-box tokenizer that I missed?
Thanks!

**Comment by adelapena** [comment]
Probably there exist some similar analyzer that you can reuse/modify. I think you can find more help about how to develop custom analyzers at [Apache Lucene user list](https://lucene.apache.org/core/discussion.html#java-user-list-java-userluceneapacheorg).

**Comment by adelapena** [comment]
From issue #261 I see that you already have the custom analyzer working. Can we close this issue?

**Comment by maxim5** [comment]
Yes, we're satisfied with its speed. You can close this one too.

**Comment by adelapena** [comment]
Cool, closing. Thanks.
