### ISSUE TITLE
cassandra 3.0.10 analyzer normaliztion

### ISSUE THREAD

**Issue by navidkaeni** [Stratio/cassandra-lucene-index#256]
org.apache.lucene.analysis.fa.PersianAnalyzer
words  are normalized when  indexed but in search , words are not normalized then it cannot find them if i normalized them by myself then it find them

**Comment by ealonsodb** [comment]
Hi @navidkaeni :
 
Can you show us a basic example in CQL with the keyspace, table index creation, some inserts and the query?

**Comment by navidkaeni** [comment]
CREATE KEYSPACE test with replication = {'class':'SimpleStrategy', 'replication_factor': 1};

CREATE TABLE metaitem (
    id UUID ,
  path text,
    value text,
PRIMARY KEY(id,path)
   );

CREATE CUSTOM INDEX metaitem_index ON metaitem ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds': '1',
   'schema': '{
    analyzers: {
         p1: {
            type: "classpath",
            class: "org.apache.lucene.analysis.fa.PersianAnalyzer"
         }
      },
      fields: {
         id: {type: "uuid"},
	     "path":{type:"text"},
		 "value":{type:"text",analyzer :"p1"}
      }
   }'
};

INSERT INTO test.metaitem (id, path, value) VALUES (88bff2ee-01a5-41f5-9189-e5edc912196b ,'user.name[88bff2ee-01a5-41f5-9189-e5edc912196c]', 'کاینی');

SELECT * FROM metaitem; --this query is ok in cassandra and data is in  correct form;
SELECT * FROM metaitem WHERE expr(metaitem_index ,'{
          filter: [{
               type: "match",
              field: "path",
         value: "user.name[*]"
         },{
               type: "fuzzy",
               field: "value",
         value: "کاینی"
         }]
         }');                           --no result;
SELECT * FROM metaitem WHERE expr(metaitem_index ,'{
          filter: [{
               type: "match",
              field: "path",
         value: "user.name[*]"
         },{
               type: "fuzzy",
               field: "value",
         value: "كايني"
         }]
         }'); -- its  ok but i typed ي instead of ی and ك instead of ک  data stored in cassandra is "کاینی" and data in index is كايني

i think they write arabic analyzer once and use it for others like persian and ordu , ...

**Comment by ealonsodb** [comment]
Hello @navidkaeni,

There are two mappers intended to be used with CQL String-based columns (ASCCI, TEXT and VARCHAR). 

Text mapper is associated to a language analyzer, in such a way that every inserted string column value is mapped to a list of language-specific stemmed tokens before being indexed.  

String mapper is intended for untokenized text, and every inserted string column value is indexed as it comes. 

You are using a text mapper with the default 'english' analyzer for ``path`` column. 

So, actually, 'user.name[88bff2ee-01a5-41f5-9189-e5edc912196c]' is analyzed with default English analyzer producing some unknown tokens. 

As stated in [#80](https://github.com/Stratio/cassandra-lucene-index/issues/80), 

"By default in Lucene, Wildcard, Prefix and Fuzzy queries are not passed through the analyzer."

Indeed, Match query values are analyzed, thats why your query '{type: "match",field: "path",value: "user.name[*]"}' produces some results. 

I think you would prefer to use a string mapper for ``path`` column, together with a wildcard query instead of match query for that part. 


```
    CREATE CUSTOM INDEX metaitem_index ON metaitem ()
    USING 'com.stratio.cassandra.lucene.Index'
    WITH OPTIONS = {
        'refresh_seconds': '1',
        'schema': '{
            analyzers: {
                p1: {
                    type: "classpath",
                    class: "org.apache.lucene.analysis.fa.PersianAnalyzer"
                }
            },
            fields: {
                id: {type: "uuid"},
                path:{type:"string"},
                value:{type:"text",analyzer :"p1"}
            }
        }'
    };

    SELECT * FROM metaitem WHERE expr(metaitem_index ,
                '{filter: [
                    {type: "wilcard",field: "path",value: "user.name[*]"},
                    {type: "fuzzy", field: "value", value: "كايني"}
                ]}');
```

Apparently from schema you are inserting user name in ``value`` column. If so, I think you don't need to analyze it, just index it as it is with a string mapper.

Hope this helps.

**Comment by navidkaeni** [comment]
i need analyzer for "value" field and  i think there is a miss understanding here my problem is about unicode characters ( persian characters and arabic characters ).
i insert text to value field with persian characters but when i search them there is no result
i found out in "org.apache.lucene.analysis.fa.PersianAnalyzer" persian characters changed by arabic characters
and if i change persian charachters with arabic ones my search is ok
but its in my code and i think u should add these changes to ur code before search 
tnx

**Comment by ealonsodb** [comment]
As we said, ``fuzzy`` queries are not intended to be used with analyzed text, this is why you are getting erratic results.

In principle, the replacement of persian characters by their arabic counterparts should not be a problem if both the indexed text and the query are analyzed, assuming that the character replacement function is [injective](https://en.wikipedia.org/wiki/Injective_function) (one-to-one).

Indeed, the search works with both persian and arabic chars when we replace the ``fuzzy`` query by a ``match`` query:
```
SELECT * FROM metaitem 
WHERE expr(metaitem_index ,
                '{filter: [
                    {type: "match", field: "path", value: "user.name[*]"},
                    {type: "match", field: "value", value: "کاینی"}
                ]}');
SELECT * FROM metaitem 
WHERE expr(metaitem_index ,
                '{filter: [
                    {type: "match",field: "path",value: "user.name[*]"},
                    {type: "match", field: "value", value: "كايني"}
                ]}');
```
And, as you can see by inserting a row with two words, the ``match`` query is still language sensitive:
```
INSERT INTO test.metaitem (id, path, value) 
VALUES (88bff2ee-01a5-41f5-9189-e5edc912196c ,'user.name[88bff2ee-01a5-41f5-9189-e5edc912196c]', 'کاینی کامپیوتر');
SELECT * FROM metaitem 
WHERE expr(metaitem_index ,
                '{filter: [
                    {type: "match", field: "path", value: "user.name[*]"},
                    {type: "match", field: "value", value: "کاینی"}
                ]}');
SELECT * FROM metaitem 
WHERE expr(metaitem_index ,
                '{filter: [
                    {type: "match",field: "path",value: "user.name[*]"},
                    {type: "match", field: "value", value: "كايني"}
                ]}');
```
I hope that helps.
