### ISSUE TITLE
Index a document only if necessary

### ISSUE THREAD

**Issue by fdimuccio** [Stratio/cassandra-lucene-index#264]
Hello,

thank you for this great project. We are using Cassandra 3.7 alongside cassandra-lucene-index 3.7.5 to index few teras of data. By tracing the indexing process after an UPDATE I noticed that a row is indexed or deleted even if no relevant fields for the lucene index are affected.

In our use case the schema is something like that:

```
CREATE TABLE ks.tbl (
    pk bigint PRIMARY KEY,
    field1 frozen<udt1>,
    field2 frozen<udt2>,
    field3 frozen<udt3>,
    field4 frozen<udt4>,
    field5 frozen<udt5>
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
```
```
CREATE CUSTOM INDEX idx on ks.tbl()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
  'refresh_seconds': '60',
  'schema': '{
    fields: {
        "field3.subfield1": {type: "text"},
        "field3.subfield2": {type: "text"},
        "field3.subfield3": {type: "text"},
        "field3.subfield4": {type: "text"},
        "field3.subfield5": {type: "text"},
        "field3.subfield6": {type: "string", case_sensitive: "false"}
    }
  }'
};
```

Only field3 has data to be indexed, and the dataset is quite sparse, only a small percentage of rows has that field set. I was wondering if it is possible to skip the index operation in case the update does not touch any of the fields that must be indexed: org.apache.cassandra.index.Indexer.updateRow(Row oldRowData, Row newRowData) gives the opportunity to check which fields have been updated. By skipping the operation IndexWriterSkinny does not even need to do a read before write. Probably even the initial compaction (Secondary index creation) could benefits from this optimization.

Is it correct or I'm missing some aspects of the indexing process?

**Comment by adelapena** [comment]
Hi @fdimuccio,

You are totally right, this could be a nice performance improvement for some use cases as yours.

During this week we are going to publish a new release containing hot fixes and merge back changes to previous branches. As soon as we had done this, we will start working on the improvement.

Thanks for the idea!

**Comment by fdimuccio** [comment]
Hello,
in the following commit I tried to implement this optimization (it is against 3.10 branch):

[https://github.com/fdimuccio/cassandra-lucene-index/commit/f042eaaa68b35cc71724e651e74df96026f9aab8](https://github.com/fdimuccio/cassandra-lucene-index/commit/f042eaaa68b35cc71724e651e74df96026f9aab8)

I check if the row to be indexed contains at least one column that is present in the index schema, if it is true then the normal flow applies, otherwise it is skipped. Moreover I added the option `sparse` to the schema definition that can be used to switch on or off this feature, that by default is off.

If you think that this is ok I can make a pr.

**Comment by adelapena** [comment]
Hi @fdimuccio,

This looks awesome! :)

Just a couple of nits:

- IndexWriterSkinny traces "Lucene index skipping document", maybe "Lucene index skipping row" would be more accurate. Also, the same message should be traced in IndexWriterWide.
- We may consider if it is make sense for any use case to don't enable the new `sparse` option. The index writing is also discarded later when `sparse=true` [here](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexService.scala#L226). Maybe the new optimization should always be used.
- lf we go ahead with the `sparse` option, we should add it to the [index builder](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/builder/src/main/java/com/stratio/cassandra/lucene/builder/index/Index.java) and [document it](https://github.com/fdimuccio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#indexing).
- We should be able to enable/disable the new `sparse` option in [acceptance test module](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.10/testsAT) to test behaviour. This should be a [test configuration option](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/testsAT/src/test/java/com/stratio/cassandra/lucene/testsAT/util/CassandraConfig.java) used by [CassandraUtils.createIndex](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/testsAT/src/test/java/com/stratio/cassandra/lucene/testsAT/util/CassandraUtils.java#L260).

What do you think?

**Comment by fdimuccio** [comment]
The reason why I made this optimization optional is because it heavily depends on the data model and index schema, sometimes it can save cpu cycles to not check every time if the row should be indexed or not (especially if there are a lot of columns in the row and it is never updated partially). 

[Here](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexService.scala#L226) the index is anyway modified (by deleting the document). My changes completely skip any index modification. So those operations are a bit different.

About the rest I totally agree, I can make those changes and resubmit it.

**Comment by fdimuccio** [comment]
Here is the updated commit [https://github.com/fdimuccio/cassandra-lucene-index/commit/7bb56f8652ed5210f690c6fb114aebf8907d8dd4](https://github.com/fdimuccio/cassandra-lucene-index/commit/7bb56f8652ed5210f690c6fb114aebf8907d8dd4)

I added the `sparse` option to the  [index builder](https://github.com/fdimuccio/cassandra-lucene-index/blob/feature/sparse_index/builder/src/main/java/com/stratio/cassandra/lucene/builder/index/Index.java#L228-L241), updated [documentation](https://github.com/fdimuccio/cassandra-lucene-index/blob/feature/sparse_index/doc/documentation.rst#indexing) and testsAT.

Sparse flag in tests can be enabled or disabled by `-Dit.sparse=false|true`:
```
mvn -f testsAT/pom.xml -U verify -Dit.host=10.200.0.155 -Dit.monitor_service=jolokia -Dit.monitor_services_url=10.200.0.155:8000,10.200.0.157:8000 -Dit.sparse=true
```

**Comment by ealonsodb** [comment]
Hi @fdimuccio: 
Can you create a PR in our repo, please? I will revise.

**Comment by ealonsodb** [comment]
Hi @fdimuccio: 

You have resolved perfectly the changes that Andres suggested to you. Great for that. 
I have some suggestions:
 
I dont really like the double logical check in [IndexWriterWide](https://github.com/fdimuccio/cassandra-lucene-index/blob/7bb56f8652ed5210f690c6fb114aebf8907d8dd4/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexWriterWide.scala#L66-L71) and [IndexWriterSkinny](https://github.com/fdimuccio/cassandra-lucene-index/blob/7bb56f8652ed5210f690c6fb114aebf8907d8dd4/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexWriterSkinny.scala#L62-L66)


I think IndexService.doesAffectIndex should be "abstract" in IndexService implemented by IndexServiceWide and IndexServiceSkinny. With this approach you can move [!row.isStatic](https://github.com/fdimuccio/cassandra-lucene-index/blob/7bb56f8652ed5210f690c6fb114aebf8907d8dd4/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexWriterWide.scala#L72) logical check to IndexServiceWide.doesAffectIndex. With this change IndexWriterWide.index could result in: 

```scala
  /** @inheritdoc */
  override def index(row: Row) {
    if (service.doesAffectIndex(row)) {
      val clustering = row.clustering
      if (service.needsReadBeforeWrite(key, row)) {
        tracer.trace("Lucene index doing read before write")
        clusterings.add(clustering)
      } else {
        tracer.trace("Lucene index skipping read before write")
        rows.put(clustering, row)
      }
    } else {
      tracer.trace("Lucene index skipping row")
    }
  }
```

In IndexWriterSkinny you check if index is affected by the row in [commit](https://github.com/fdimuccio/cassandra-lucene-index/blob/7bb56f8652ed5210f690c6fb114aebf8907d8dd4/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexWriterSkinny.scala#L61-L68) method. Why not do it in insert() like IndexWriterWide?

It should be like this: 
```scala

  /** @inheritdoc*/
  override def index(row: Row) {
    if (service.doesAffectIndex(row)) {
      this.row = Option(row)
    } else {
      tracer.trace("Lucene index skipping row")
    }
  }
```

Apart from that, i think the commit is great. I will write some unit tests to include in your PR

**Comment by fdimuccio** [comment]
I agree, actually by moving [!row.isStatic](https://github.com/fdimuccio/cassandra-lucene-index/blob/7bb56f8652ed5210f690c6fb114aebf8907d8dd4/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexWriterWide.scala#L72) to [IndexWriterWide.doesAffectIndex](https://github.com/fdimuccio/cassandra-lucene-index/blob/df2a49eae70f26de8815ac5e0a59cb65d7ab0bb9/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexServiceWide.scala#L95-L97) the check become generic enough to be moved from IndexWriterSkinny/IndexWriterWide to [IndexWriter](https://github.com/fdimuccio/cassandra-lucene-index/blob/df2a49eae70f26de8815ac5e0a59cb65d7ab0bb9/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexWriter.scala#L86-L92). Do you think it's fine?

**Comment by ealonsodb** [comment]
Hi @fdimuccio: 
Your last changes are great. I had merged the PR. 

Thank you for your effort

**Comment by ealonsodb** [comment]
If everything is correct, could you please close this issue?

**Comment by fdimuccio** [comment]
It was a pleasure to contribute. Thank you.
