### ISSUE TITLE
geo_point search in a list of tuples returns only first result

### ISSUE THREAD

**Issue by smiklosovic** [Stratio/cassandra-lucene-index#269]
Is there any workaround how to do this?

Having

    addresses list<address>

And in schema

    "place": {
        type: "geo_point",
        latitude: "addresses.latitude",
        longitude: "addresses.longitude"
    }

    '{
        filter: {
            type: "geo_distance",
            field: "place",
            latitude: 45.93894,
            longitude: -60.20489,
            max_distance: "10km"
        }
    }'

I want to search accross all items in that list. Currently it takes into consideration only first value in that list which is kind of funny - why it does not iterate further?

I am using 3.7.5 plugin with Cassandra 3.7

Thanks

**Comment by ealonsodb** [comment]
Hi @smiklosovic: 

Please, could you provide us a full example of your use case including CREATE KEYSPACE, TABLE , INDEX; INSERTS and SELECT, please? 

Something like the first Andres comment in this other [issue](https://github.com/Stratio/cassandra-lucene-index/issues/253)

**Comment by smiklosovic** [comment]
@ealonsodb 

    DROP KEYSPACE IF EXISTS geo_bug;
    DROP INDEX IF EXISTS geo_bug.geo_idx;
    
    CREATE KEYSPACE IF NOT EXISTS geo_bug WITH 
        replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};
    
    CREATE TYPE IF NOT EXISTS geo_bug.geo_address (
        latitude float,
        longitude float
    );
    
    CREATE TABLE IF NOT EXISTS geo_bug.geo_bug_table (
        id text,
        addresses list<FROZEN<geo_bug.geo_address>>,
        lucene text,
        PRIMARY KEY (id)
    );
    
    CREATE CUSTOM INDEX geo_idx ON geo_bug.geo_bug_table(lucene) 
    USING 'com.stratio.cassandra.lucene.Index'
    WITH OPTIONS = {
       'refresh_seconds': '1',
       'schema': '{
          fields: {
             place: {
                type: "geo_point",
                latitude: "addresses.latitude",
                longitude: "addresses.longitude",
                max_levels: 15
             }
          }
       }'
    };
    
    INSERT INTO geo_bug.geo_bug_table (id, addresses) VALUES ('1',
        [
            {
                longitude: 45,
                latitude:45
            },
            {
                longitude: 60,
                latitude: 60
            }
        ]
    );
    
    -- the first query returns "1"
    
    select id from geo_bug.geo_bug_table where expr(geo_idx, '{
        filter: [
            {
                type: "geo_distance",
                field: "place",
                latitude: 45,
                longitude: 45,
                max_distance: "1km"
            }
        ]
    }');
    
    -- the second query returns nothing
    
    select id from geo_bug.geo_bug_table where expr(geo_idx, '{
        filter: [
            {
                type: "geo_distance",
                field: "place",
                latitude: 60,
                longitude: 60,
                max_distance: "1km"
            }
        ]
    }');

**Comment by ealonsodb** [comment]
Hi @smiklosovic :

Sorry for the late response. This is a bug, but not because it cannot index several points for every row using a `geo_point` mapper. This is a bug because the plugin allows to create multicolumn mappers over collections, and it shouldn't. 

We are working in branch [hotfix/non_single_column_mapper](https://github.com/Stratio/cassandra-lucene-index/tree/hotfix/non_single_column_mapper) to add a validation to non single column mappers.

There is a major constraint in Lucene to achieve this functionality. It is the way Lucene flattens nested objects. 

We are adding an explanation of these in [hotfix/fix_collection_docs](https://github.com/Stratio/cassandra-lucene-index/tree/hotfix/fix_collection_docs). 

But you are lucky, because geo point mapper is not the only one mapper that is able to index geospatial things.

You can probably achieve similar functionality using geo_shapes in [wkt](https://es.wikipedia.org/wiki/Well_Known_Text) format using MULTIPOINT:

```sql

CREATE KEYSPACE IF NOT EXISTS geo_bug WITH 
    replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};

CREATE TABLE IF NOT EXISTS geo_bug.geo_bug_table (
    id text,
    place text,
    lucene text,
    PRIMARY KEY (id)
);

CREATE CUSTOM INDEX geo_idx ON geo_bug.geo_bug_table(lucene) 
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds': '1',
   'schema': '{
      fields: {
         place: {
            type: "geo_shape",
            max_levels: 15
         }
      }
   }'
};


INSERT INTO geo_bug.geo_bug_table (id, place) VALUES ('1','MULTIPOINT(45 45, 60 60)');

SELECT id FROM geo_bug.geo_bug_table WHERE expr(geo_idx, '{
    filter: [
        {
            type: "geo_distance",
            field: "place",
            latitude: 45,
            longitude: 45,
            max_distance: "1km"
        }
    ]
}');


SELECT id FROM geo_bug.geo_bug_table WHERE expr(geo_idx, '{
    filter: [
        {
            type: "geo_distance",
            field: "place",
            latitude: 60,
            longitude: 60,
            max_distance: "1km"
        }
    ]
}');
```

Hope this helps

**Comment by smiklosovic** [comment]
Thanks for the answer. I have problem with adding more geopoints over time, when I need to add or remove one, I would need to gather all of them, remove what should be removed and save them back ... little bit cumbersome I would say ... How should I work with MULTIPOINT stuff?

**Comment by adelapena** [comment]
I'm afraid that, if you need frequent partial updates of the list of points, you would need to denormalize and put each point in a single row, maybe in a separate table. If the searches involve other columns, you would need to replicate them in each row.

**Comment by msravi16** [comment]
Hi @ealonsodb-stratio ,
I have tried your example in version 3.11.1 , I am getting the following error.
**InvalidRequest: Error from server: code=2200 [Invalid query] message="Field 'place' requires a mapper of type 'class com.stratio.cassandra.lucene.schema.mapping.GeoPointMapper' but found 'GeoShapeMapper{field=place, column=place, validated=false, maxLevels=15, transformations=[]}'"**
should I do any transformations while I index
