### ISSUE TITLE
Can't index column value of size 140952 for index null

### ISSUE THREAD

**Issue by lucevers** [Stratio/cassandra-lucene-index#27]
I'm loading config files in Cassandra + index with Lucene.
A small column family with 4 fields and a config file of 15M gives no problem.
But a column family with more than 100 fields and one field is a config which is only 271K, then I got an error?  Can't index column value of size 140952 for index null?

**Comment by adelapena** [comment]
How is the error? How is your schema? Could it be related to [issue #13](https://github.com/Stratio/cassandra-lucene-index/issues/13)?

**Comment by lucevers** [comment]
5 servers, release version  2.1.5.0-SNAPSHOT
Fault generation:

Client (gocql)

Error(id,andsiteid,ti,err): 877277b6-38f9-11e5-b3a2-009c02a0c746 10539684 172.25.130.5 Can't index column value of size 138831 for index null on testerdb.testerdbtable
Error(id,andsiteid,ti,err): 87715171-38f9-11e5-b3a1-009c02a0c746 10539703 172.25.143.32 Can't index column value of size 140952 for index null on testerdb.testerdbtable
Error(id,andsiteid,ti,err): e465136e-38f9-11e5-802b-009c02a0c746 10534924 172.25.65.4 Can't index column value of size 323670 for index null on testerdb.testerdbtable
Error(id,andsiteid,ti,err): e465f4f4-38f9-11e5-802c-009c02a0c746 10534922 172.25.65.5 Can't index column value of size 276705 for index null on testerdb.testerdbtable
Error(id,andsiteid,ti,err): e4673ce8-38f9-11e5-802e-009c02a0c746 10534922 172.25.65.5 Can't index column value of size 276705 for index null on testerdb.testerdbtable
Error(id,andsiteid,ti,err): e46a27fa-38f9-11e5-8033-009c02a0c746 10484948 172.25.65.2 Can't index column value of size 269682 for index null on testerdb.testerdbtable
Error(id,andsiteid,ti,err): e46bbc7b-38f9-11e5-8036-009c02a0c746 10484946 172.25.65.3 Can't index column value of size 281810 for index null on testerdb.testerdbtable
Error(id,andsiteid,ti,err): e46aacf6-38f9-11e5-8034-009c02a0c746 10484946 172.25.65.3 Can't index column value of size 281810 for index null on testerdb.testerdbtable


Cassandra LOG

ERROR [SharedPool-Worker-1] 2015-08-04 03:27:42,916 Log.java:49 - Error while
indexing row 9636a8a338f911e5888d009c02a0c746
WARN  [SharedPool-Worker-1] 2015-08-04 03:27:42,916
AbstractTracingAwareExecutorService.java:169 - Uncaught exception on thread
Thread[SharedPool-Worker-1,5,main]: {}
java.lang.IllegalArgumentException: Document contains at least one immense
term in field="opceconfig" (whose UTF8 encoding is longer than the max length
32766), all of which were sktiped.  Please correct the analyzer to not produce
such terms.  The prefix of the first immense term is: '[85, 115, 105, 110,
103, 32, 52, 56, 53, 49, 53, 32, 111, 117, 116, 32, 111, 102, 32, 50, 54, 50,
49, 51, 54, 32, 98, 121, 116, 101]...', original message: bytes can be at most
32766 in length; got 48552
        at
org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:687)
~[lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
        at
org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:359)
~[lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
        at
org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:318)
~[lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
        at
org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:241)
~[lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
        at
org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:465)
~[lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
        at
org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1526)
~[lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
        at
org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1500)
~[lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
        at
com.stratio.cassandra.index.service.LuceneIndex.upsert(LuceneIndex.java:150)
~[main/:na]
        at
com.stratio.cassandra.index.service.RowServiceWide.indexInner(RowServiceWide.java:87)
~[main/:na]
        at
com.stratio.cassandra.index.service.RowService.index(RowService.java:139)
~[main/:na]
        at com.stratio.cassandra.index.RowIndex.index(RowIndex.java:155)
~[main/:na]
        at
org.apache.cassandra.db.index.SecondaryIndexManager$StandardUpdater.updateRowLevelIndexes(SecondaryIndexManager.java:815)
~[main/:na]
        at
org.apache.cassandra.db.AtomicBTreeColumns.addAllWithSizeDelta(AtomicBTreeColumns.java:229)
~[main/:na]
        at org.apache.cassandra.db.Memtable.put(Memtable.java:208) ~[main/:na]
        at
org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1185)
~[main/:na]
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:385)
~[main/:na]
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:348)
~[main/:na]
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:214)
~[main/:na]
        at
org.apache.cassandra.db.MutationVerbHandler.doVerb(MutationVerbHandler.java:54)
~[main/:na]
        at
org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:62)
~[main/:na]
        at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
~[na:1.8.0_45]
        at
org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164)
~[main/:na]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105)
[main/:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]


SCHEMA

CREATE KEYSPACE IF NOT EXISTS testerdb WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 2};

USE testerdb;


CREATE TABLE IF NOT EXISTS testerdbtable (id TimeUUID,
    andsiteid text,
    date timestamp,
    vert map<text,text>,
    dsid text,
    andcontractversion text,
    prfcurrentstatus text,
    andshortcustname text,
    andsiteshortname text,
    scountrycode text,
    accessid text,
    andorigaccesslineid text,
    accessgrpnum text,
    accesscurrentstatus text,
    andnetworktypeid text,
    andaccesstypename text,
    andbackup text,
    andlineinfonumber text,
    andtttid text,
    andorigtttid text,
    tttgrpnum text,
    tttcurrentstatus text,
    andtttitemid text,
    cmsttttectype text,
    cmsttttecsubtype text,
    andtttitemvendor text,
    andtttitemgroup text,
    andtttitemsubgroup text,
    andtttitemproductnumber text,
    cmsbgcproductname text,
    dpoaccessid text,
    hostname text,
    dpodsid text,
    cid text,
    loddback00 text,
    loddback99 text,
    epename text,
    epeti text,
    rd text,
    pewan text,
    cewan text,
    accessfamily text,
    networkfamily text,
    sitestatus text,
    isprimaccess text,
    isbackup text,
    tiamreservationwanid text,
    tiamassignwanid text,
    tiamassignid text,
    tiamreservationid text,
    tiamreservationlbc99id text,
    cncdsid text,
    dpolte text,
    sinti text,
    sinname text,
    sindsid text,
    sinalias text,
    ddcemodel text,
    ddcestate text,
    ddceboxname text,
    ddceaccount text,
    ddceinterfaces map<text,text>,
    ddcelb0ti text,
    ddcelb99ti text,
    ddcebbti text,
    ddcewanintf text,
    ddcewanti text,
    ddceuptime text,
    ddcereloadtime text,
    ddcereloadcause text,
    ddcereloadtype text,
    ddceiosrun text,
    ddceiosflash text,
    ddceioslocation text,
    ddceconfreg text,
    ddcedatasources text,
    ddceconfig text,
    ddceinserted text,
    ddepepe text,
    ddepserviceid text,
    ddepcustomer text,
    ddepxnetimport text,
    ddepxnetexport text,
    ddepintfname text,
    ddepintftype text,
    ddepintfstateadmin text,
    ddepintfstateddr text,
    ddepintfdowndays text,
    ddepintfcustshort text,
    ddepintfsiteshort text,
    ddepintftttgrp text,
    ddepdescrtition text,
    ddepnadescr text,
    ddeptiintf text,
    ddeptittt text,
    ddeppingti text,
    ddeppingintf text,
    ddepnddingdays text,
    ddepvrrp text,
    ddepvpls text,
    ddepsap text,
    ddeplag text,
    ddepstag text,
    ddepctag text,
    ddepqosingress text,
    ddepqosegress text,
    ddepshedpol text,
    ddepsapstateadmin text,
    ddepsapstateddr text,
    ddepbytescount text,
    ddepbytesdiff text,
    ddepnotrafficdays text,
    ddeplaststatuschange text,
    ddeplastmgmtchange text,
    ddeplinenumber text,
    ddepinserted text,
    ddepecontext text,
    cncsiteddtions text,
    ddceserial text,
    cnm map<text,text>,
    ddlte map<text,text>,
    ddprocodac map<text,text>,
    ddepservicetype text,
    rad map<text,text>,
    z_lucene varchar,
PRIMARY KEY (id,accessid));

CREATE INDEX IF NOT EXISTS ix_sindsid on testerdbtable (sindsid);
CREATE INDEX IF NOT EXISTS ix_accessid ON testerdb.testerdbtable (accessid);
CREATE INDEX IF NOT EXISTS ix_pewan ON testerdb.testerdbtable (pewan);
CREATE INDEX IF NOT EXISTS ix_cncdsid ON testerdb.testerdbtable (cncdsid);
CREATE INDEX IF NOT EXISTS ix_loddback00 ON testerdb.testerdbtable (loddback00);
CREATE INDEX IF NOT EXISTS ix_andsiteid ON testerdb.testerdbtable (andsiteid);

CREATE CUSTOM INDEX IF NOT EXISTS nurpr_index
  ON  testerdb.testerdbtable (z_lucene) 
  USING 'org.apache.cassandra.db.index.stratio.RowIndex'
  WITH OPTIONS = {
      'refresh_seconds':'1',
      'num_cached_filters':'1',
      'ram_buffer_mb':'64',
      'max_merge_mb':'5',
      'max_cached_mb':'30',
      'schema':'{
        default_analyzer:"org.apache.lucene.analysis.core.WhitespaceAnalyzer",
        fields:{
                id:{type:"uuid"},
                andsiteid:{type:"string"},
                date:{type:"date", pattern: "yyyy/MM/dd"},
                vert:{type:"string"},
                dsid:{type:"string"},
                andcontractversion:{type:"string"},
                prfcurrentstatus:{type:"string"},
                andshortcustname:{type:"string"},
                andsiteshortname:{type:"string"},
                scountrycode:{type:"string"},
                accessid:{type:"string"},
                andorigaccesslineid:{type:"string"},
                accessgrpnum:{type:"string"},
                accesscurrentstatus:{type:"string"},
                andnetworktypeid:{type:"string"},
                andaccesstypename:{type:"string"},
                andbackup:{type:"string"},
                andlineinfonumber:{type:"string"},
                andtttid:{type:"string"},
                andorigtttid:{type:"string"},
                tttgrpnum:{type:"string"},
                tttcurrentstatus:{type:"string"},
                andtttitemid:{type:"string"},
                cmsttttectype:{type:"string"},
                cmsttttecsubtype:{type:"string"},
                andtttitemvendor:{type:"string"},
                andtttitemgroup:{type:"string"},
                andtttitemsubgroup:{type:"string"},
                andtttitemproductnumber:{type:"string"},
                cmsbgcproductname:{type:"string"}, 
                dpoaccessid:{type:"string"},
                hostname:{type:"string"},
                dpodsid:{type:"string"},
                cid:{type:"string"},
                loddback00:{type:"string"},
                loddback99:{type:"string"},
                epename:{type:"string"},
                epeti:{type:"string"},
                rd:{type:"string"},
                pewan:{type:"string"},
                cewan:{type:"string"},
                accessfamily:{type:"string"},
                networkfamily:{type:"string"},
                sitestatus:{type:"string"},
                isprimaccess:{type:"string"},
                isbackup:{type:"string"},
                tiamreservationwanid:{type:"string"},
                tiamassignwanid:{type:"string"},
                tiamassignid:{type:"string"},
                tiamreservationid:{type:"string"},
                tiamreservationlbc99id:{type:"string"},
                cncdsid:{type:"string"},
                dpolte:{type:"string"},
                sinti:{type:"string"},
                sinname:{type:"string"},
                sindsid:{type:"string"},
                sinalias:{type:"string"},
                ddcemodel:{type:"string"},
                ddcestate:{type:"string"},
                ddceboxname:{type:"string"},
                ddceaccount:{type:"string"},
                ddceinterfaces:{type:"string"},
                ddcelb0ti:{type:"string"},
                ddcelb99ti:{type:"string"},
                ddcebbti:{type:"string"},
                ddcewanintf:{type:"string"},
                ddcewanti:{type:"string"},
                ddceuptime:{type:"string"},
                ddcereloadtime:{type:"string"},
                ddcereloadcause:{type:"string"},
                ddcereloadtype:{type:"string"},
                ddceiosrun:{type:"string"},
                ddceiosflash:{type:"string"},
                ddceioslocation:{type:"string"},
                ddceconfreg:{type:"string"},
                ddcedatasources:{type:"string"},
                ddceconfig:{type:"string"},
                ddceinserted:{type:"string"},
                ddepepe:{type:"string"},
                ddepserviceid:{type:"string"},
                ddepcustomer:{type:"string"},
                ddepxnetimport:{type:"string"},
                ddepxnetexport:{type:"string"},
                ddepintfname:{type:"string"},
                ddepintftype:{type:"string"},
                ddepintfstateadmin:{type:"string"},
                ddepintfstateddr:{type:"string"},
                ddepintfdowndays:{type:"string"},
                ddepintfcustshort:{type:"string"},
                ddepintfsiteshort:{type:"string"},
                ddepintftttgrp:{type:"string"},
                ddepdescrtition:{type:"string"},
                ddepnadescr:{type:"string"},
                ddeptiintf:{type:"string"},
                ddeptittt:{type:"string"},
                ddeppingti:{type:"string"},
                ddeppingintf:{type:"string"},
                ddepnddingdays:{type:"string"},
                ddepvrrp:{type:"string"},
                ddepvpls:{type:"string"},
                ddepsap:{type:"string"},
                ddeplag:{type:"string"},
                ddepstag:{type:"string"},
                ddepctag:{type:"string"},
                ddepqosingress:{type:"string"},
                ddepqosegress:{type:"string"},
                ddepshedpol:{type:"string"},
                ddepsapstateadmin:{type:"string"},
                ddepsapstateddr:{type:"string"},
                ddepbytescount:{type:"string"},
                ddepbytesdiff:{type:"string"},
                ddepnotrafficdays:{type:"string"},
                ddeplaststatuschange:{type:"string"},
                ddeplastmgmtchange:{type:"string"}, 
                ddeplinenumber:{type:"string"},
                ddepinserted:{type:"string"},
                ddepecontext:{type:"string"},
                cncsiteddtions:{type:"string"},
                ddceserial:{type:"string"},
                cnm:{type:"string"},
                ddlte:{type:"string"},
                ddprocodac:{type:"string"},
                ddepservicetype:{type:"string"},
                rad:{type:"string"}
                }
  }'};

**Comment by adelapena** [comment]
Indeed, it's related to [issue #13](https://github.com/Stratio/cassandra-lucene-index/issues/13). There is a Lucene limitation in max token size:

https://issues.apache.org/jira/browse/LUCENE-5472
https://lucene.apache.org/core/5_1_0/core/org/apache/lucene/index/IndexWriter.html#addDocument(java.lang.Iterable)

However, the problem is affecting to Lucene DocValues, which are used to sort results. If you are not interested in sorting results by "opceconfig", you can upgrade to [2.1.8.1](https://github.com/Stratio/cassandra-lucene-index/tree/2.1.8.1) and disable sorting in large columns.

**Comment by lucevers** [comment]
Sorting is not needed only searching!
I shall upgrade .
By the way, do you know the answer for issue #21 , extending a field in Cassandra and Lucene.

Thanks!

**Comment by lucevers** [comment]
Upgrade to 2.1.8.1 and disable sorting is performed.
  I did not saw the error reports:  Can't index column value of size 140952 for index null.
  So the problem is solved.

  The only error reports I still have are: "no response received from cassandra within timeout period"
  I don't think that this report is caused by a delay of the additional Lucene index?

**Comment by ealonsodb** [comment]
Are you seeing any indexing error in logs? You can view Stratio logs adding this line to conf/logback.xml:
```
<logger name="stratio" level="INFO"/>
```
If you dont see any errors you must increase timeout

**Comment by lucevers** [comment]
Thanks! I shall extend the logback.xml file and test again.

**Comment by lucevers** [comment]
Results:

  Got a warning:
    WARN  [SharedPool-Worker-3] 2015-08-08 08:01:58,375 AbstractTracingAwareExecutorService.java:169 - Uncaught exception on thread Thread[SharedPool-Worker-3,5,main]: {}
java.lang.RuntimeException: java.lang.IllegalArgumentException: Document contains at least one immense term in field="cncsiteoptions" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[91, 10, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 34, 99, 111, 110, 103, 108, 34, 58, 32, 34, 77]...', original message: bytes can be at most 32766 in length; got 63515
        at com.stratio.cassandra.lucene.Index.index(Index.java:156) ~[cassandra-lucene-index-plugin-2.1.8.1.jar:na]
        at org.apache.cassandra.db.index.SecondaryIndexManager$StandardUpdater.updateRowLevelIndexes(SecondaryIndexManager.java:834) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.AtomicBTreeColumns.addAllWithSizeDelta(AtomicBTreeColumns.java:229) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Memtable.put(Memtable.java:210) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1237) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:400) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:363) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:214) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.MutationVerbHandler.doVerb(MutationVerbHandler.java:54) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:62) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_45]
        at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [apache-cassandra-2.1.8.jar:2.1.8]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

This field has a length of 53K.   (JSON model)
We are using the WhitespaceAnalyser.
We did not lost data, all data of the warning field is available.

I did a second exercise by shuting down a node and checked if I could bring the mode back up.
I followed the method; http://docs.datastax.com/en/cassandra/1.2/cassandra/operations/ops_backup_noderestart_t.html
But then I was blocked because of lucene/write.lock
So I dropped the Lucene index, started the node (oke now) en created the lucene index again.
Seems oke.

**Comment by lucevers** [comment]
We see error in de cassandra logfile: seems the same problem.
The field is a string and sorted: false . (cassandra index).

ERROR [SharedPool-Worker-8] 2015-08-09 11:12:08,563 Log.java:49 - Error while indexing row 889b2fa03db011e5bd00001e0bd13184 in Lucene index masterdb.masterdbtable.nurpr_index
WARN  [SharedPool-Worker-8] 2015-08-09 11:12:08,564 AbstractTracingAwareExecutorService.java:169 - Uncaught exception on thread Thread[SharedPool-Worker-8,5,main]: {}
java.lang.RuntimeException: java.lang.IllegalArgumentException: Document contains at least one immense term in field="cncsiteoptions" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[91, 10, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 34, 99, 111, 110, 103, 108, 34, 58, 32, 34, 69]...', original message: bytes can be at most 32766 in length; got 40479
        at com.stratio.cassandra.lucene.Index.index(Index.java:156) ~[cassandra-lucene-index-plugin-2.1.8.1.jar:na]
        at org.apache.cassandra.db.index.SecondaryIndexManager$StandardUpdater.updateRowLevelIndexes(SecondaryIndexManager.java:834) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.AtomicBTreeColumns.addAllWithSizeDelta(AtomicBTreeColumns.java:229) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Memtable.put(Memtable.java:210) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1237) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:400) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:363) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:214) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.MutationVerbHandler.doVerb(MutationVerbHandler.java:54) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:62) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_45]
        at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [apache-cassandra-2.1.8.jar:2.1.8]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: Document contains at least one immense term in field="cncsiteoptions" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[91, 10, 32, 32, 32, 32, 32, 123, 10, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 34, 99, 111, 110, 103, 108, 34, 58, 32, 34, 69]...', original message: bytes can be at most 32766 in length; got 40479
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.jav

**Comment by adelapena** [comment]
Hi,

It seems that the latest Lucene versions fail with tokens over 32766 bytes in length, independently of if they are sorted or not. So it's the hard limit for ``string`` fields. If you want to index large fields using Lucene, then you must use a ``text`` mapper with an analyzer able to split it in smaller tokens. I have added a token filter to discard this large tokens and log a warning. This changes, and a bug related with default analyzer selection, are in [master branch](https://github.com/Stratio/cassandra-lucene-index/tree/master). 

However, according to your log report, the failing field is named "cncsiteoptions", which is not present in your posted index schema. How is this field mapped? You say that you are using WhitespaceAnalyzer, which is set as default_analyzer in the posted schema. However, all the fields are mapped using ``string`` mapper instead of ``text`` mapper, which means not analyzed field. You should use ``text``mapper if you want the default whitespace analyzer to be applied:
```
CREATE CUSTOM INDEX IF NOT EXISTS nurpr_index
ON testerdb.testerdbtable (z_lucene) 
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
'refresh_seconds':'1',
'ram_buffer_mb':'64',
'max_merge_mb':'5',
'max_cached_mb':'30',
'schema':'{
default_analyzer:"whitespace",
fields:{
id:{type:"uuid"},
andsiteid:{type:"string"},
date:{type:"date", pattern: "yyyy/MM/dd"},
vert:{type:"text"},
dsid:{type:"text"},
andcontractversion:{type:"text", sorted:false},
prfcurrentstatus:{type:"text", sorted:false},
...
cncsiteoptions:{type:"text", sorted:false},
}
}'};
```
I hope it helps.

**Comment by lucevers** [comment]
Our schema is not completed yet, there a new field extension.
So fo the new field:
Schema  Cassandra:
------------------------------
cncsiteoptions text

Schema Lucene:
-------------------------
cncsiteoptions:{type:"string", sorted : false},

I did'nt make a difference between text and string. But you are right there is a difference.
All string types shall be replaced by a text type, we shall test again.
I shall return with the results.

**Comment by adelapena** [comment]
Great. Please use the version in [master branch](https://github.com/Stratio/cassandra-lucene-index/tree/master) because it contains improvements in token management that are not present in 2.1.8.1 and some related bug fixing. If after using ``whitespace`` there are still too large tokens then you will see error messages in Cassandra log files.

**Comment by lucevers** [comment]
oke, if I build the new plugin I got: cassandra-lucene-index-plugin-2.1.8.2-SNAPSHOT.jar.
I supose plugin-2.1.8.2 is the right version.

**Comment by adelapena** [comment]
The right version fixing these problems is 2.1.8.2-SNAPSHOT. We will release 2.1.8.2 not later than this wee. This will be presumably very similar to the current snapshot.

**Comment by lucevers** [comment]
Result of the tests:  No Time outs, the problem is solved by changing the string type to text type . (Lucene schema)

Thanks for help!
