### ISSUE TITLE
wildcards in udt collections

### ISSUE THREAD

**Issue by smiklosovic** [Stratio/cassandra-lucene-index#270]
I have hard time to figure out how this plugin works.

I am doing this 

    SELECT id FROM a.b WHERE 
        expr(idx, '{filter: 
                {type: "phrase", field: "addresses.city", value: "Washington"}
            }');

This one gives me the result.

But when I do it like this, it is empty

    SELECT id FROM a.b WHERE
        expr(idx, '{filter:
            {type: "wildcard", field: "addresses.city", value: "Washington"}
        }');

How can I do wildcard query on some fields in collections?

**Comment by ealonsodb** [comment]
Hi @smiklosovic : 

You dont need to figure out how this plugin works. You just need to read the [documentation](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst). Please notice the documentation is versioned also. 

[Wildcard](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#wildcard-search) queries need wildcard ('*') pattern.

[Phrase](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#phrase-search)  queries are usefull for a sequence of words. 

For just looking for a exact value, you can use a [Match](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#match-search) query.

Hope this helps.

**Comment by smiklosovic** [comment]
I have resolved this by adding some default analyzer. Only after that I have been able to do this.
