### ISSUE TITLE
Different algorithm for fuzzy search

### ISSUE THREAD

**Issue by smiklosovic** [Stratio/cassandra-lucene-index#271]
We are using Jaro-Winkler instead of that Damerau-Levenstain.

Is it possible to switch between these two?

**Comment by ealonsodb** [comment]
Hi 

As stated in [doc](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#fuzzy-search), you only have [Damerau–Levenshtein](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance)  or [Levenshtein](https://en.wikipedia.org/wiki/Levenshtein_distance) for distance calculation in fuzzy queries.

**Comment by smiklosovic** [comment]
what do I have to do in order to support that? I dont mind to implement it myself and fork this.

Where it is specified which one will be used?

**Comment by ealonsodb** [comment]
Hi @smiklosovic : 

As you probably know, the search library used in this project is [Apache Lucene](https://lucene.apache.org/core). 

There are four steps:

First, you should implement a custom `JaroWinklerQuery` in lucene as recommended in this [thread](http://lucene.472066.n3.nabble.com/Using-Lucene-with-Jarowinkler-td551485.html) in its user list. Please use the [lucene version](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/plugin/pom.xml#L43) you are using.

Second , you need to code your own `JaroWinklerCondition` in [cassandra-lucene-index/plugin](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.10/plugin), just like the [fuzzy condition](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/plugin/src/main/java/com/stratio/cassandra/lucene/search/condition/FuzzyCondition.java), with its [builder](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/plugin/src/main/java/com/stratio/cassandra/lucene/search/condition/builder/FuzzyConditionBuilder.java). You also need to choose a custom condition type in [ConditionBuilder](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/plugin/src/main/java/com/stratio/cassandra/lucene/search/condition/builder/ConditionBuilder.java#L32-L48) just to determine the type of the query. You could add a unit test like [FuzzyConditionTest](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/plugin/src/test/java/com/stratio/cassandra/lucene/search/condition/FuzzyConditionTest.java)

Third, you should include the `JaroWinklerCondition` builder in [cassandra-lucene-index/builder](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.10/builder) just like [FuzzyCondition](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/builder/src/main/java/com/stratio/cassandra/lucene/builder/search/condition/FuzzyCondition.java) and add a method to [Builder](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/builder/src/main/java/com/stratio/cassandra/lucene/builder/Builder.java#L341) to be able to create that query with builder submodule library. There are [unit test](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/builder/src/test/java/com/stratio/cassandra/lucene/builder/BuilderTest.java#L501-L518) in builder too.

And as a last step, you could add a acceptance test like [FuzzySearchIT](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/testsAT/src/test/java/com/stratio/cassandra/lucene/testsAT/search/FuzzySearchIT.java) in [cassandra-lucene-index/testsAT](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.10/testsAT)

First step is hard to achieve, others are easy.

Hope this helps

**Comment by smiklosovic** [comment]
Thanks a lot for your detailed answer.

What I do not understand is how the implementation in this plugin enables me to search for that. I mean, by creating JaroWinklerQuery, that query itself would be saved where exactly and how it would be used from this plugin? Any hints please?

**Comment by adelapena** [comment]
Hi @smiklosovic,

This plugin allows you translate Cassandra data and queries into Apache Lucene queries. Apache Lucene is another project that **does not** support Jaro-Winkler distance-based queries. So, what @ealonsodb suggest you is to create your own Lucene query implementation and write the plugin classes wrapping it.

Regarding where the query will be stored, the new query type would be a piece of code added to the existing code of the plugin, and will be part of the Java JAR file that the code of this plugin becomes when compiled.

About if someone has written any Lucene query using Jaro-Winkler, you can take a look to Lucene documentation and address any question to the [Apache Lucene user community](https://lucene.apache.org/core/discussion.html). Once you have the query working in Lucene itself, we can provide help with the integration with Cassandra, which is in the scope of this project.

We don't specify anywhere that Damerau-Levenstain will be used, we just use [Lucene's FuzzyQuery implementation](https://lucene.apache.org/core/5_3_0/core/org/apache/lucene/search/FuzzyQuery.html), which only implements this kind of distance function. You can take a look to [Lucene's code](https://github.com/apache/lucene-solr/blob/53981795fd73e85aae1892c3c72344af7c57083a/lucene/core/src/java/org/apache/lucene/search/FuzzyQuery.java) and try to modify their implementation.

About the linked Jaro-Winkler implementation, I think it is used with a very different purpose, being related to spell checking and not to fuzzy queries. Is a fuzzy query using Jaro-Winkler distance what you want?
