### ISSUE TITLE
joda time issue:  wrong zoneOffset

### ISSUE THREAD

**Issue by imhy** [Stratio/cassandra-lucene-index#272]
Hi!
During mvn clean package, some tests in DateParserTest failed with error like this:

java.lang.AssertionError: yyyy/MM/dd for Mon Nov 02 23:00:00 NOVT 2015 should generate Mon Nov 02 23:00:00 NOVT 2015 but get Mon Nov 02 00:00:00 NOVT 2015 
Expected :Mon Nov 02 23:00:00 NOVT 2015
Actual   :Mon Nov 02 00:00:00 NOVT 2015

Seems that it is wrong timezone info in joda-time.

When i add latest version joda-time to pom 
<dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.9.7</version>
 </dependency>
tests finished without errors.

**Comment by adelapena** [comment]
Hi @imhy,

You're totally right about the failing tests. We have just fixed the tests at PR #274, and we are also trying to get our internal CI system fixed. 

Changing the joda-time dependency would be great for us, but it would mean that Apache Cassandra would also use the same upgraded library, and we can't guarantee that it is not going to break it.

Thanks for reporting.
