### ISSUE TITLE
JAR files are deployed wrongly to Maven Central

### ISSUE THREAD

**Issue by smiklosovic** [Stratio/cassandra-lucene-index#279]
I have Cassandra Maven plugin where I put cassandra-lucene-index-plugin-3.7.6.jar as a Maven dependency which means that when I start that plugin, I have that JAR automatically in runtime of embedded Cassandra.

Initially, what I was doing is that I cloned this repository, I checkout to 3.7.6, mvn clean install and I had that JAR in my local Maven repository.

Then I wanted to put this stuff to Jenkins but it was constantly saying to me that 'Unable to find custom indexer class 'com.stratio.cassandra.lucene.Index'.

I could not wrap my head around this.

After double checking that all dependencies are same, version-wise, I did md5sum on both my local plugin built from repository and plugin JAR released to Maven Central.

To my surprise, these JARs do not have same size, mine has 17MB and released in Maven Central only 15MB and when I download that JAR from Central, it is not even possible to extract it.

Better to fix this very quickly please ... We need to deploy our custom version of that into our private repository.

**Comment by ealonsodb** [comment]
Hi @smiklosovic: 

Sorry for this late answer. Yes, we have discovered a bug in our release generation pipeline and last generated releases plugin jars are not correct. 

I suppose you have achieve it deploying a custom maven repository. If you havent done yet [this](http://www.javaworld.com/article/2073230/maven-repository-in-three-steps.html) can help you. 

Hope this helps and please excuse us again for this late answer.
