### ISSUE TITLE
Error while creating index

### ISSUE THREAD

**Issue by jsebrien** [Stratio/cassandra-lucene-index#28]
I created this table:

CREATE TABLE IF NOT EXISTS flat3 (
    id uuid,
    title text,
    description text,
    creationDate timestamp,
    lastModificationDate timestamp,
    lucene TEXT,
    PRIMARY KEY(id)
);

And I would like to create the following index (I'm using the 2.1.8.1 version):

CREATE CUSTOM INDEX flat3_index ON flat3 (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '10',
    'schema' : '{
        fields : {
            id    : {type : "uuid"},
            title  : {type : "text"},
            description  : {type : "text"},
            lastModificationDate  : {type : "date"}
        }
    }'
};

But I get the following error:

ErrorMessage code=2300 [Query invalid because of configuration issue] message="Error while validating Lucene index options: 'schema' is invalid : No column definition lastModificationDate for mapper lastModificationDate"

Any idea?

**Comment by mbriot** [comment]
cassandra field are case insensitive,

    describe table flat3;

create your custom index like that : 

    CREATE CUSTOM INDEX flat3_index ON flat3 (lucene)
    USING 'com.stratio.cassandra.lucene.Index'
    WITH OPTIONS = {
    'refresh_seconds' : '10',
    'schema' : '{
    fields : {
    id : {type : "uuid"},
    title : {type : "text"},
    description : {type : "text"},
    lastmodificationdate : {type : "date"}
    }
    }'
    };

**Comment by jsebrien** [comment]
Ok I forgot that, thanks. Also, I noticed, all indexed fields have to be set during insertion. Is there a way to insert rows with null columns, even if these columns are indexed?

**Comment by adelapena** [comment]
All single-field mappers allow null values, whereas multi-field mappers (geo_point, date_range and bitemporal) need all the fields to be present. However it seems a good idea to change this behavior. I think we could modify this kind of mappers to ignore rows with all columns with null value, e.g. ignore points with null latitude and null longitude. However, a row with a null latitude and a not null longitude should produce a failure. What do you think about this?

**Comment by jsebrien** [comment]
Well, I would prefer if multi field mappers allow either:  
- null values for all its fields
- or all its fields setted

In any other case (partially set fields), the mapper should produce a failure.

**Comment by adelapena** [comment]
The we agree. I will add this new behavior ASAP, probably this week. Thanks!

**Comment by jsebrien** [comment]
This is great, thanks.

**Comment by adelapena** [comment]
Done! The changes are in master branch and they will be available in the next release.

**Comment by minauser** [comment]
Hi

I am trying to do a case-insensitive search in stratio/lucene/cassandra.

Therefore, I created the index as below:

CREATE CUSTOM INDEX my_index ON my_table (lucene)
USING 'com.stratio.cassandra.lucene.Index.RowIndex'
WITH OPTIONS = {
'refresh_seconds' : '10',
'schema' : '{
fields : {
id : {type : "uuid"},
title : {type : "string", case_sensitive: false}
}
}'
};

However, if I in my test instead of "TestTitle", I use "testTitle", it returns nothing.

**Comment by minauser** [comment]
Hi

I am trying to do a case-insensitive search in stratio/lucene/cassandra.

Therefore, I created the index as below:

CREATE CUSTOM INDEX my_index ON my_table (lucene)
USING 'com.stratio.cassandra.lucene.Index.RowIndex'
WITH OPTIONS = {
'refresh_seconds' : '10',
'schema' : '{
fields : {
id : {type : "uuid"},
title : {type : "string", case_sensitive: false}
}
}'
};

However, if in my test instead of "TestTitle", I use "testTitle", it returns nothing.

I really appreciate if I get the information on how I can do a case_insensitive search.

**Comment by ealonsodb** [comment]
Hi @minauser, 

Can you write down here the Keyspace creation, table creation and filter query please??

**Comment by minauser** [comment]
CREATE CUSTOM INDEX my_index ON my_table (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
'refresh_seconds' : '10',
'schema' : '{
fields : {
id : {type : "uuid"},
name : {type : "string", case_sensitive: false}
}
}'
};

CREATE KEYSPACE IF NOT EXISTS my_keyspace WITH replication = {'class':'SimpleStrategy', 'replication_factor':1};

CREATE TABLE IF NOT EXISTS my_table(id uuid, name varchar, lucene TEXT, PRIMARY KEY(id)

INSERT INTO my_table(name, id) VALUES (“TestName”, "1c3d775f-d251-448f-9d51-5f3e0689ff0c") IF NOT EXISTS

SELECT name, id FROM my_table WHERE lucene = 'filter: { type: "match", field: "name", value: "TestName" }'

Returns 1 row BUT if I change the query to 

SELECT name, id FROM my_table WHERE lucene = 'filter: { type: "match", field: "name", value: "testName" }'

Returns nothing!

**Comment by adelapena** [comment]
This will be answered at #62. @minauser, please don't copy-paste same message in three threads at a time, and don't mix your own issues with another not-related ones, specially if they are closed.
