### ISSUE TITLE
Engine fails to parse it's own generated JSON

### ISSUE THREAD

**Issue by maxim5** [Stratio/cassandra-lucene-index#284]
Build the JSON like this:
```
Builder.search().filter(
  Builder.bool().must(
    Builder.range("x").lower(-10).upper(10),
    Builder.range("y").lower(-10).upper(10)
  )
).build()
```

It corresponds to the following JSON:
`{"filter":[{"type":"boolean","must":[{"type":"range","field":"x","lower":-10,"upper":10},{"type":"range","field":"y","lower":-10,"upper":10}]}]}`.

However, the engine fails to parse this JSON:
```
com.datastax.driver.core.exceptions.InvalidQueryException: Unparseable JSON search: Unexpected token (START_OBJECT), expected VALUE_STRING: need JSON String that contains type id (for subtype of com.stratio.cassandra.lucene.search.condition.builder.ConditionBuilder)
```

Solution that works for me is to drop `[]` in `filter`:
`{filter: {type: "boolean", must:[{type:"range",field:"x",lower:-10,upper:10}, {"type":"range","field":"y","lower":-10,"upper":10}]}}`

But I can't make Java builder generate this kind of JSON, have to do it manually.

**Comment by ealonsodb** [comment]
Hi @maxim5: 

Can you show us cassandra-lucene-index-plugin, cassandra-lucene-index-builder and cassandra version, please?

**Comment by maxim5** [comment]
Hi @ealonsodb 

Cassandra 3.5, `cassandra-lucene-index-plugin-3.5.0.jar`, `cassandra-lucene-index-builder-3.9.6.jar`.
Thanks!

**Comment by adelapena** [comment]
Hi @maxim5,

JSON syntax was improved in [3.7.1](https://github.com/Stratio/cassandra-lucene-index/blob/3.9.5/CHANGELOG.md#371-july-05-2016) to accept multiple clauses in `filter` and `query`. The new syntax is backward compatible in the sense that the server (Cassandra) accepts searches with the old syntax. However, prior Cassandra releases (such as 3.5.0) don't accept searches with the new syntax, as the ones generated by `cassandra-lucene-index-builder-3.9.6`.

**Comment by maxim5** [comment]
Hi @adelapena 

Got it! One way to improve the builder would be not to generate a list if there is just one item.
But switching to latest Cassandra index will do for me. And I like the new syntax sugar. Thanks!
