### ISSUE TITLE
Cassandra 2.2.0 support ?

### ISSUE THREAD

**Issue by morten-holm** [Stratio/cassandra-lucene-index#29]
Hi 

Any plans for supporting cassandra 2.2.0 ?

Morten

**Comment by adelapena** [comment]
Hi,

Yes, we will add support for 2.2.0 as soon as possible, although the current stable release is 2.1.8.

**Comment by AndreasPetter** [comment]
Hi,
had a problem and needed a version that works with 2.2.0, so I made a few changes to get that runnnig. Doesn't support 2.2.0-functions other than count, though. Should I PR?
Rgards, Andi

**Comment by adelapena** [comment]
Hi,

I have created a branch named [feature/upgrade_to_cassandra_2.2.0](https://github.com/Stratio/cassandra-lucene-index/tree/feature/upgrade_to_cassandra_2.2.0), you can PR to this branch.

If I'm not wrong, the index API remains unchanged, but the new version requires changes in LuceneQueryHandler, doesn't it?

Thanks for your interest

**Comment by AndreasPetter** [comment]
afaict, LuceneQueryHandler has been renamed to IndexQueryHandler, but yes i didn't make changes to the index API. In fact it has only been a few lines change.
