### ISSUE TITLE
ServerError: java.lang.NoClassDefFoundError: org/apache/cassandra/db/ReadOrderGroup

### ISSUE THREAD

**Issue by nyitzkj1992** [Stratio/cassandra-lucene-index#292]
Hi,

I am new to Stratio lucene index and I just installed Cassandra server 3.10 and lucene index plugin.

However, when I trying to run the sample code, it generates the following problem.

![capture](https://cloud.githubusercontent.com/assets/26145046/23619107/935da082-0260-11e7-8ec3-6d633ad0c889.JPG)

Could you help me look into it?

Thank you

Jay

**Comment by ealonsodb** [comment]
Hi @nyitzkj1992: 

If you are new to cassandra-lucene-index, we recommend you to read carefully the [documentation](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst), specially [Installation](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#installation) section. 

You will discover that cassandra-lucene-index version numbers are closely related to cassandra version. I think you are using a wrong cassandra-lucene-index version. We haven't released yet a 3.10.x version but we will do it soon. 
I have tested a generated jar from [branch-3.10](https://github.com/stratio/cassandra-lucene-index/tree/branch-3.10) and the example works perfect. 

Hope this helps

**Comment by nyitzkj1992** [comment]
Hi ealonsodb,

Thank you for your response. But actually we just used the branch-3.10 jar file you gave me in your response for Cassandra v3.10.

But it still generates the following problem.

Thank you

**Comment by ealonsodb** [comment]
Hi @nyitzkj1992: 
As i mentioned before, it worked perfect with last commit in [branch-3.10](https://github.com/Stratio/cassandra-lucene-index/commits/branch-3.10). 

The error says that something is trying to use a already-non-existing ReadOrderGroup class. 

ReadOrderGroup class in cassandra was refactored/deleted in cassandra 3.2.  

If you look for any use/dependency of that class in [branch-3.10](https://github.com/Stratio/cassandra-lucene-index/commits/branch-3.10), you will not see anything.

I dont know how you have deployed the cluster or if you have missed anything but I would recomend you to look for an old cassandra-lucene-index jar in $CASSANDRA_HOME/lib. 
Remove it and restart cassandra.

Hope this helps

**Comment by nyitzkj1992** [comment]
Thank you ealonsodb.
I have solved this issue.
I will close it
