### ISSUE TITLE
Support Cassandra-3.0.11

### ISSUE THREAD

**Issue by cooldoger** [Stratio/cassandra-lucene-index#293]
3.0.11 has been release a few weeks back:
https://www.mail-archive.com/dev@cassandra.apache.org/msg10707.html

**Comment by evgeny-pasynkov** [comment]
Meanwhile 3.0.12 is released

**Comment by ealonsodb** [comment]
Hi @cooldoger: 

Could you please open the same PR against stratio/cassandra-lucene-index:**branch.3.0.11**?
