### ISSUE TITLE
grouping searches with partition key ?

### ISSUE THREAD

**Issue by navidkaeni** [Stratio/cassandra-lucene-index#295]
hi
we want to know if its possible to grouping search results by partition key
for example fuzzy searches that match in same partition key has highest position in results 
thank you

**Comment by ealonsodb** [comment]
Hi @navidkaeni: 

I dont understand your question

Do you want to GROUP BY  the results or SORTING. 

Can you show us an example of your use case?

**Comment by navidkaeni** [comment]
CREATE KEYSPACE test with replication = {'class':'SimpleStrategy', 'replication_factor': 1};
use test;
CREATE TABLE metaitem (
    id UUID ,
  path text,
    value text,
PRIMARY KEY(id,path)
   );
CREATE CUSTOM INDEX metaitem_index ON metaitem ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds': '1',
   'schema': '{
    analyzers: {
         p1: {
            type: "classpath",
            class: "org.apache.lucene.analysis.fa.PersianAnalyzer"
         }
      },
      fields: {
         id: {type: "uuid"},
	     "path":{type:"text"},
		 "value":{type:"text",analyzer :"p1"}
      }
   }'
};
INSERT INTO metaitem JSON
'{"id":"88bff2ee-01a5-41f5-9189-cccccccccccc","path": "user_name", "value": "navid"}';       
INSERT INTO metaitem JSON
'{"id":"88bff2ee-01a5-41f5-9189-cccccccccccc","path": "user_Lname", "value": "gholi"}';   
INSERT INTO metaitem JSON
'{"id":"88bff2ee-01a5-41f5-9189-e5edc912196b","path": "user_name", "value": "navid"}';       
INSERT INTO metaitem JSON
'{"id":"88bff2ee-01a5-41f5-9189-e5edc912196b","path": "user_Lname", "value": "kaeni"}';       


SELECT * FROM metaitem WHERE expr(metaitem_index ,'{
          filter: {
               type: "boolean",
should:[ {
               type: "fuzzy",
               field: "value",
         value: "nav"
         }, {
               type: "fuzzy",
               field: "value",
         value: "kae"
         }]
               }
         }');
we want to see "88bff2ee-01a5-41f5-9189-e5edc912196b" higher than "88bff2ee-01a5-41f5-9189-cccccccccccc" in our "or" filter because in first partition key we have two match result and in other we have one match

**Comment by navidkaeni** [comment]
waiting ?

**Comment by ealonsodb** [comment]
Hi @ navidkaeni: 

This functionality at partition key level is not posible. 


It is posible to execute [sorted by relevance "queries"](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#searching) (order by result query relevance).

Also it is posible to set different [weights](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#searching) to queries, called 'boost', to select which part of your lucene boolean query results higher. But all of this is at primary key level.

This is an easy task to code on client side. Do you think so?
Hope this helps

**Comment by navidkaeni** [comment]
Hi @ealonsodb 
i see lucene example
`Analyzer analyzer = new StandardAnalyzer();

    // Store the index in memory:
    Directory directory = new RAMDirectory();
    // To store an index on disk, use this instead:
    //Directory directory = FSDirectory.open("/tmp/testindex");
    IndexWriterConfig config = new IndexWriterConfig(analyzer);
    IndexWriter iwriter = new IndexWriter(directory, config);
    Document doc = new Document();
    String text = "This is the text to be indexed.";
    doc.add(new Field("fieldname", text, TextField.TYPE_STORED));
    iwriter.addDocument(doc);
    iwriter.close();
    
    // Now search the index:
    DirectoryReader ireader = DirectoryReader.open(directory);
    IndexSearcher isearcher = new IndexSearcher(ireader);
    // Parse a simple query that searches for "text":
    QueryParser parser = new QueryParser("fieldname", analyzer);
    Query query = parser.parse("text");
    ScoreDoc[] hits = isearcher.search(query, null, 1000).scoreDocs;
    assertEquals(1, hits.length);
    // Iterate through the results:
    for (int i = 0; i < hits.length; i++) {
      Document hitDoc = isearcher.doc(hits[i].doc);
      assertEquals("This is the text to be indexed.", hitDoc.get("fieldname"));
    }
    ireader.close();
    directory.close();`
i need to map my partition key (id) to doc id and the other part of primary key (path) to field and my value (value) to field value in lucene then i dont need any group by 
how do you map cassandra columns to lucene indexes ?
is it possible to have this map with your implementation ?

thank you.

**Comment by ealonsodb** [comment]
Hi, as i have said, that is not posible. 

We include the PRIMARY KEY as the document id([partition_key in skinny tables](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.12/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexServiceSkinny.scala#L68) and [partition_key plus clustering_key(s) in wide tables](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.12/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexServiceWide.scala#L91)), a well known field (the mapper name), and the corresponding value in value.

When executing queries against lucene you need to know the "field" (see [FuzzyQuery](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.12/plugin/src/main/java/com/stratio/cassandra/lucene/search/condition/FuzzyCondition.java#L144-L145))

How do you know the clustering key of that query afected rows before executing the query? Please tell me. 
Regards
