### ISSUE TITLE
Spark connector error: object stratio is not a member of package com

### ISSUE THREAD

**Issue by nyitzkj1992** [Stratio/cassandra-lucene-index#296]
Hi there,

I was able to install the Plugin and use it well in Cassandra.

However, when I want to use it in Spark, It generates the following error when I want to 'import com.stratio.cassandra.lucene.search.SearchBuilders._'

Is there any package I need to use through Spark-shell ?

Can some one help me?

Thank you!

![capture](https://cloud.githubusercontent.com/assets/26145046/23819870/e0f9fa20-05da-11e7-9079-07ec90a2ae55.JPG)

**Comment by ealonsodb** [comment]
Hi @nyitzkj1992: 

I think you are looking for examples in [cassandra-lucene-index-examples](https://github.com/stratio/cassandra-lucene-index-examples). 

The master branch in that project is using a very old [cassandra lucene index:2.1.9.0](https://github.com/Stratio/cassandra-lucene-index-examples/blob/master/pom.xml#L21)

In [cassandra-lucene-index:2.2.3.0] we [split query builder](https://github.com/Stratio/cassandra-lucene-index/commit/750442fa36d49a36ecb39018929212986fcf7c88) from plugin jar to not force clients to have a dependency to plugin if not needed.


We have updated [cassandra-lucene-index-examples](https://github.com/stratio/cassandra-lucene-index-examples) with a 3.0.10.3 branch that shows you how to do it. 

As you can [see](https://github.com/Stratio/cassandra-lucene-index-examples/blob/3.0.10.3/pom.xml#L20), now clients using query builder only depends on cassandra-lucene-index-builder, not on cassandra-lucene-index-plugin any more.

Hope this helps

**Comment by ealonsodb** [comment]
Hi @nyitzkj1992: 

Did this solvbe your issue? Could you please close this ?
