### ISSUE TITLE
LockObtainFailedException after node crash, unable to restart cassandra

### ISSUE THREAD

**Issue by rahuljayz** [Stratio/cassandra-lucene-index#297]
as part of test, we shut down a few nodes and it resulted in:

 Initialization of Lucene FS directory for index 'abc_events_idx' has failed
org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /.../index_events/write.lock

I tried deleting the write.lock file and restarting but that does not work as the write.lock file is recreated. Also, tried deleting the whole index folder, doesn't work.

1) How to restart cassandra server now?
2) How to ensure that when a node goes down and comes back up, it does not require recreating lucene indexes? if it does, is there a way to recreate indexes automatically when the node comes back up?

**Comment by ealonsodb** [comment]
Hi @rahuljayz:

I will try to reproduce it.

Could you please tell me your versions(cassandra and cassandra-lucene-index)?
Can you tell me how do you shut down some nodes? 
when Does this error happens? when you shut down the nodes?
Does this error only happens in shut down nodes, or in all the cluster?

**Comment by rahuljayz** [comment]
Hi Eduardo,

One correction: we crashed all nodes, not just a few

cassandra version: 3.9
cassandra-lucene-index: 3.9.6
crashed all the nodes, forcefully shut down
error happens when we try to restart the cassandra servers, in all the nodes of the cluster

Update: I was able to restart by following these steps:

1) remove commit logs
2) remove .db files from cassandra data
3) restart all nodes
4) drop and recreate indexes

Steps 1) and 2) mean we lost some data.

**Comment by ealonsodb** [comment]
hI @rahuljayz: 

Lucene creates a write.lock when it starts and remove when shut down(correctly), just to prevent more that one instance to access the same files. 

It always create this file when it starts. 
Could you please perform these steps and show us your results?.

ou have a cassandra running cluster of 10 machines.
You kill -9 the cassandra process in 3 machines.
You delete every write.lock inside lucene directories.
You start cassandra.

Does the error happen?

**Comment by ealonsodb** [comment]
Hi @rahuljayz 
Did you solve the issue? Can you close this?
