### ISSUE TITLE
Contains query

### ISSUE THREAD

**Issue by craveica** [Stratio/cassandra-lucene-index#3]
Using stop words with "Contains query" will throw:
InvalidRequest: code=2200 [Invalid query] message="Value discarded by analyzer"

Shouldn't stop words be discarded without any errors? Or is it intended?

Eg:
```
...
analyzers : {
              my_custom_analyzer : {
                  type:"snowball",
                  language:"Spanish",
                  stopwords : "el,la,lo,loas,las,a,ante,bajo,cabe,con,contra"
              }
},
...

SELECT * FROM <table> WHERE stratio_col='{ query : { type : "contains", "field : "<field>", values : [ "el", "<other_non_stop_word_term>" ]  }  }';

InvalidRequest: code=2200 [Invalid query] message="Value discarded by analyzer"
```

**Comment by adelapena** [comment]
This kind of query was created as syntactic sugar for a boolean query with multiple match queries in the ``must`` clause. If we force "contains query" ignore failing values then, using the same reasoning, boolean queries would ignore failing predicates, don't you think so? Moreover, failing on match queries composed by stopwords exclusively is probably a bad idea and it would be preferable to simply return no results. What do you think?

**Comment by craveica** [comment]
That makes sense. However, I did not expect a query to fail.

**Comment by adelapena** [comment]
I think you are right, I'm going to change the behavior to skip this kind of errors. This behavior will be present in the next release. Thanks!
