### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by craveica** [Stratio/cassandra-lucene-index#30]
1. Can you include an upgrading advice (general and per release)?
2. Is it possible to retrieve index schema?

**Comment by adelapena** [comment]
Hi,

1. In general, most releases need to drop the index, stop the Cassandra node, replace the old plugin JAR by the new one, start the node and create the index again. However, some versions are compatible with the previous ones, we will publish a compatibility matrix ASAP.

2. Schema and other index options are stored by Cassandra in ``system`` keyspace, you can retrieve them with this CQL query:
```
SELECT index_options 
FROM system.schema_columns 
WHERE keyspace_name = '<my_indexed_keyspace>' 
AND columnfamily_name = '<my_indexed_table>' 
AND column_name = '<my_indexed_column>';
```

**Comment by craveica** [comment]
Thanks. Can you add how to retrieve index options to documentation?
