### ISSUE TITLE
Missing words

### ISSUE THREAD

**Issue by didip** [Stratio/cassandra-lucene-index#300]
When using `{type: "text", analyzer: "english"}`, it looks like some kind of stopwords dictionary is being used. I am not seeing words such as `in`.

What's the alternative if I just want Lucene parser to tokenize by whitespace?

**Comment by ealonsodb** [comment]
Hi @didip: 

There are some prebuilt analyzers. These are analyzers included in maven dependency [org.apache.lucene:lucene-analyzers-common](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/plugin/pom.xml#L81-L85). 

You can see all these in [code](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/plugin/src/main/java/com/stratio/cassandra/lucene/schema/analysis/StandardAnalyzers.java). 

You can read about analyzers description in [Apache lucene analyzer documentation](https://lucene.apache.org/core/5_5_3/core/org/apache/lucene/analysis/package-summary.html#package_description)

You only need to use the "whitespace" analyzer `{type: "text", analyzer: "whitespace"}`

I have discovered that these analyzers are not included in documentation. I will add

**Comment by didip** [comment]
Awesome! Thank you for the detailed reply. Having the analyzers documented would be super nice :)
