### ISSUE TITLE
Performance Requirement

### ISSUE THREAD

**Issue by SeenaLibin** [Stratio/cassandra-lucene-index#303]
Hi,
This is not an issue. I just want a suggestion. What is the minimum RAM size and other system requirements to run lucene query on apache cassandra 2.2.4 with good performance

We are working on 3 node cassandra cluster with RF=2 and we have near 50 lakhs records occupying 15GB space. 
Can you please suggest the requirements?

**Comment by ealonsodb** [comment]
Hi @SeenaLibin: 
I am sorry but we cannot agree in what is good performance. 

- Does a 100 millis query duration enough?

- Also, a cassandra cluster performance not only depends on RAM. Does a pentium 4 and 32GB of ram work better than a i7 with 16 GB of ram?

- A system good performance depends also on your specific use cases, indexed column values cardinality, mapper types, query types.  Do you need fast writes or fast reads or both?  

What we recommend is to generate a stress test as close as posible to your real system(size, indexes columns cardinality, concurrent client number) and test with different configurations. 

¿Are 50 lakhs equal to 5 million of rows? 
Hope this helps
