### ISSUE TITLE
Unable to find custom indexer class 'com.stratio.cassandra.lucene.Index'

### ISSUE THREAD

**Issue by SeenaLibin** [Stratio/cassandra-lucene-index#304]
I am using apache-cassandra-3.0.10. I have placed cassandra lucene jar with version 3.0.10.3 in cassandra lib folder. When i am trying to create lucene index it is showing the message Unable to find custom indexer class 'com.stratio.cassandra.lucene.Index'. As per the lucene documentation 3.0.10 jar is compatible with cassandra version 3.0.10. Then why this error is occuring. Can you help me out of this please?

**Comment by mkrup** [comment]
I faced the same issue. Looks like it's related to https://github.com/Stratio/cassandra-lucene-index/issues/279.
The jar looks broken.

**Comment by ealonsodb** [comment]
Hi @SeenaLibin and @mkrup: 

Yes, it is related to #279. Please [generate your own jar file](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.10/doc/documentation.rst#installation).

**Comment by SeenaLibin** [comment]
Hi,
I generated my own jar file and it is working. Thanks for your reply
