### ISSUE TITLE
 Unparseable JSON schema: Unrecognized field "sorted" 

### ISSUE THREAD

**Issue by ajmalsha** [Stratio/cassandra-lucene-index#305]
Hi

I am using cassandra 3.0.9 and lucene cassandra-lucene-index-plugin-3.0.9.4-RC1-SNAPSHOT.jar. But when iam running the query 
CREATE CUSTOM INDEX lucene_index_name ON table_name (lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds': '1', 'schema': '{ fields : {field1   : {type : "string"},field2 : {type : "string",sorted:"true"}}}'} it is throwing this exception

ConfigurationException: 'schema' is invalid : Unparseable JSON schema: Unrecognized field "sorted" (class com.stratio.cassandra.lucene.schema.mapping.builder.StringMapperBuilder), not marked as ignorable (3 known properties: "validated", "case_sensitive", "column"])

How can I achieve sorting for my fields

**Comment by ealonsodb** [comment]
Hi @ajmalsha: 

You should read carefully the [documentation](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.9/doc/documentation.rst). Please notice it is versioned. 

You dont need sorted paarameter in [string mapper](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.9/doc/documentation.rst#string-mapper) anymore.

Hope this helps

**Comment by ajmalsha** [comment]
Thanks
