### ISSUE TITLE
3.10.0-RC1-SNAPSHOT build broken?

### ISSUE THREAD

**Issue by djsunTB** [Stratio/cassandra-lucene-index#309]
cassandra-lucene-index/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexService.scala:282: error: not found: type ReadExecutionController

tag 3.9.6 built just fine

**Comment by ealonsodb** [comment]
Sorry, my fault, bad cassandra version.[fixed](https://github.com/Stratio/cassandra-lucene-index/commit/044836697bad7b69267fc7a4dbcf9c8106477375)

Cheers

**Comment by jchangusa** [comment]
Worked. Thx.

**Comment by djsunTB** [comment]
Worked. Thx.
