### ISSUE TITLE
Cassandra Lucene Index in Spark and Hadoop

### ISSUE THREAD

**Issue by lunkaleung** [Stratio/cassandra-lucene-index#31]
It it mentioned Cassandra Lucene Index is compatible with Spark and Hadoop. Can you please provide any spark sql or hive sql examples to create cassandra lucene index in spark and hadoop ? Thank you .

**Comment by adelapena** [comment]
Hi,

We will soon publish detailed examples about how to combine Lucene indexes with Spark. 

In the meanwhile, you can use [any existing documentation about how to use regular Cassandra secondary indexes with Spark](https://github.com/datastax/spark-cassandra-connector/blob/master/doc/3_selection.md). Lucene index plugin is just an implementation of Apache Cassandra secondary indexes, so they should be completely compatible with any existing tool able to use regular 2i.

**Comment by lunkaleung** [comment]
Thank you so much~

**Comment by adelapena** [comment]
Hi,

@ealonsodb is working in a new module containin examples about how to integrate Spark with Lucene indexes, you can take a look at the branch [feature/spark-example](https://github.com/Stratio/cassandra-lucene-index/tree/feature/spark-example).

**Comment by adelapena** [comment]
Spark examples can be found in this [separate project](https://github.com/Stratio/cassandra-lucene-index-examples/tree/master/cassandra-lucene-index-examples-spark).
