### ISSUE TITLE
Sort by date column not possible

### ISSUE THREAD

**Issue by leikingo** [Stratio/cassandra-lucene-index#313]
Using cassandra:2.2.8 with the cassandra-lucene-index-plugin-2.2.8.0.jar.

It seams that it is not possible to sort on a date column. Query on a date field works, but when I add a sort to the query I get an error: 

> Unable to execute CQL script on ...: Required positive integer for dates but found '-2147466892''))

Here the setup:
```
DROP table if exists test;
CREATE table test (
    my_id bigint,
    my_date date,
    lucene TEXT, -- needed for index search
    PRIMARY KEY(my_id)
);

DROP INDEX IF EXISTS test_index;
CREATE CUSTOM INDEX IF NOT EXISTS test_index ON test (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
	  my_date : {type : "date", pattern : "yyyy-MM-dd", sorted : true}
        }
    }'
};

insert into test (my_id, my_date) values (1234, toDate('2015-11-17'));

select * from test
WHERE lucene = '
{
 filter : {
   type  : "match",
   field : "my_date",
   value : "2015-11-17" 
 }
 ,sort  : {
   fields: [ {field:"my_date", reverse:true} ] 
 }
}'
;
```

Maybe it is related to this fixed issue [#158](https://github.com/Stratio/cassandra-lucene-index/issues/158)

**Comment by ealonsodb** [comment]
Hi @leikingo:
Yes, sorting by "date"  columns was broken in branch-2-2.x. 

We have [fix it](https://github.com/Stratio/cassandra-lucene-index/commit/19f050480e8e87b78a9373bcc014be0a3ee37357) . We have just released [2.2.9.1](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.9.1) with this patch included. 

Version branches for cassandra 3.0.x and 3.x do not suffer this bug but we have included the [Issue313AT](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.13/testsAT/src/test/java/com/stratio/cassandra/lucene/testsAT/issues/Issue313IT.java) to check it.

Also, dont use 'toDate' function. Just insert it as a string. 
```
insert into test (my_id, my_date) values (1234, '2015-11-17');
```

Thank you @leikingo for reporting. 

PD: Please check that we have resolved it correctly, and please close this issue.

**Comment by leikingo** [comment]
Hi @ealonsodb !

Thanks for the quick response. 

I've just successfully tried the updated version! Awesome, great work! Also thanks for the `toDate` hint.

**Comment by ealonsodb** [comment]
Your welcome @leikingo
