### ISSUE TITLE
Fuzzy search in Chinese

### ISSUE THREAD

**Issue by polyu-lsgi-xiaofei** [Stratio/cassandra-lucene-index#314]
You applied the _StandardAnalyzer_ for Chinese search right?  I found it is impossible to do the fuzzy search for Chinese characters using this plugin.  Is there any solution for this problem?  Thank you!

**Comment by ealonsodb** [comment]
Hi @polyu-lsgi-xiaofei 
Could you please show us the create keyspace, create index, inserts and select statement please?

**Comment by polyu-lsgi-xiaofei** [comment]
OK, I followed the official instruction in the homepage.
1. first i created the keyspace and table:
`CREATE KEYSPACE demo
WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1};
USE demo;`
`CREATE TABLE tweets (
   id INT PRIMARY KEY,
   user TEXT,
   body TEXT,
   time TIMESTAMP,
   latitude FLOAT,
   longitude FLOAT
);`

2. Then i created the custom index on tweets, I changed the analyzer to 'chinese'
`CREATE CUSTOM INDEX tweets_index ON tweets ()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds': '1',
   'schema': '{
      fields: {
         id: {type: "integer"},
         user: {type: "string"},
         body: {type: "text", analyzer: "chinese"},
         time: {type: "date", pattern: "yyyy/MM/dd"},
         place: {type: "geo_point", latitude: "latitude", longitude: "longitude"}
      }
   }'
};`

3. the i populated the table with some records like these:
`INSERT INTO tweets (id,user,body,time,latitude,longitude) VALUES ( 1,'xiao fei','I am in Beijing.','2017-04-22 09:33:38',39.9,116.16);`
`INSERT INTO tweets (id,user,body,time,latitude,longitude) VALUES ( 2,'肖飞','I am in 北京.','2017-04-21 09:33:38',39.91,116.16);`
`INSERT INTO tweets (id,user,body,time,latitude,longitude) VALUES ( 3,'肖飞','我在北京五棵松，我是一名程序员。','2017-04-22 08:33:38',39.92,116.16);`
`INSERT INTO tweets (id,user,body,time,latitude,longitude) VALUES ( 4,'肖飞','我在北京五棵松，我是一名工程师。','2017-04-22 07:33:38',39.92,116.16);`

4. At last i did the fuzzy search like below (the Chinese characters come from the _body_ column of the third insert statement above.):
`SELECT * FROM tweets WHERE expr(tweets_index , '{
   filter: {
      type: "fuzzy",
      field: "body",
      value: "我是一名程序员。",
      max_edits: 1
   }
}');`

unfortunately, i got nothing.

**Comment by ealonsodb** [comment]
Hi @polyu-lsgi-xiaofei: 

This is a missunderstanding ,fuzzy queries are not intended to use against analyzed text index. You can read more about this in #256, #80 and #65. 

You should use a [StringMapper](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.13/doc/documentation.rst#string-mapper) instead.

Hope this helps

**Comment by polyu-lsgi-xiaofei** [comment]
Dear @ealonsodb ，

Sorry for my late reply.
I have tried the Fuzzy query based on your instruction and it works!
The reason is that I applied the 'analyzer' on the column used for fuzzy query, and when I changed to StringMapper  it is OK. 

I am confused with so many conditions, i.e. phrase,match,fuzzy,wildcard,.... >_<

Thank you for your help!
