### ISSUE TITLE
artifact in Maven Central?

### ISSUE THREAD

**Issue by jsebrien** [Stratio/cassandra-lucene-index#32]
Hello,

Is it possible to upload last version (2.1.8.2) in Maven Central?

Regards,

Julien

**Comment by adelapena** [comment]
Hi,

It was uploaded [yesterday](http://search.maven.org/#artifactdetails%7Ccom.stratio.cassandra%7Ccassandra-lucene-index-plugin%7C2.1.8.2%7Cjar), the publishing process takes some time.

Regards

**Comment by jsebrien** [comment]
Ok, it is available now, thanks!
