### ISSUE TITLE
Documentation on cassandra-lucene index handling index creation on Columns with TTL

### ISSUE THREAD

**Issue by mohigup** [Stratio/cassandra-lucene-index#321]
**Type**: Question

I was not able to find details in the documentation regarding **cassandra-lucene-index** handling of Columns Values that have TTL.

- Does it remove the records from index, builds new index after TTL expires?
- How does it affect search using such an index ?

Please help.

**Comment by ealonsodb** [comment]
Hi @mohigup: 

Yes, [ttl rows are supported](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.13/doc/documentation.rst#features)

Indeed, When performing searches against a [cassandra-lucene-index](www.github.com/stratio/cassandra-lucene-index), the index performs the search, get a group of primary keys and then ask cassandra about the related data. Even if the index still contains the expired ttl row cassandra will detect the tombstone while reading the related data and you will get correct results(without that expired row). 

Cassandra, when compacting, detects that a ttl row has expired and delete it from index. This lets the index save disk. If you want to see code please look at [this commit](https://github.com/Stratio/cassandra-lucene-index/commit/72c48759aef25650270aca92ffa9b34e6b909cf9)

Hope this helps

**Comment by mohigup** [comment]
Thank You for confirming that **cassandra-lucene-index** supports auto updating/removal of records in index that have TTL

**Comment by ealonsodb** [comment]
Hi @mohigup, If resolved, could you please close this issue?

**Comment by mohigup** [comment]
👍
