### ISSUE TITLE
java.lang.NoClassDefFoundError: com/vividsolutions/jts/io/ParseException 

### ISSUE THREAD

**Issue by whedro** [Stratio/cassandra-lucene-index#324]
Hi
I have cassandra 3.7 in docker ... cassandra lucene index 3.7.7 (or I try 3.7.8.rc1 with build from git)

I try run select with polygon, but it finish with error ...
`
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /XX.XX.XX.XX:XXXX (com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on /XX.XX.XX.XX:XXXX : java.lang.NoClassDefFoundError: com/vividsolutions/jts/io/ParseException))
`
### index
```
CREATE CUSTOM INDEX hotels_index ON hotels () USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds' : '1', 'schema' : '{
        fields : {
            ...
	    "place": {type: "geo_point", latitude: "address.latitude", longitude: "address.longitude"},
           ...
         }
    }
```
### select 
(polygon have short version .... )
```
select * from hotels WHERE expr(hotels_index, '{ 
            filter: {
                type: "boolean",
                    must: [
                        {
		                type: "geo_shape",
		                field: "place",
		                shape: {
		                    type: "wkt",
		                    value: "MULTIPOLYGON(((16.957262 48.2634829, 16.957703 48.2634819, ..... )))"
		                }
                         }
                    ]                              
                }
          }'
);
```
On my dev server working correctly....
I don't know, where is the problem .... :(
Thanks for help ...

**Comment by ealonsodb** [comment]
Hi @whedro: 

Are you using cassandra 3.7 with cassandra-lucene-index 3.7.7 inside a docker written by you?

Have you putted [the JTS jar in every cassandra lib](https://github.com/Stratio/cassandra-lucene-index/blob/3.7.7/doc/documentation.rst#geo-shape-mapper) folder?

The class 'com/vividsolutions/jts/io/ParseException' is inside that jar. 

Hope this helps

**Comment by whedro** [comment]
Hi @ealonsodb 

now its ok ... 
maybe could you add this information to install section in documentation ? .. :) 

.. for next time .. :)

thanks a lot ..

**Comment by ealonsodb** [comment]
Hi @whedro: 

Do you like [this](https://github.com/Stratio/cassandra-lucene-index/pull/325/files)?

Please close this issue if solved.
Your welcome

**Comment by whedro** [comment]
yop ... exactly ... :)

good job @ealonsodb 
Thanks ..
