### ISSUE TITLE
Change cassandra download url from www.us.apache.org to something else, e.g. archive.apache.org, in plugin/pom.xml

### ISSUE THREAD

**Issue by wxr** [Stratio/cassandra-lucene-index#330]
Hi,

The command `mvn clean package -Pdownload_and_patch -Dcassandra_home=<CASSANDRA_HOME>` is very helpful. 

It worked great in the past days, however, it suddenly stopped working today. 

The reason is that the cassandra download website hardcoded in plugin/pom.xml just updated cassandra version today (i.e. removed 3.0.13 and added 3.0.14). 

As you can see from the hardcoded website `http://www.us.apache.org/dist/cassandra/`, there are only very limited versions (i.e. the latest ones) provided. 

It makes it impossible to use the download_and_patch profile for any cassandra version other than the latest one, which is 3.0.14 and has no cassandra-lucene-index support yet because it's too new. 

I suggest we change the cassandra download url from `www.us.apache.org` to something else, e.g. `archive.apache.org`, in `plugin/pom.xml`. 

`archive.apache.org` promises to never remove old versions, so it will help make sure that, no matter which cassandra version/branch a user wants to use, the download_and_patch profile always works as expected, rather than only works for the specific versions limited by `www.us.apache.org`.

Thank you for your great work!

**Comment by ealonsodb** [comment]
Hi @wxr: 
Yes, you are totally right. We have created #333. 

Very much thank you for pointing us.

**Comment by wxr** [comment]
Hi @ealonsodb 

download_and_patch worked great again. 

Thank you very much for your prompt update to solve this issue.
