### ISSUE TITLE
Build for 3.11 ?

### ISSUE THREAD

**Issue by hkroger** [Stratio/cassandra-lucene-index#331]
Hello,

now that Cassandra 3.11 is out, when would the plugin build be available for 3.11?

**Comment by ealonsodb** [comment]
ASAP

**Comment by ealonsodb** [comment]
[cassandra-lucene-index:3.11.0.0](https://github.com/Stratio/cassandra-lucene-index/tree/3.11.0.0) is out. Could you please close this issue?

Regards

**Comment by hkroger** [comment]
With pleasure!

**Comment by hkroger** [comment]
Ah, right. So there is a tag but ready but no JAR builds are publicly available.

**Comment by ealonsodb** [comment]
Hi @hkroger: 

I think we have fixed it. 
Could you please confirm?

Regards

**Comment by hkroger** [comment]
Yes, now I see also the JARs. Thanks!
