### ISSUE TITLE
increase maxClauseCount: com.datastax.driver.core.exceptions.InvalidQueryException: maxClauseCount is set to 1024

### ISSUE THREAD

**Issue by jyotsnabh** [Stratio/cassandra-lucene-index#332]
I am using lucene index for Cassandra.

```
<dependency>
        <groupId>com.stratio.cassandra</groupId>
        <artifactId>cassandra-lucene-index-builder</artifactId>
        <version>3.9.4</version>
</dependency>`

```
I am getting the following error:
`com.datastax.driver.core.exceptions.InvalidQueryException: maxClauseCount is set to 1024   `
due to too many filter conditions. 

I tried to increase the maxClauseCount by :     BooleanQuery.setMaxClauseCount(5000);
using this dependency:
 ```
<dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-core</artifactId>
            <version>6.6.0</version>
        </dependency>
```

But I was still getting the error. Am I missing something?

**Comment by ealonsodb** [comment]
Hi @jyotsnabh: 

Using a boolean query with more than 1024 clauses is risky. With such number of clauses in a Lucene boolean query, it will require a lot of memory and will loose performance. 

First of all, it is preferable to understand why your query has so much clauses and try to reduce it. 

Apart from that, we understand there are some use cases where this functionality would be great. So, we have [added 'max_clauses' to boolean search](https://github.com/Stratio/cassandra-lucene-index/pull/338). 

It will ship into the next release.
Regards
