### ISSUE TITLE
Question: Can we query on indexed collections which returns matching elements of that collection instead of the cassandra row? 

### ISSUE THREAD

**Issue by muralikg** [Stratio/cassandra-lucene-index#347]
For a table which has a colelction called tags (set of strings).
```
CREATE TABLE tweets (
   id bigint PRIMARY KEY,
   author text,
   raw_text text,
   tags list<text>
);
CREATE CUSTOM INDEX tweets_index ON tweets()
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds': '1',
   'schema': '{
      fields: {
         "tags" : {type: "string"}
      }
   }'
};
```
I am trying to implement an auto completion feature on available tags. Can I query only on `tags` which returns matching tags and not the actual tweets ?
Is there a way to do this with the existing index instead of an additional table?

**Comment by ealonsodb** [comment]
Hi @muralikg 

If i am not wrong, what you want is to search for every different tag contained in the table.

For autocompletion you should use the [prefix query](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.14/doc/documentation.rst#prefix-search)

For example, when the user has written 'cassan', you could use this query: 

```sql

SELECT tags FROM tweets 
WHERE expr(tweets_index,'{type: "prefix",field: "tags",value: "cassan"}');

```
We always recommend to not use the secondary index if it is posible with just a correct cassandra modeling . And in your use case, it is posible.

We recommend you to insert it in another table, because the tweets cardinality (number of different tweets in table ) is much greater than the number of tags(i presume).

So, that query asking for every different tag performance depends heavily on number of tweets and it may not. Number of tweets will always increase but not necessarily the number of tags. 

I think the best solution is to use our friend [Michael Laing](https://www.youtube.com/watch?v=_KOrZAC_qR8)'0 just cassandra-modeling based approach. 

Something like this:
```
CREATE KEYSPACE IF NOT EXISTS test_issue_347
WITH REPLICATION = {
  'class' : 'SimpleStrategy', 
  'replication_factor': 1
};

CREATE TABLE test_issue_347.tweets (
   id bigint PRIMARY KEY,
   author text,
   raw_text text,
   tags list<text>
);

CREATE TABLE test_issue_347.tags (
  prefix text PRIMARY KEY,
  complete_tags set<text>
);


BEGIN BATCH
    INSERT INTO test_issue_347.tweets (id, author, raw_text, tags) VALUES (0,'Clark','I am new in the city',['newbie','New_York'])

    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'newbie'} WHERE prefix = 'n';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'newbie'} WHERE prefix = 'ne';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'newbie'} WHERE prefix = 'new';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'newbie'} WHERE prefix = 'newb';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'newbie'} WHERE prefix = 'newbi';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'newbie'} WHERE prefix = 'newbie';

    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'New_York'} WHERE prefix = 'N';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'New_York'} WHERE prefix = 'Ne';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'New_York'} WHERE prefix = 'New';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'New_York'} WHERE prefix = 'New_';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'New_York'} WHERE prefix = 'New_Y';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'New_York'} WHERE prefix = 'New_Yo';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'New_York'} WHERE prefix = 'New_Yor';
    UPDATE test_issue_347.tags SET complete_tags = complete_tags + {'New_York'} WHERE prefix = 'New_York';
APPLY BATCH;

SELECT complete_tags FROM test_issue_347.tags WHERE prefix='n';
```

What do you think?

**Comment by muralikg** [comment]
That helps thanks @ealonsodb .

Just a follow up question on the table based solution. Is there a recommended way of deleting entries from `tags` table when source data (`tweets`) is deleted using a TTL ? 
I can think of setting same TTL for tags also but wanted to know if that is recommended or not

**Comment by ealonsodb** [comment]
I think there is a problem. That relation between tweets-tags is not single. What I mean, there could be more than one tweet sharing a tag. So, when you want to delete a tweet, maybe, and only maybe, you delete a tag.

I think you can use a counter table like this. 

```
CREATE TABLE test_issue_347.tweets_by_tag
  num_tweets counter,
  tag text,
  PRIMARY KEY (tag)
);
```

You need to add to previous batch insertion: 
```
UPDATE test_issue_347.tweets_by_tag
 SET num_tweets = num_tweets + 1
 WHERE tag='New_York';

UPDATE test_issue_347.tweets_by_tag
 SET num_tweets = num_tweets + 1
 WHERE tag='newbie';
```
When deleting a tweet, for each tag, you decrement its counter and if  it gets to zero, you **only** delete that tag.

This is something like this: 

```

--get the tags for that tweet
List<Row> potential_tags_to_delete = SELECT complete_tags from tweets where id = 0;
--for example ["cassandra"]

for (int i=0; i<potential_tags_to_delete.lenght;i++ ) {
	tag= potential_tags_to_delete(i);

	UPDATE test_issue_347.tweets_by_tag SET num_tweets = num_tweets -1 WHERE tag='cassandra';
	if (SELECT num_tweets FROM test_issue_347.tweets_by_tag ==0) {
		UPDATE test_issue_347.tags SET complete_tags = complete_tags - {'cassandra'} WHERE prefix = 'c';
		UPDATE test_issue_347.tags SET complete_tags = complete_tags - {'cassandra'} WHERE prefix = 'ca';
		UPDATE test_issue_347.tags SET complete_tags = complete_tags - {'cassandra'} WHERE prefix = 'cas';
		UPDATE test_issue_347.tags SET complete_tags = complete_tags - {'cassandra'} WHERE prefix = 'cass';
		UPDATE test_issue_347.tags SET complete_tags = complete_tags - {'cassandra'} WHERE prefix = 'cassa';
		UPDATE test_issue_347.tags SET complete_tags = complete_tags - {'cassandra'} WHERE prefix = 'cassan';
		UPDATE test_issue_347.tags SET complete_tags = complete_tags - {'cassandra'} WHERE prefix = 'cassand';
		UPDATE test_issue_347.tags SET complete_tags = complete_tags - {'cassandra'} WHERE prefix = 'cassandr';
		UPDATE test_issue_347.tags SET complete_tags = complete_tags - {'cassandra'} WHERE prefix = 'cassandra';
	}

}

DELETE FROM test_issue_347.tweets WHERE id=0;
```
 Please notice that this last code block may cause race conditions if two different threads execute it concurrently. It cannot be included in a single casandra batch. So , you should use [mutual exclusion](https://en.wikipedia.org/wiki/Mutual_exclusion)

Hope this helps

**Comment by muralikg** [comment]
Hey @ealonsodb  for deletes that would happen from my application I would definitely go as you explained. 

For tweets that expires through TTL(I dont need data older than a month so I add auto expiry combined with date tierred compaction) I was thinking of  setting the same TTL on tags (It is the TTL on individual element of a collection) and keep pushing that TTL forward as and when new tweets with same tags come in.

```
CREATE KEYSPACE IF NOT EXISTS test_issue_347
WITH REPLICATION = {
  'class' : 'SimpleStrategy', 
  'replication_factor': 1
};

CREATE TABLE test_issue_347.tags (
  prefix text PRIMARY KEY,
  complete_tags set<text>
);


UPDATE test_issue_347.tags USING TTL 30
SET complete_tags = complete_tags + {'cassandra'}
WHERE prefix = 'cas';

--- Again for another tweet I would do the same (tags is now a SET and not LIST)
--- Effectively postponing the expiry 
UPDATE test_issue_347.tags USING TTL 30
SET complete_tags = complete_tags + {'cassandra'}
WHERE prefix = 'cas';
```

This way I can let compaction cleanup the expired entries. But I am not sure of the performance implications of the tombstones added during expiry. But I am guessing it should be fine as long as my data cardinality is low.

Thanks a lot for the help
-Murali

**Comment by ealonsodb** [comment]
Hi @muralikg: 

So, you renew your complete system data every month. When TTL expires, a tombstone is generated and you will see it there for  **gc_grace_seconds**.  There are some [tombstones limit warnings](https://github.com/apache/cassandra/blob/trunk/conf/cassandra.yaml#L1049) you should be aware of.


Your approach with TTL is correct for me if and only if every tweet has a TTL.  

Just for other use cases, it would be interesting to use cassandra [change data capture](http://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/configCDCLogging.html) functionality. This would let you detect data changes and act over other tables accordingly. This is great for building an asynchronous synchronizing approach over it.

Your very welcome
