### ISSUE TITLE
Select with limit and sort

### ISSUE THREAD

**Issue by whedro** [Stratio/cassandra-lucene-index#353]
Hi, 

I use cassandra 3.7.... and i have problem with sort and limit in query.

When I use select query like this:
```
SELECT * FROM reservations WHERE expr(reservations_index,'
{"filter":
	{"type":"boolean",
		"must":[
			{"type":"contains","field":"services.room","values":[1,2,3,4,5,6,33,34,86,87,83,84,85,116,117]}
		]
	},
	"sort":{"fields":
		[
			{"field":"reservationdate","reverse":true}
		]
	}
}') limit 10000
```
, so this finish with error:
```
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /XXXX:XXX (com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on /XXXX:XXX: java.lang.ArrayIndexOutOfBoundsException))
```
When I remote `sort` part from select, result is OK ... 
**Note:** Table have less rows as is in limit ... When is limit less as rows in table, result is OK.
*(Table rows: 300, used limit 10000)*

Cassandra version: 3.7
Thrift API version: 20.1.0
CQL supported versions: 3.4.2 (default: 3.4.2)
Lucene Index:  cassandra-lucene-index-plugin-3.7.7.jar 
Other:  jts-core-1.14.0.jar

**Comment by jpgilaberte** [comment]
Hi @whedro,

Is this issue similar (Schema, UDT, etc ...) to the [192](https://github.com/Stratio/cassandra-lucene-index/issues/192) ? 

I tried playing the scenario but I am not able to reproduce the error. Ordered searches with occurrence limits above the number of results works correctly.

Please:

Can you provide me with some example INSERT with data?

Has the query worked at any time?

Thanks,

**Comment by whedro** [comment]
@jpgilaberte-stratio 
Hi, thanks for answer ... I forgot on this issue, but It is possible ... I deleted table content before your reaction ... and now I waiting if any process generate invalid row or if the problem generate something else.
