### ISSUE TITLE
Sometimes Lucene index is not updated within reasonable time

### ISSUE THREAD

**Issue by didip** [Stratio/cassandra-lucene-index#355]
Observed in Cassandra 3.7 and it's respective plugin.

After some writes happened, search query does not show the new results even after waiting for half hour. We are using glob '*' query on id.

I don't see anything in the log that could possible be related to this problem. I have turned on the lucene logging on `error` in `logback.xml`.

```
CREATE TABLE my_ks.my_table (
    id text PRIMARY KEY,
    app text,
    chunks text,
    dc text,
    suffix text,
    updated bigint
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX idx_my_table ON my_ks.my_table () USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds': '120', 'max_merge_mb': '20', 'ram_buffer_mb': '256', 'max_cached_mb': '1024', 'schema': '{
    fields: {
      id: {type: "string"},
      app: {type: "string"},
      dc: {type: "string"},
      chunks: {type: "text", analyzer: "english"},
      updated: {type: "bigint"}
    }
  }'};
```

`my_ks` has replication factory of 5. All inserts/updates are `LOCAL_QUORUM`, all reads are `LOCAL_ONE`.

The data size is about 15 million rows. Not too large.

The one workaround we have that always works is to perform `nodetool rebuild_index`.

I'm not sure how to debug this further. Any Lucene options I am missing?

**Comment by jpgilaberte** [comment]
Hi @didip,

Thank you for your interest in the project.

I think the configuration is correct. Please,

Can you show me how you do the query, how do you generate the keyspace and some inserts with false data?

Can you tell me the ratio of inserts and queries?

Thanks

**Comment by didip** [comment]
Hi all,

I am so sorry for the really delayed response.

We think we found our issue, indices weren't updated when mutation dropped count is really high.

After adjusting write threads and memtable size, we have not been encountering this problem anymore.

Thank you again for your time.
