### ISSUE TITLE
Typo in Stratio's Cassandra Lucene Index documentation

### ISSUE THREAD

**Issue by RettPop** [Stratio/cassandra-lucene-index#358]
> Lucene makes a huge use of caching, so the first query done to an index will be **_specially_** slow **_dou_** to the cost of initializing caches. 

It looks like **_selected_** words are mistyped. "Specifically" and "due" perhaps should be used instead.

**Comment by RettPop** [comment]
Also, it seems that the same description is used for two opposite attributes in https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.14/doc/documentation.rst#jmx-interface:


Name | Type | Notes
-- | -- | --
NumDeletedDocs | Attribute | **_Total number of documents in the index._**
NumDocs | Attribute | **_Total number of documents in the index._**

**Comment by jpgilaberte** [comment]
Hi @RettPop,

Thank you for your interest in the project.

Let's review concepts and misspelled words.

Regards

**Comment by ealonsodb** [comment]
Fixed in #374
