### ISSUE TITLE
Is lucene-plugin abandoned by Stratio?

### ISSUE THREAD

**Issue by hkroger** [Stratio/cassandra-lucene-index#373]
Hi,

I haven't seen a code update in this repository since July. Is this project abandoned by Stratio?

Cheers.
Hannu

**Comment by hkroger** [comment]
Stratio is saying in Twitter that it's not fully abandoned. Waiting for further news:
https://twitter.com/hkroger/status/942692791502692352

**Comment by ealonsodb** [comment]
No, it isnt. We have paused due to personal problems but i am back right now.
