### ISSUE TITLE
Cassandra warns for multiple logback.xml 

### ISSUE THREAD

**Issue by masumsoft** [Stratio/cassandra-lucene-index#38]
I get this warning after adding lucene index jar file into cassandra lib directory:

19:48:03,074 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
19:48:03,074 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/cassandra/lib/cassandra-lucene-index-plugin-2.1.8.4.jar!/logback.xml]
19:48:03,074 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/cassandra/conf/logback.xml]

**Comment by adelapena** [comment]
I have just removed the file ``logback.xml`` from [branch 2.1.8](https://github.com/Stratio/cassandra-lucene-index/tree/branch-2.1.8).
