### ISSUE TITLE
Match and Phrase behavior problem (compared to stratio-cassandra)

### ISSUE THREAD

**Issue by adejanovski** [Stratio/cassandra-lucene-index#4]
Switching from stratio-cassandra 2.1.5 to a bare C* 2.1.6 with the cassandra-lucene-index plugin (compiled today) shows inconsistencies on Match, Phrase and Fuzzy queries, that seem to behave differently than expected in the plugin.

Match and phrase seem to have switched from single word search to sentence search, which prevents using them to search for a single word or a group of words in a string (and leaving wildcard for that, which is not as fast).

### Wildcard

Seems to work fine, but gives a real slowdown compared to match/phrase/fuzzy : 

```
select ref_expediteur, adresse_1_destinataire 
from vision_dev.lt 
where lucene = '
            {filter : {type:"range", field:"date_depot_lt", lower:"2015-01-25", upper:"2015-04-01"},  
             query  :  {type:"wildcard", field:"adresse_1_destinataire", value:"*DANIEL*COGNAC*"}}';
```

I get the following 7 rows : 

```
 ref_expediteur | adresse_1_destinataire
----------------+-------------------------
       95762968 | 15 RUE DANIEL DE COGNAC
       89162952 | 15 RUE DANIEL DE COGNAC
       94262880 | 15 RUE DANIEL DE COGNAC
       95823340 | 15 RUE DANIEL DE COGNAC
       95162706 | 15 RUE DANIEL DE COGNAC
       95042969 | 15 RUE DANIEL DE COGNAC
       94443320 | 15 RUE DANIEL DE COGNAC
```

### Fuzzy

If I use the following query : 

```
select ref_expediteur, adresse_1_destinataire 
from vision_dev.lt 
where lucene = '
            {filter : {type:"range", field:"date_depot_lt", lower:"2015-01-25", upper:"2015-04-01"},  
             query  :  {type:"fuzzy", field:"adresse_1_destinataire", value:"15 RUE DANIEL DECOGNAC"}}';
```

I get the following 8 rows : 

```
 ref_expediteur | adresse_1_destinataire
----------------+-------------------------
       94262880 | 15 RUE DANIEL DE COGNAC
       95042969 | 15 RUE DANIEL DE COGNAC
     RI36692335 | 15 RUE DANIEL DE COSNAC
       95762968 | 15 RUE DANIEL DE COGNAC
       89162952 | 15 RUE DANIEL DE COGNAC
       95823340 | 15 RUE DANIEL DE COGNAC
       95162706 | 15 RUE DANIEL DE COGNAC
       94443320 | 15 RUE DANIEL DE COGNAC

```

This seems like a reasonable result.
Than if we differ a bit more from the "real" string :

```
select ref_expediteur, adresse_1_destinataire 
from vision_dev.lt 
where lucene = '
            {filter : {type:"range", field:"date_depot_lt", lower:"2015-01-25", upper:"2015-04-01"},  
             query  :  {type:"fuzzy", field:"adresse_1_destinataire", value:"15 RUE DANIEL COGNAC"}}';
```

Then we get no match at all (0 rows).
This could be related to me misunderstanding the accuracy needed for fuzzy to return results.

### MATCH

Using the same dataset, we can use match to get results providing the full string (exactly as stored) : 

```
select ref_expediteur, adresse_1_destinataire 
from vision_dev.lt 
where lucene = '
            {filter : {type:"range", field:"date_depot_lt", lower:"2015-01-25", upper:"2015-04-01"},  
             query  :  {type:"match", field:"adresse_1_destinataire", value:"15 RUE DANIEL DE COGNAC"}}';
```

returns 7 rows : 

```
 ref_expediteur | adresse_1_destinataire
----------------+-------------------------
       95762968 | 15 RUE DANIEL DE COGNAC
       89162952 | 15 RUE DANIEL DE COGNAC
       94262880 | 15 RUE DANIEL DE COGNAC
       95823340 | 15 RUE DANIEL DE COGNAC
       95162706 | 15 RUE DANIEL DE COGNAC
       95042969 | 15 RUE DANIEL DE COGNAC
       94443320 | 15 RUE DANIEL DE COGNAC
```

Previously, this didn't work since "match" didn't allowed multiple words at once.

Now if I restrict the match to a single word : 

```
select ref_expediteur, adresse_1_destinataire 
from vision_dev.lt 
where lucene = '
            {filter : {type:"range", field:"date_depot_lt", lower:"2015-01-25", upper:"2015-04-01"},  
             query  :  {type:"match", field:"adresse_1_destinataire", value:"COGNAC"}}';
```

Then I get no result at all.
Shouldn't it return all rows containing the word "COGNAC" in it ?

### PHRASE

Phrase gets it right, like match does, when the full string is searched as stored : 

```
select ref_expediteur, adresse_1_destinataire 
from vision_dev.lt 
where lucene = '
            {filter : {type:"range", field:"date_depot_lt", lower:"2015-01-25", upper:"2015-04-01"},  
             query  :  {type:"phrase", field:"adresse_1_destinataire", value:"15 RUE DANIEL DE COGNAC"}}';
```

returns 7 rows : 

```
 ref_expediteur | adresse_1_destinataire
----------------+-------------------------
       95762968 | 15 RUE DANIEL DE COGNAC
       89162952 | 15 RUE DANIEL DE COGNAC
       94262880 | 15 RUE DANIEL DE COGNAC
       95823340 | 15 RUE DANIEL DE COGNAC
       95162706 | 15 RUE DANIEL DE COGNAC
       95042969 | 15 RUE DANIEL DE COGNAC
       94443320 | 15 RUE DANIEL DE COGNAC
```

But if I try to skip a word like "DE" and set slop like this : 

```
select ref_expediteur, adresse_1_destinataire 
from vision_dev.lt 
where lucene = '
            {filter : {type:"range", field:"date_depot_lt", lower:"2015-01-25", upper:"2015-04-01"},  
             query  :  {type:"phrase", field:"adresse_1_destinataire", value:"15 RUE DANIEL COGNAC", slop:2}}';
```

Once again I get no results.

Here's the create statement for the index : 

```
CREATE CUSTOM INDEX lt_lucene_index ON vision_dev.lt (lucene) 
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds' : '10',
   'schema' : '{
       fields : {
           adresse_1_destinataire : {type : "string"},
           adresse_1_expediteur : {type : "string"},
           adresse_2_destinataire : {type : "string"},
           adresse_2_expediteur : {type : "string"},
           date_depot_lt : {type : "date", pattern : "yyyy-MM-dd"}
       }
   }'
};
```

Am I misunderstanding something ?

**Comment by adelapena** [comment]
Hi,

I think that most of the problems are because you are using a ``string`` mapper for ``adresse_1_destinataire`` column. This kind of mapper uses a [KeywordAnalyzer](https://lucene.apache.org/core/5_1_0/analyzers-common/org/apache/lucene/analysis/core/KeywordAnalyzer.html) that generates a single token per column value. Maybe using a ``text`` mapper with a language aware analyzer would be more appropriate:
```
CREATE CUSTOM INDEX lt_lucene_index ON vision_dev.lt (lucene) 
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds' : '10',
   'schema' : '{
       fields : {
           adresse_1_destinataire : {type:"text", analyzer:"french"},
           adresse_1_expediteur : {type:"text", analyzer:"french"},
           adresse_2_destinataire : {type:"text", analyzer:"french"},
           adresse_2_expediteur : {type:"text", analyzer:"french"},
           date_depot_lt : {type : "date", pattern : "yyyy-MM-dd"}
       }
   }'
};
```
Let's go through your example using ``string`` mapper:
Fuzzy
-----
Fuzzy queries allows [specifying the number of max allowed editions](https://github.com/Stratio/cassandra-lucene-index/blob/branch-2.1.6/doc/extended-search-in-cassandra.md#fuzzy-query). This value, due to Lucene limitations, can't be greater than 2, which is also the default value. The query:
```
select ref_expediteur, adresse_1_destinataire 
from vision_dev.lt 
where lucene = '
            {filter : {type:"range", field:"date_depot_lt", lower:"2015-01-25", upper:"2015-04-01"},  
             query  :  {type:"fuzzy", field:"adresse_1_destinataire", value:"15 RUE DANIEL COGNAC"}}';
```
contains 3 editions (3 deleted characters) so no row is matched. A max of 2 editions could seem a strong limitation, but it seems to be enough when dealing with tokenized text, which is the common use case of fuzzy queries.
Match
-----
Match queries find exact token matches. The query
```
select ref_expediteur, adresse_1_destinataire 
from vision_dev.lt 
where lucene = '
            {filter : {type:"range", field:"date_depot_lt", lower:"2015-01-25", upper:"2015-04-01"},  
             query  :  {type:"match", field:"adresse_1_destinataire", value:"COGNAC"}}';
```
does not return results because the column value ``15 RUE DANIEL DE COGNAC`` has been translated to a single token by the analyzer. However, if you had used the french analyzer, then the text would have been translated to the tokens ``15``,``rue``,``daniel``and ``cognac`` and you would have found results.
Phrase
------
The same thing happens with the phrase query:
```
select ref_expediteur, adresse_1_destinataire 
from vision_dev.lt 
where lucene = '
            {filter : {type:"range", field:"date_depot_lt", lower:"2015-01-25", upper:"2015-04-01"},  
             query  :  {type:"phrase", field:"adresse_1_destinataire", value:"15 RUE DANIEL COGNAC", slop:2}}';
```
The text is not tokenized and the purposed phrase query is trying to find rows/documents with the tokens ``15``,``rue``,``daniel``and ``cognac`` whereas all the rows contain the single token ``15 RUE DANIEL DE COGNAC``.

I hope you find it useful.

**Comment by adejanovski** [comment]
I totally missed the distinction between "string" and "text" in the index definition.
It works perfectly now !!

This project is a wonderful addon to Cassandra, which is so painful for building search engines, and now that the fork is not necessary anymore, it is way more convenient.

Thank you very much !

**Comment by Hervian** [comment]
@adejanovski 
Can you share your solution (index creation statement + query)?
I am trying to use the plugin to create an address autocomplete function, but my fuzzy search does not work as expected.
