### ISSUE TITLE
OperationTimedOut when sorting on TEXT data

### ISSUE THREAD

**Issue by karlbunnell** [Stratio/cassandra-lucene-index#40]
Cassandra version (running on Ubuntu 14.04): Cassandra 2.1.8
cassandra-lucene-index: cassandra-lucene-index-plugin-2.1.8.1.jar

Simple to reproduce. I use the example schema:

CREATE KEYSPACE demo
WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};
USE demo;
CREATE TABLE tweets (
    id INT PRIMARY KEY,
    user TEXT,
    body TEXT,
    time TIMESTAMP,
    latitude FLOAT,
    longitude FLOAT,
    lucene TEXT
);

CREATE CUSTOM INDEX tweets_index ON tweets (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            id    : {type : "integer"},
            user  : {type : "string"},
            body  : {type : "text", analyzer : "english"},
            time  : {type : "date", pattern : "yyyy/MM/dd", sorted : true},
            place : {type : "geo_point", latitude:"latitude", longitude:"longitude"}
        }
    }'
};

Insert some data: 

INSERT INTO demo.tweets ( id, body, latitude, longitude, time, user ) VALUES (21, 'Utah is a great state', 79.13032, 67.2017, 1440780495620, 'Kenny');
INSERT INTO demo.tweets ( id, body, latitude, longitude, time, user ) VALUES (22, 'Indiana is a great state', 79.13232, 67.2727, 1440780995620, 'Andrea');

Then use the following query as a sanity check:

SELECT * FROM tweets WHERE lucene='{
    query  : {
              type:"phrase", 
              field:"body", 
              value: "is a great state"}
}';

 id | body                     | latitude | longitude | lucene | time                     | user
----+--------------------------+----------+-----------+--------+--------------------------+--------
 22 | Indiana is a great state | 79.13232 |   67.2727 |    1.0 | 2015-08-28 16:56:35+0000 | Andrea
 21 |    Utah is a great state | 79.13032 |   67.2017 |    1.0 | 2015-08-28 16:48:15+0000 |  Kenny

Now try the following:

SELECT * FROM tweets WHERE lucene='{
    query  : {
              type:"phrase", 
              field:"body", 
              value: "is a great state"},
   sort : 
   {
     fields: [ {field : "user", reverse : true} ] 
   }
}';

You'll get the following:
OperationTimedOut: errors={}, last_host=x.x.x.x

If this is a legitimate timeout on two rows of data we are in trouble. ;)

If I sort on numeric fields I get back an immediate response. The problem only manifests itself with TEXT fields.

**Comment by adelapena** [comment]
This bug [was fixed some days ago](https://github.com/Stratio/cassandra-lucene-index/commit/465cbcc8ba4bb9b55e8f0c2da5cdceed5516379f). The changes were included in last release, [2.1.8.4](https://github.com/Stratio/cassandra-lucene-index/tree/2.1.8.4).

**Comment by karlbunnell** [comment]
Confirmed this is fixed in build 2.1.8.4 and after. 
Thanks
