### ISSUE TITLE
Supporting Cassandra stable releases

### ISSUE THREAD

**Issue by masumsoft** [Stratio/cassandra-lucene-index#41]
I just wanted to know what the roadmap plans are for supporting cassandra releases. I see there is an active branch for latest cassandra 2.2 support for this plugin. While cassandra 2.1.9 has also been released, is there any plan to also release a 2.1.9 supporting version of this plugin? 

Will there be two separate releases supporting the latest vs the stable version of cassandra? Will the existing 2.1.8 release of this plugin also work properly with cassandra 2.1.9?

**Comment by adelapena** [comment]
Hi,

The idea is to provide support for Apache Cassandra stable versions, 2.1.9 will be available in no more than a couple of days.

Some latest versions will be available when possible and interesting, as is the case of 2.2, which was [kindly updated by Andreas Petter](https://github.com/Stratio/cassandra-lucene-index/issues/29).
