### ISSUE TITLE
When will support for TTL columns be added?

### ISSUE THREAD

**Issue by karlbunnell** [Stratio/cassandra-lucene-index#42]
Any word on when support for TTL columns will be added?

**Comment by adelapena** [comment]
Hi,

This week we will be working in [our presentation for Cassandra Summit](http://cassandrasummit-datastax.com/agenda/geospatial-and-bitemporal-search-in-cassandra-with-pluggable-lucene-index/). Cassandra 3.0 is supposed [to be released during the summit](http://www.planetcassandra.org/blog/cassandra-2-2-3-0-and-beyond/). It will come with [a lot of changes](https://issues.apache.org/jira/browse/CASSANDRA-9459), so we will need some time to upgrade the indexes, at least a couple of weeks. After that, we could start working on the TTL feature.

**Comment by karlbunnell** [comment]
Thanks for the response. I'll look for this feature in a future release post Cassandra 3.0.
