### ISSUE TITLE
SELECT COUNT statement return result twice

### ISSUE THREAD

**Issue by Evangileon** [Stratio/cassandra-lucene-index#43]
When I executed the CQL below, I got two lines of result
```
fred@cqlsh:opensignal> SELECT COUNT(*) FROM os_snapshot2 WHERE ts = 0 and network_name_mapped = 'Verizon' and network_type_mapped = '4' and lucene = '{ filter : {type:"boolean", must:[ {type:"geo_bbox",  field:"place", min_latitude: 25, max_latitude: 26, min_longitude: -100, max_longitude: -97} ]} }';

 count
-------
   100

---MORE---
 count
-------
    59
```
So I wonder whether this output style is a part of design or some issue.
According to my schema, the CQL will only contact coordinator and only one cohort node, since all the data with `ts = 0 and network_name_mapped = 'Verizon'` is stored in one node (say, node-4).
After I have checked CQL trace, and then found that all operations processed on coordinator node and node-4. So I thought both coordinator and cohort node had issued the same CQL once. And dump their outputs to CQL execution node.
Please let me know whether this is your design or some other issue.
Here is my table schema
```CQL
CREATE TABLE opensignal.os_snapshot2 (
    ts timestamp,
    network_name_mapped text,
    network_type_mapped text,
    box_lat double,
    box_long double,
    created_at timeuuid,
    averaged_over double,
    download_speed double,
    lat double,
    long double,
    lucene text,
    network_id_mapped text,
    ping_time double,
    reliability double,
    rssi double,
    speed_averaged_over double,
    upload_speed double,
    PRIMARY KEY ((ts, network_name_mapped), network_type_mapped, box_lat, box_long, created_at)
) WITH CLUSTERING ORDER BY (network_type_mapped ASC, box_lat ASC, box_long ASC, created_at ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
CREATE CUSTOM INDEX os_snapshot2_spatial_index ON opensignal.os_snapshot2 (lucene) USING 'com.stratio.cassandra.lucene.Index';
```
And my index schema
```CQL
CREATE CUSTOM INDEX os_snapshot2_spatial_index ON os_snapshot2 (lucene) 
USING 'com.stratio.cassandra.lucene.Index' 
WITH OPTIONS = {  
    'refresh_seconds' : '60',
    'schema' : '{ 
        fields : { 
            place : { type : "geo_point", latitude:"lat", longitude:"long" }, 
            network_type_mapped: { type: "string" } 
        }     
    }' 
};
```

**Comment by adelapena** [comment]
Hi,

The count behavior that you report is not the expected, this should return a single row with the total count. Which version of the plugin are you using?

The search should be directed only to the nodes owning the specified partition key, and its replicas depending on the replication factor and consistency level. Which is your replication factor and consistency level?

**Comment by ealonsodb** [comment]
Hi, 
I am trying to reproduce this issue with version 2.1.9.1 with both single node and ccm cluster, and it does not happen.

So please , can you answer these questions??

1.- Version of cassandra and plugin.
2.- Replication factor and consistency level.

Thanks in advance

**Comment by Evangileon** [comment]
Hi @adelapena @ealonsodb 
I compiled the plugin at branch `feature/upgrade_to_cassandra_2.2.0`
Here is my settings
* Cassandra 2.2.1
* 7 nodes
* Replication factor = 2
* Consistency level = 1

**Comment by ealonsodb** [comment]
hi @Evangileon, i have reproduce the issue and now it is fixed in branch feature/upgrade_to_cassandra_2.2.0. 

And we have realized that this problem was happening too in all other aggregation functions and  UDFs 

Please confirm that it is already resolved.
Thank you for your effort.

**Comment by Evangileon** [comment]
Thanks, it works!
