### ISSUE TITLE
bitemporal index unexpedted filtering on vt

### ISSUE THREAD

**Issue by cyrilco0** [Stratio/cassandra-lucene-index#46]
I have a simple entry (in a single table):
Table structure:
```
CREATE TABLE users (
         user_id int,
         name text,
         vt_from text,
         vt_to text,
         tt_from text,
         tt_to text,
         lucene text,
         PRIMARY KEY (user_id, vt_from, tt_from)
     );

     CREATE CUSTOM INDEX users_index on users(lucene)
     USING 'com.stratio.cassandra.lucene.Index'
     WITH OPTIONS = {
         'refresh_seconds' : '1',
         'schema' : '{
         fields : {
         bitemporal : {
             type : "bitemporal",
             tt_from : "tt_from",
             tt_to : "tt_to",
             vt_from : "vt_from",
             vt_to : "vt_to",
             pattern : "yyyy/MM/dd",
             now_value : "2200/12/31"}
         }
     }'};
```

value
```
INSERT INTO users (user_id,  name, vt_from, vt_to, tt_from, tt_to)
    VALUES (42, 'Bob', '2015/01/01', '2200/12/31', '2015/01/01', '2015/01/05');
```

The "valid" date range is from 2015-01-01 to 2200-12-31, so I should be able to read it while filtering on a sub-range: [2015-01-06, 2200-12-31]. But this does not work.

```
SELECT name FROM users
WHERE lucene = '{
    filter : {
        type : "bitemporal",
        field : "bitemporal",
        vt_from : "2015/01/06",
        vt_to : "2200/12/31"
    }
}';
```

This query **does not find any value**, despite the VT range intersects the data VT range (and TT also, as I left them to default)
Same result with specific TT in the query filter ( `tt_from : "2015/01/01", tt_to : "2200/12/31"`)

But the same query does find data with: `vt_from : "2015/01/04"`.
So it seems the data `tt_to` (2015/01/05) is somehow filtered by the query `vt_from` (2015/01/06)!

Why I cannot query my data? 
 the query [tt_from, tt_to] range includes the one of the data, it should not be affected by the query VT.

**Comment by ealonsodb** [comment]
which version of the plugin are you using?? branch-2.1.9??

**Comment by cyrilco0** [comment]
yes branch-2.1.9
```
# Changelog
## 2.1.9.0 (9 September 2015)
...
```

**Comment by ealonsodb** [comment]
This issue is fixed in [master](https://github.com/Stratio/cassandra-lucene-index/tree/master) branch. This  will be included in next release.

Thank you.
