### ISSUE TITLE
Timeout on multiple concurrent queries

### ISSUE THREAD

**Issue by razvanz** [Stratio/cassandra-lucene-index#47]
This is probably not an issue but a question.

I have a script which bootstraps the data model and inserts some data. The inserts have some hefty logic (they insert > search > update) and run in parallel. (Just to mention, searching is using the lucene index.) 

I used to run it on a single node and recently I added one more to form a cluster (2 nodes). I'm experiencing time outs and I tried both on the old `stratio-cassandra-2.1.5.0` and the new `cassandra-2.1.9` + `cassandra-lucene-index-2.1.9.0`. The database nodes + custom indexes were set-up with pretty much default settings from the documentation.

After some investigation, it seemed that the cluster could not keep up with that concurrency, which was in the order of 10's. It seems pretty strange, given that the database is benchmarked way above that.

To conclude, I'm left with few questions:
1. Is this slow behavior normal or I'm doing something obviously wrong?
2. If it is normal, which part is more plausible to be the problem: Cassandra or the index?
3. Which would be the first config adjustments to give better results?
4. Is it just a concurrency problem?

**Comment by adelapena** [comment]
Indexing adds extra load to writes because each insertion must be done both in C* and in Lucene indexes. So, benchmarks done without indexes are not valid to estimate the behavior with indexes.

The concurrency level should not be a problem. Instead of that, a better way to measuring the write performance is the write throughput. Which is your write throughput? Which hardware are you using?

**Comment by razvanz** [comment]
First, sorry for taking so long. After some further investigation I narrowed down the problem to a bad data model design according to [CASSANDRA-7103](https://issues.apache.org/jira/browse/CASSANDRA-7103?jql=project%20%3D%20CASSANDRA%20AND%20text%20~%20%22operation%20timed%20out%20map%22).

This has nothing to do with the lucene index, therefore I'm closing it. Thanks for your time!

**Comment by adelapena** [comment]
Great, thanks!
