### ISSUE TITLE
create index on existing table does not work

### ISSUE THREAD

**Issue by sunchanras** [Stratio/cassandra-lucene-index#5]
create index before data insertion is ok, but when I created index on existing data(millions rows) , the query result always 0 row return.

**Comment by adelapena** [comment]
It should be able to index already existing data. Index build take some time, depending on the amount of stored data, your hardware and your schema.

Have you seen a message like ``Index build of <index_name> complete`` in the Cassandra log file before doing your queries? Is the log file reporting any error?

**Comment by sunchanras** [comment]
Thank for your great work, @adelapena. Yes, it did index and took some time to complete.
Here, I run on my laptop with core I5,SSD and 8GB of RAM.
I have existing table with 20 millions  partition(row) after issue the command to create index
create custom index tweets.idx on tweets(lucene) using 'com.stratio.cassandra.lucene.Index' with options={'refresh_seconds':'1','schema':'{fields:{message:{type:"string"}}}'}, it took sometime, I did not check casandra log, but I wait until the CPU stop indexing, then I started to query again with no result, so I decided to leave it one more hour, still query with no result.

**Comment by sunchanras** [comment]
It working now. Thank @adelapena

**Comment by adelapena** [comment]
Great! So, can we close the issue?

By the way, you can also monitor the number of indexed rows [through JMX](https://github.com/Stratio/cassandra-lucene-index/blob/branch-2.1.6/doc/extended-search-in-cassandra.md#jmx-interface).

**Comment by sunchanras** [comment]
Yes! thank @adelapena .
