### ISSUE TITLE
Split query builder from the main package

### ISSUE THREAD

**Issue by morten-holm** [Stratio/cassandra-lucene-index#50]
We use the query builder in the client but don't want to include all transitive dependencies of the main package in our build.

**Comment by adelapena** [comment]
It's in our roadmap, we will move the query builder to a separate module ASAP.

**Comment by adelapena** [comment]
Hi, just to let you know that we have just added a separate query builder module both in 2.1.11 and master branchs. You can find the documentation [here](https://github.com/Stratio/cassandra-lucene-index/blob/branch-2.1.11/doc/src/site/sphinx/documentation.rst#query-builder). This will be in Maven Central as soon as we release 2.1.11.0 and/or 2.2.3.0. I hope it helps.
