### ISSUE TITLE
Support with  Cassandra 2.2 and 3.0 ?

### ISSUE THREAD

**Issue by sunchanras** [Stratio/cassandra-lucene-index#53]
@adelapena
Can I use current release with Cassandra 2.2 or 3.0? 
Do you have plan to release for 2.2 and 3.0?

Thanks.

**Comment by ealonsodb** [comment]
This question has already been answered [before](https://github.com/Stratio/cassandra-lucene-index/issues/29).

We usually support the last stable release in cassandra that now it is 2.1.x.

As soon as Cassandra releases 3.0, we will start working on it.

**Comment by sunchanras** [comment]
@ealonsodb  
It's good to start working  on Candidate Release of Cassandra. like 3.0.0 rc2, so for those in development phase be able to test with lucene secondary index. I think it's not a big change to cassandra-lucene compatible with Cassandra 3.0. For now, Cassandra throw error even I create lucene index on 3.0
 
```
error:unable to find custom indexer class 'com.stratio.cassandra.lucene.Index'
```
Thank

**Comment by adelapena** [comment]
Yes, it is a big change to do cassandra-lucene compatible with Cassandra 3.0, there's a [refactor of the storage engine](https://issues.apache.org/jira/browse/CASSANDRA-8099) and an [index API redesign](https://issues.apache.org/jira/browse/CASSANDRA-9459), so it's going to take a while.

**Comment by sayeaud** [comment]
@ealonsodb @adelapena, given that Cassandra 2.2.X is now considered the [stable release](http://cassandra.apache.org/download/), what's your timeline to merge the [upgrade_to_cassandra_2.2.0](https://github.com/Stratio/cassandra-lucene-index/tree/feature/upgrade_to_cassandra_2.2.0) branch and produce the corresponding artifacts?

BTW, great work guys.

**Comment by adelapena** [comment]
@sayeaud, we have plans to release 2.2.3.0 (which is in [master branch](https://github.com/Stratio/cassandra-lucene-index/tree/master)) later this week or, in the worst case, early next week. Cassandra 3.x will take some more time.

**Comment by sunchanras** [comment]
@adelapena  I am waiting for Cassandra 3.x .

Thank.

**Comment by adelapena** [comment]
Hi,

As promised, [2.2.3.0](https://github.com/Stratio/cassandra-lucene-index/tree/2.2.3.0) has been just released, including UDF, UDAF, UDT and new CQL data types support. Artifacts have been put in our Nexus repo and they will be available in Maven Central in a few hours.

**Comment by sunchanras** [comment]
@adelapena 
Hi,
Is it compatible with 3.0 ?
Thank

**Comment by adelapena** [comment]
@sunchanras, as you can read in the project documentation, the three first numbers of the version number indicate the compatible Apache Cassandra version. As you can read in this thread, 2.x versions can't be compatible with 3.x due to the afforementoned refactors of the Apache Cassandra.

**Comment by EzequielAdrianM** [comment]
Hi @adelapena is there any way to release a version for Cassandra 3.2?

**Comment by adelapena** [comment]
Hi @EzequielAdrianM, 

We are [very close](https://github.com/Stratio/cassandra-lucene-index/tree/feature/upgrade_to_3.x) to publish a 3.x compatible version, but it won't be possible until [CASSANDRA-11043](https://issues.apache.org/jira/browse/CASSANDRA-11043) is fixed. We will publish a version of the plugin for the first 3.x release containing this fix.

**Comment by masumsoft** [comment]
@adelapena Looks like [CASSANDRA-11043](https://issues.apache.org/jira/browse/CASSANDRA-11043) has been resolved few days ago. Any updates on expected release time would help us a lot. As there are so many changes in cassandra 3, I understand it should take some time to release the compatible version of the lucene index plugin. But you know, as you guys have made us hopelessly dependent on this plugin, we will continue to push for it ;-)

**Comment by adelapena** [comment]
Hi @masumsoft ,

We have plans to release a 3.0.3.0 version hopefully at the end of this week, or next week at the latest.

In the mean time, you can take a look on [upgrade_to_3.x branch](https://github.com/Stratio/cassandra-lucene-index/tree/feature/upgrade_to_3.x).

We are very happy with having made you hopelessly dependent on this project ;)

**Comment by adelapena** [comment]
[3.0.3.0](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.3) is almost ready, it will be released this Monday.

**Comment by EzequielAdrianM** [comment]
That's good news! Gracias.

**Comment by masumsoft** [comment]
Will the latest 3.0.3 work with cassandra tick tock release 3.3?

**Comment by adelapena** [comment]
No, it wont. Version 3.0.3.0 is intended to be used with Apache Cassandra 3.0.3.
