### ISSUE TITLE
Current release version not support with Cassandra 3.0

### ISSUE THREAD

**Issue by sunchanras** [Stratio/cassandra-lucene-index#54]
@adelapena 

When I use current release with Cassandra 3.0, got this error. Work ok with 2.1.11.
```
error:unable to find custom indexer class 'com.stratio.cassandra.lucene.Index'
```
Cassandra 3.0 support release soon?
Anything I can help here? 
Best Regards

**Comment by adelapena** [comment]
Repeated from #53
