### ISSUE TITLE
sorting is broken after using boolean type filter in query

### ISSUE THREAD

**Issue by dejwsz** [Stratio/cassandra-lucene-index#55]
Hi, I tried to query my example table using lucene index with timestamp sorting. If I use only one filter like 'range' sorting by date works great, I can reverse it also. But after I change my filter to boolean type to have two different conditions like range and prefix then reverse sorting stops working - I cannot sort in reverse anymore by date. So this works fine (can sort in both directions by date):

SELECT modifytime,noteid,userid FROM epodb.notes
WHERE fts_index = '{filter : {type:"range", field:"modifytime", lower:"2015/09/28 00:00:00"},
                        sort : {fields: [ {field:"modifytime", reverse:true}]}}'
limit 20;

But this one stops sorting in reverse by date (regardless the reverse parameter results are always sorted ascending):

SELECT modifytime,noteid,userid FROM epodb.notes
WHERE fts_index = '{filter : {
                        type : "boolean",
                        must : [{type:"range", field:"modifytime", lower:"2015/09/28 00:00:00"},
                                {type : "prefix", field : "value", value : "a"}],
                        sort : {fields: [ {field:"modifytime", reverse:true}]}}}'
limit 20;

**Comment by adelapena** [comment]
Yes, it should work. Could you please paste here your table and index creation statements? Which version of the index are you using?

**Comment by dejwsz** [comment]
Sorry I updates before a minute - it is sorted but only ascending - I cannot reverse it

**Comment by dejwsz** [comment]
CREATE TABLE IF NOT EXISTS epodb.notes (
  noteId uuid,
  userId varchar,
  handbookId varchar,
  moduleId varchar,
  location varchar,
  pageId varchar,
  subject varchar,
  value varchar,
  type int,
  accepted boolean,
  modifyTime timestamp,
 PRIMARY KEY ((userId,handbookId),moduleId,noteId)
 )
WITH CLUSTERING ORDER BY (moduleId ASC, noteId ASC);

CREATE CUSTOM INDEX notes_index on epodb.notes(fts_index)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '10',
    'directory_path' : '/var/lib/cassandra/lucene',
    'excluded_data_centers' : 'DC1',
    'schema' : '{
        analyzers : {
              polish_analyzer : {
                  type:"classpath",
                  class:"org.apache.lucene.analysis.morfologik.MorfologikAnalyzer"}
        },
        default_analyzer : "english",
        fields : {
            userid    : {type : "string"},
            handbookid  : {type : "string"},
            moduleid  : {type : "string"},
            noteid  : {type : "string", sorted : true},
            handbookid  : {type : "string"},
            location : {type : "string"},
            pageid : {type : "string"},
            type : {type : "integer"},
            subject  : {type : "text", "analyzer": "polish_analyzer"},
            value  : {type : "text", "analyzer": "polish_analyzer"},
            modifytime  : {type : "date", pattern : "yyy/MM/dd HH:mm:ss", sorted : true}
        }
    }'
};

**Comment by adelapena** [comment]
Ok, thanks, I'll take a look on it.

**Comment by adelapena** [comment]
It's not a bug, but a parenthesization problem in the second search. The sort clause is inside the filter clause, so its being ignored. It must be one JSON level above, at the same level as the filter:
```
SELECT modifytime,noteid,userid FROM epodb.notes
WHERE fts_index = '{
   filter : {
      type : "boolean",
      must : [{type:"range", field:"modifytime", lower:"2015/09/28 00:00:00"},
                  {type : "prefix", field : "value", value : "a"}]
   },
   sort : {
      fields: [ {field:"modifytime", reverse:true}]}
}'
limit 20;
```

**Comment by dejwsz** [comment]
Ah yes indeed, my fault, sorry, I overlooked this, Thanks!
