### ISSUE TITLE
What happen when data in nodes of a cluster is rebalanced?

### ISSUE THREAD

**Issue by sunchanras** [Stratio/cassandra-lucene-index#58]
@adelapena What happen when data nodes of cluster is rebalanced by adding new node?
Does the index file move along with the indexed table automatically? or we need to re-index field of table after rebalancing is completed?

Thank.

**Comment by ealonsodb** [comment]
Hi @sunchanras :

When a new node is added to a cluster and this rebalances its load, the old node index, where the data resided, recieves a DELETE via gossip and the new one receive an INSERT, so no file is exchanged between nodes.
No need to re-index.

Thank you.
