### ISSUE TITLE
Stratio/Lucene cannot search case insensitive.

### ISSUE THREAD

**Issue by minauser** [Stratio/cassandra-lucene-index#62]
Hi,

I am trying to do a case insensitive search in Stratio/Cassandra-Lucene. However, using "case sensitive : false" when creating index did not help.

Please see below for the information on CREATE INDEX, CREATE KEYSPACE, CREATE TABLE, INSERT and SELECT.

CREATE CUSTOM INDEX my_index ON my_table (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
'refresh_seconds' : '10',
'schema' : '{
fields : {
id : {type : "uuid"},
name : {type : "string", case_sensitive: false}
}
}'
};

CREATE KEYSPACE IF NOT EXISTS my_keyspace WITH replication = {'class':'SimpleStrategy', 'replication_factor':1};

CREATE TABLE IF NOT EXISTS my_table(id uuid, name varchar, lucene TEXT, PRIMARY KEY(id)

INSERT INTO my_table(name, id) VALUES (“TestName”, "1c3d775f-d251-448f-9d51-5f3e0689ff0c") IF NOT EXISTS

SELECT name, id FROM my_table WHERE lucene = 'filter: { type: "match", field: "name", value: "TestName" }'

Returns 1 row BUT if I change the query to

SELECT name, id FROM my_table WHERE lucene = 'filter: { type: "match", field: "name", value: "testName" }'

Returns nothing!

**Comment by adelapena** [comment]
It seems that there are several typos in your example. We assume that the right example is:
``` 
CREATE KEYSPACE IF NOT EXISTS my_keyspace WITH replication = {'class':'SimpleStrategy', 'replication_factor':1};

USE my_keyspace;

CREATE TABLE IF NOT EXISTS my_table(id uuid, name varchar, lucene TEXT, PRIMARY KEY(id));
INSERT INTO my_table(name, id) VALUES ('TestName', 1c3d775f-d251-448f-9d51-5f3e0689ff0c);
CREATE CUSTOM INDEX my_index ON my_table (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds' : '10',
   'schema' : '{
      fields : {
         id : {type : "uuid"},
         name : {type : "string", case_sensitive: false}
      }
   }'
};
-- Wait ten seconds for index refresh
SELECT name, id FROM my_table WHERE lucene = {'filter: { type: "match", field: "name", value: "Testname" }};
SELECT name, id FROM my_table WHERE lucene = {'filter: { type: "match", field: "name", value: "testName" }};
SELECT name, id FROM my_table WHERE lucene = {'filter: { type: "match", field: "name", value: "testname" }};
```
We have tested it with the current 2.1.11.0 and also with 2.1.10.0, and it works perfectly. Maybe you are not waiting for the ten seconds refresh period specified in the create index statement?

**Comment by minauser** [comment]
Hi,

Thank you for the information, appreciate it!

I have a question for you regarding the wildcard filter. After I
applied "case_sensitive:
false", I am not able to do combined wildcard search.

Considering the above similar example:

INSERT INTO my_table(firstname, lastname,id) VALUES ('NameTest',
'LastNameTest', 1c3d775f-d251-448f-9d51-5f3e0689ff0c);

CREATE CUSTOM INDEX my_index ON my_table (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds' : '10',
   'schema' : '{
      fields : {
         id : {type : "uuid"},
         firstname : {type : "string", case_sensitive: false},
lastname :        {type : "string", case_sensitive: false}

      }
   }'
};


SELECT firstname, lastname,id FROM my_table WHERE lucene = {'filter: {
type: "wildcard", field: "firstname", value: "N*" }};

returns 1 row.


However, SELECT firstname, lastname,id FROM my_table WHERE lucene =
{'filter: {type:"boolean", must:[{ type: "wildcard", field:
"firstname", value: "N*" }, { type: "wildcard", field: "lastname",
value: "L*" }]};


returns nothing.


Kindest regards,

Mina

**Comment by minauser** [comment]
And if I have

SELECT firstname, lastname,id FROM my_table WHERE lucene = {'filter:
{type:"boolean", must:[{ type: "wildcard", field: "firstname", value:
"n*" }, { type: "wildcard", field: "lastname", value: "l*" }]};

it returns one row

**Comment by minauser** [comment]
So when we have added case_sensitive :false and we are going to do a
wildcard search, should it be lowercase in the filter (e.g. "n*" instead of
"N*")?
