### ISSUE TITLE
Class not found exception while creating index

### ISSUE THREAD

**Issue by jereesh** [Stratio/cassandra-lucene-index#71]
Tried with DataSax Cassandra community Edition 2.2.3 and followed the steps mentioned in the document but get the following error.

cqlsh:jpos> CREATE CUSTOM INDEX tweets_index ON tweets (lucene)
           ... USING 'com.stratio.cassandra.lucene.builder.index.Index'
           ... WITH OPTIONS = {
           ...     'refresh_seconds' : '1',
           ...     'schema' : '{
           ...         fields : {
           ...             id    : {type : "integer"},
           ...             user  : {type : "string"},
           ...             body  : {type : "text", analyzer : "english"},
           ...             time  : {type : "date", pattern : "yyyy/MM/dd", sorte
d : true},
           ...             place : {type : "geo_point", latitude:"latitude", lon
gitude:"longitude"}
           ...         }
           ...     }'
           ... };
ServerError: ErrorMessage code=0000 [Server error] message="java.lang.RuntimeEx
ception: java.lang.ClassNotFoundException: com.stratio.cassandra.lucene.builder.
index.Index"

**Comment by adelapena** [comment]
Hi,
As you can read in the [ current documentation](https://github.com/Stratio/cassandra-lucene-index/blob/branch-2.2.3/doc/src/site/sphinx/documentation.rst#example), the name of the index class is ``com.stratio.cassandra.lucene.Index``, instead of ``com.stratio.cassandra.lucene.builder.index.Index``. This last is the class used by the Java query builder.

**Comment by jereesh** [comment]
The issue is resolved , Initially I used only the com.stratio.cassandra.lucene.Index, but got the error. I just restarted the Cassandra Community Server service only . When I ran the Cassandra batch file it is working. Thank you.
