### ISSUE TITLE
Stable release version 2.1.0 in maven

### ISSUE THREAD

**Issue by arunavdev89** [Stratio/cassandra-lucene-index#73]
The earliest plugin version in the maven repo seems to be 2.1.11, any plan on including earlier releases?

**Comment by adelapena** [comment]
Last version in [Maven Central is 2.2.3.1](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.stratio.cassandra%22%20AND%20a%3A%22cassandra-lucene-index-plugin%22), and not 2.1.11. Which Maven repo are you using?

**Comment by arunavdev89** [comment]
The earliest release you have is 2.1.6, but on maven repo search, it seems the latest you have is 2.2.4.
