### ISSUE TITLE
Issue with multiple range search in boolean filter

### ISSUE THREAD

**Issue by arunavdev89** [Stratio/cassandra-lucene-index#74]
I have a table as follows:

    CREATE TABLE IF NOT EXISTS user(
          orgId uuid ,  
          groupId uuid,
          groupName text, 
          unit text,  
          userName text,
          userId uuid, 
          lucene  TEXT,
      PRIMARY KEY ((orgId ), groupId , unit, userName));

I have created the index on `groupName`, `unit`, and `userName` fields as follows: 

    CREATE CUSTOM INDEX userCustomIndex ON user(lucene)
    USING 'com.stratio.cassandra.lucene.Index'
    WITH OPTIONS = {
        'refresh_seconds' : '1',
        'schema' : '{
            fields : {            
               username:{type: "text", sorted: "true", analyzer: "english"},
               groupname :{type: "text", analyzer: "english"},
               unit:{type: "text", analyzer: "english"}
            }
        }'
    };

Making the following inserts:
````
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Art', 'Archival', 'Aaron', 1132c935-cbb3-4c66-90ac-2478ca6a5633
);
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Art', 'Archival', 'James', 1132c935-cbb3-4c66-90ac-2478ca6a5634
);
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Business', 'Accounting', 'Jane', 1132c935-cbb3-4c66-90ac-2478ca6a5635
);
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Business', 'Accounting', 'Jean', 1132c935-cbb3-4c66-90ac-2478ca6a5636
);
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Business', 'Accounting', 'Juan', 1132c935-cbb3-4c66-90ac-2478ca6a5637
);
````
I want to run the following equivalent query filtering users by a range of username, groupname, and unit:
````
select * from user where orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND  groupName >='Art' AND unit>='Accounting' AND userName > 'James' limit 25;
````
Basically retrieve next 25 users in sorted order of group and business unit, that come after user x. Since Cassandra only allows  `>` or `<` on one field, I was hoping I could use the lucence indexing something similar to the following boolean search.

````
select * from user where orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND lucene='
	{filter : {
                   type : "boolean",
                   must : [
                              {type : "range", field : "groupname",lower: "Art", include_lower : true },
		              {type : "range", field : "unit",lower: "Archival", include_lower : true},
			           {type : "range", field : "username",lower: "James", include_lower : false}
			      ]
  			  },
           refresh:true
}' LIMIT 5
````
It returns users `James`, and ` Aaron` as well which belongs to `Art` group and `Archival` unit. I thought since I did not put `include_lower` on `username` field, (default is false) it would exclude `James`. Why it is including `Aaron` as well (even though I explicitly put lower bound to `James`) I am not sure. Am I missing something? 

It seems the boolean search is not properly working with Range for text fields?
<b>
UPDATE: 
</b>
The issue might be range search on text:
````
select * from user where orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND lucene='
	{filter : {type : "range", field : "username", lower: "Juan", include_lower : false }
  			  ,
    refresh:true
}' LIMIT 5;
````
This query seems to return all the users including Aaron, James as well.

**Comment by adelapena** [comment]
You are using a ``text`` mapper that analyzes the text before indexing it. Probably the analyzer is not producing the terms you expect. I think that ``string`` mappers would be more appropriate:
```
CREATE CUSTOM INDEX userCustomIndex ON user(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {            
           username:{type: "string", sorted: "true", analyzer: "english"},
           groupname :{type: "string", analyzer: "english"},
           unit:{type: "string", analyzer: "english"}
        }
    }'
};
SELECT * FROM user WHERE orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND lucene='
    {filter : {
                   type : "boolean",
                   must : [ {type : "range", field : "groupname", lower: "Art",       include_lower : true },
                      		{type : "range", field : "unit",     lower: "Accounting", include_lower : true },
                       		{type : "range", field : "username", lower: "James",      include_lower : false}
                  ]
              },
           refresh:true
}' LIMIT 5;
```

**Comment by arunavdev89** [comment]
Thanks! It seems to work as expected for individual query after I changed to string mapper.

````
select * from user where orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND lucene='
	{filter : {type : "range", field : "groupname", lower: "Art", include_lower : true }
  			  ,
    refresh:true
}' LIMIT 5;

select * from user where orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND lucene='
	{filter : {type : "range", field : "unit", lower: "Archival", include_lower : true }
  			  ,
    refresh:true
}' LIMIT 5;
select * from user where orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND lucene='
	{filter : {type : "range", field : "username", lower: "James", include_lower : false }
  			  ,
    refresh:true
}' LIMIT 5;
````

All of these return data as expected. However, when I specify a boolean search with a must condition, it does not return any match.
```
select * from user where orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND lucene='
	{filter : {
                   type : "boolean",
                   must : [{type : "range", field : "groupname",lower: "Art", include_lower : true },
						   {type : "range", field : "unit",lower: "Archival", include_lower : true},
						   {type : "range", field : "username",lower: "James", include_lower : false}
						  ]
  			  },
    refresh:true
}' LIMIT 5;
```

Is there anything I am missing? My understanding so far is boolean with must condition kind of performs an AND operation on each search query.

**Comment by adelapena** [comment]
Hi,
Indeed ``must`` clause performs a logic AND operation. I'm using your provided dataset:
```
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Art', 'Archival', 'Aaron', 1132c935-cbb3-4c66-90ac-2478ca6a5633
);
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Art', 'Archival', 'James', 1132c935-cbb3-4c66-90ac-2478ca6a5634
);
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Business', 'Accounting', 'Jane', 1132c935-cbb3-4c66-90ac-2478ca6a5635
);
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Business', 'Accounting', 'Jean', 1132c935-cbb3-4c66-90ac-2478ca6a5636
);
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Business', 'Accounting', 'Juan', 1132c935-cbb3-4c66-90ac-2478ca6a5637
);
```
Using this dataset, the provided query must produce no results:
```
select * from user where orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND lucene='
    {filter : {
                   type : "boolean",
                   must : [
                               {type : "match", field : "groupname",value: "Art"},
                   {type : "range", field : "unit",lower: "Archival", include_lower : true},                                                   
                   {type : "range", field : "username",lower: "James", include_lower : false}
                  ]
              },
    refresh:true
}' LIMIT 5;
```
This is the expected behavior because the last two clauses produce mutually exclusive sets, which in an AND operation is enough to produce an empty result set. 

Boolean conditions can be nested into the clauses of other boolean queries, so you can implement any boolean logic. For example, you can use a boolean condition with a ``should`` uniting two boolean conditions with ``must`` clauses:
```
select * from user where orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND lucene='
   {filter : {
      type   : "boolean",
      should : [{type : "boolean", must : [...] },
                {type : "boolean", must : [...],
               ]
   },
   refresh:true
}' LIMIT 5;
```

**Comment by arunavdev89** [comment]
Thanks! I think for the most part this solved the problem of performing multiple queries.

One other issue with wildcard search seems, doing a "*<character seqauennce>*" foes not filter all the entries containing the character sequence.

To illustrate, I have run the following queries:
````
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Business', 'Accounting', 'Tasmania', 1132c935-cbb3-4c66-90ac-2478ca6a5638
);
INSERT INTO user (orgId , groupId , groupName , unit ,userName , userId ) VALUES (
1132c935-cbb3-4c66-90ac-2478ca6a5631, 1132c935-cbb3-4c66-90ac-2478ca6a5632, 'Business', 'Accounting', 'Toronto', 1132c935-cbb3-4c66-90ac-2478ca6a5638
);
````

When I run wildcard search filter it only returns "Toronto", not "Tasmania". 
````
select * from user where orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND lucene='
	{query : {type : "wildcard", field : "username", value:"*t*" }  			  
}' LIMIT 5;
````

For my wildcard match, I need to match the tokens in the middle of the text as well as prefix/postfix, and I need the match to be case sensitive. I did some readup on lucene analyzers, but it seems no analyzer alone could do the trick. I tried snowball, standard analyzer, and pattern analyzer all of which does seem to use `LowerCaseFilter` but none of them fulfill all the above match criteria. 

I could use regexp search filtering, but I would assume that would have more performance overhead than just a wildcard search.

**Comment by adelapena** [comment]
I guess that you are using ``string``mappers:
```
CREATE CUSTOM INDEX userCustomIndex ON user(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {            
           username : {type: "string", sorted: "true"},
           groupname : {type: "string"},
           unit : {type: "string"}
        }
    }'
};
```
This kind of mapper doesn't allow to specify an analyzer.  Instead, it uses a fixed [KeywordAnalyzer](https://lucene.apache.org/core/5_3_0/analyzers-common/org/apache/lucene/analysis/core/KeywordAnalyzer.html) that produces a single **case sensitive** token.

Indeed, the search with upper case ``*T*`` finds the two rows:
```
select * from user where orgId=1132c935-cbb3-4c66-90ac-2478ca6a5631 AND lucene='
    {query : {type : "wildcard", field : "username", value:"*T*" }                
}' LIMIT 5;
```
However, your query using ``*t*`` only finds ``Toronto`` because it matches the second, lower case ``t`` in the word, but not the first upper case ``T``.

If you are not interested in this behaviour, you can set the mappers to be case insensitive:
```
CREATE CUSTOM INDEX userCustomIndex ON user(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {            
           username : {type: "string", sorted: "true", case_sensitive:false},
           groupname : {type: "string", case_sensitive:false},
           unit : {type: "string", case_sensitive:false}
        }
    }'
};
```

**Comment by arunavdev89** [comment]
Thanks you. I think my issue was I was running 2.2.4 with plugin version 2.2.1 so case_insensitive was not working properly. 

Are the plugins going to be backward compatible in future?
