### ISSUE TITLE
unavailable nodes caused by timeout exception

### ISSUE THREAD

**Issue by cscetbon** [Stratio/cassandra-lucene-index#77]
Hey @adelapena,

I run some automated read tests and got issues with cassandra 2.1.11 and branch-2.1.11. You can see the error at http://pastebin.com/2rGwzHXv, but the result is that nodes are unreachable for minutes even if there are seen as available : 

```
$ nodetool status|grep 10.0.1.121
UN  10.0.1.121  120.29 MB  256     ?       dd0989e8-8de9-403c-a89a-50b664512c97  r01
```

What I can say is that it's originally caused by a timeout exception not caught in your classes. I don't get any issues when I execute request manually, but when I try to automate it to see how many queries I can do and to measure latencies I block my whole cluster : 

```
$ cqlsh 10.0.1.121
Connection error: ('Unable to connect to any servers', {'10.0.1.121': OperationTimedOut('errors=Timed out creating connection (5 seconds), last_host=None',)})
```

**Comment by adelapena** [comment]
Hi,

It seems that the errors are related to authentication checkings producing timeouts. Are you using any  particular authentication checking?

**Comment by cscetbon** [comment]
Honestly, I think it's just the fact that all calls use authentication and that's why it appears in the stack. But I'm not sure it is the cause of the errors. We use the basic authentication method available. It happens only when we access the index.

**Comment by adelapena** [comment]
So you are using ``PasswordAuthenticator`` and ``CassandraAuthorizer`` in your ``cassandra.yaml``, aren't you? Are you using the Java driver for your test? Which version?

You say that you don't get any issues when you execute request manually, what do yo you mean by manually? Using cqlsh?

We are trying to reproduce the issue in order to fix it.

**Comment by cscetbon** [comment]
>So you are using PasswordAuthenticator and CassandraAuthorizer in your cassandra.yaml, aren't you? 

Yes

>Are you using the Java driver for your test? Which version?

Java 8u31

>You say that you don't get any issues when you execute request manually, what do yo you mean by manually? Using cqlsh?

Yes using cqlsh

To help you in your investigations, here is what happened when I try to execute the same query several times sequentially http://pastebin.com/v2AWsqjF and the same test when I try it in parallel http://pastebin.com/UYMmix2U.
