### ISSUE TITLE
Unable to do query using SparkSql

### ISSUE THREAD

**Issue by ssuperczynski** [Stratio/cassandra-lucene-index#79]
- Based on this url: https://docs.datastax.com/en/datastax_enterprise/4.6/datastax_enterprise/spark/sparkSqlScala.html

- Given I have scala object

```scala
object SparkConnector {
  val conf = new SparkConf(true).set("spark.cassandra.connection.host", "127.0.0.1")
  val sc = new SparkContext("local", "Application", conf)
}
```
- and scala method to connect to Cassandra
```scala
  def get(): Set[String] = {
    val cc = new CassandraSQLContext(SparkConnector.sc)
    val lucene = """
      '{
          filter :
              {
                  type:"geo_distance",
                  field:"place",
                  latitude:52.39416,
                  longitude:16.93779,
                  max_distance:"1km",
                  min_distance:"10m"
              }
      }'
      """
    val rdd: DataFrame = cc.sql(s"SELECT * FROM dev.location WHERE lucene=$lucene")
    rdd.collect.foreach(value => {
      println(value)
    })
  }
```

- And I created index:
```sql
CREATE CUSTOM INDEX location_index ON location (lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
  'refresh_seconds' : '1',
      'schema' : '{
          fields    : {
              context   : {type : "string"},
              query     : {type : "string"},
              created   : {type : "date", pattern : "yyyy/MM/dd", sorted : true},
              place     : {type : "geo_point", latitude:"lat", longitude:"long"}
          }
      }'
};
CONSISTENCY ALL
SELECT * FROM location WHERE lucene = '{refresh:true}';
CONSISTENCY QUORUM
```

- When I execute this method, I am not getting back any results. But when I execute the same query in `cqlsh` console:

```sql
SELECT * FROM dev.location WHERE lucene='{
          filter :
              {
                  type:"geo_distance",
                  field:"place",
                  latitude:52.39416,
                  longitude:16.93779,
                  max_distance:"1km",
                  min_distance:"10m"
              }
      }'
```

am getting some results
<img width="428" alt="screen shot 2015-12-23 at 13 00 57" src="https://cloud.githubusercontent.com/assets/6843074/11976109/487c0c1a-a975-11e5-9a90-cd0a66374330.png">

Of course my method works when query does not have lucene query `SELECT * FROM dev.location`
What I am doing wrong? Is it possible that SparkSql have some problems with lucene queries?

**Comment by ealonsodb** [comment]
I think your problem is not related to sparkSQL or not directly. I think the problem is the scala multiline string (your val lucene) . 

Try this please: 

Replace this:

```
val lucene = """
      '{
          filter :
              {
                  type:"geo_distance",
                  field:"place",
                  latitude:52.39416,
                  longitude:16.93779,
                  max_distance:"1km",
                  min_distance:"10m"
              }
      }'
      """
```
with this:

```
val lucene = """
      |'{
          |filter :
              |{
                  |type:"geo_distance",
                  |field:"place",
                  |latitude:52.39416,
                  |longitude:16.93779,
                  |max_distance:"1km",
                  |min_distance:"10m"
              |}
      |}'
      """.stripMargin.replaceAll("\n", " ")
```

and add ';' at the end of the query.

This is described in scala [cookbook](https://www.safaribooksonline.com/library/view/scala-cookbook/9781449340292/ch01s03.html): 

Let us know if what i write here is correct, please

Thank you

**Comment by warkocz** [comment]
Having same problem with SparkSql in Scala, even using one line query:
`val df = cassandraSQLContext.sql("""SELECT id, message, lucene FROM feeds WHERE lucene='{query: {type: "phrase", field: "message", value: "BUU", slop: 1} }' limit 10""")`

Of course this returns results in cqlsh. Any ideas?

**Comment by ealonsodb** [comment]
Yes, we have done some tests and the full query reach cassandra but after that sparksql filters by lucene column. 
 
By the way you can use [spark connector](https://github.com/Stratio/cassandra-lucene-index-examples/tree/master/cassandra-lucene-index-examples-spark) without sparkSQL and [convert RDD to DataFrame](http://stackoverflow.com/questions/29383578/how-to-convert-rdd-object-to-dataframe-in-spark) 

Hope this helps

**Comment by Supanccy** [comment]
Hi，I have the same problem, in cql  the follow sql  work well, and returns result:
select * from zdt_ssl where lucene = '{ filter : {type:"match", field:"p", value:"111"}}';  When I execute the follow  method, I am not getting back any results. 

  def testConnectorSparkSql2(): Unit = {
    val sc = new SparkContext(conf)
    val sqlContext = new SQLContext(sc)
    var csl = new CassandraSQLContext(sc)
     val lucene = """
          |'{
              |filter :
                  |{
                      |type:"match",
                      |field:"p",
                      |value:"222"
                  |}
          |}'
          """.stripMargin.replaceAll("\n", " ");
     
     var sqlsql =  "select * from hleemas.zdt_ssl where lucene = " + lucene
     val df = csl.sql(sqlsql);
     df.show();
     println(df.count());
     sc.stop();
  }

So I want to know  if SparkSql is not support cassandra_lucene_idnex ?   Theank you.

**Comment by ssuperczynski** [comment]
@ealonsodb I did test with:

```scala
val lucene = """
      |'{
          |filter :
              |{
                  |type:"geo_distance",
                  |field:"place",
                  |latitude:52.39416,
                  |longitude:16.93779,
                  |max_distance:"1km",
                  |min_distance:"10m"
              |}
      |}'
      """.stripMargin.replaceAll("\n", " ")
```
and it returns no records

**Comment by ealonsodb** [comment]
Hi @Supanccy @warkocz @ssuperczynski .

The problem with cassandra-lucene-index with SparkSQL is that SparkSQL performs a filter after cassandra returns the query just for verify that 'lucene' column is equal to the value, in this case the query. 

So, as in our implementation 'lucene' column is always returned as null, this operation(after query filter) discards all the results. 

This [SparkC-JIRA](https://issues.apache.org/jira/browse/SPARK-10978) has resolved that, so using [spark-cassandra-connector](https://github.com/datastax/spark-cassandra-connector) since 1.6.0 (next release) with cassandra-lucene-index will support sparkSQL queries. 

Thank you all

**Comment by Supanccy** [comment]
@ealonsodb  got it ,  Thank you .

**Comment by ssuperczynski** [comment]
@ealonsodb Thank you for your and Stratio help in investigating this bug. :beers:

**Comment by junaidnasir** [comment]
it's still not working for me, am using spark-connector 2.0.3
pyspark, cassandra 3.11.0 lucene 3.11.0
any pointers?

**Comment by xiaohan815** [comment]
I also found this problem.if my lucene column is not empty,then can return results using spark.so I only can put some unused value to this column.Have any other resolutions?

**Comment by romulogoncalves** [comment]
We have the same issue with `spark-cassandra-connector:2.3.1-s_2.11` and `spark 2.2.0` and `cassandra-lucene-index-plugin-3.11.1.0`.

To repeat it just use `earthquakes.csv` from: https://docs.datastax.com/en/tutorials/gis.zip

Then
```
cqlsh> CREATE KEYSPACE gis WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 2 };

cqlsh> USE gis;

cqlsh:gis> CREATE TABLE earthquakes ( 
             datetime timestamp, 
             latitude double, 
             longitude double, 
             depth double, 
             magnitude double, 
             magtype text, 
             nbstations int, 
             gap double, 
             distance double, 
             rms double, 
             source text, 
             eventid int,
             PRIMARY KEY (datetime, latitude, longitude)
           );

cqlsh:gis> COPY earthquakes (datetime, latitude, longitude, depth, magnitude, magtype, nbstations, gap, distance, rms, source, eventid) FROM '<path>/earthquakes.csv' WITH HEADER = 'true';

```

To create the index:
```
ALTER TABLE gis.earthquakes add lucene text;

CREATE CUSTOM INDEX earthquakes_index ON gis.earthquakes(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
   'refresh_seconds': '1',
   'schema': '{
      fields: {
         geo_point: {
             type: "geo_point",
             validated: true,
             latitude: "latitude",
             longitude: "longitude",
             max_levels: 15
          }
       }
   }'
};
```
Load data into Spark using scala:
```
val df = spark
  .read
  .cassandraFormat("earthquakes","gis")
  .load()

df.createOrReplaceTempView("earthquakes")
```

Query the table:
```
val sqlQuery = "select * from earthquakes where lucene = '{filter: {type: \"geo_bbox\", field: \"geo_point\", min_latitude: 40.0, max_latitude: 50.0, min_longitude: 50.0, max_longitude: 60.0}}' LIMIT 10"

val resultDataFrame_B = spark.sql(sqlQuery)
spark.time { resultDataFrame_B.count }
```

It should return `28` records, but it returns 0.
