### ISSUE TITLE
Installation Test Failing

### ISSUE THREAD

**Issue by jamesajones** [Stratio/cassandra-lucene-index#83]
The second installation test (Creating a Custom Index) is failing.
Dialog Content: "Unable to execute CQL script on 'Test Cluster': com.stratio.cassandra.lucene.Index"

**Comment by ealonsodb** [comment]
Can you give us more information about this: 

When does it fails?? 
When you run `mvn clean package`??
What are the installation tests???

Which OS are you using??

**Comment by alextobias48** [comment]
I'm getting the same error message. I have a cluster set up on Windows Server 2012, I built the jar, and copied it into the lib folder and restarted Cassandra. I added a lucene text column to a table, then got the error when trying to create an index with the following query:

``CREATE CUSTOM INDEX tasks_index ON tasks (lucene)
``USING 'com.stratio.cassandra.lucene.Index'
``WITH OPTIONS = {
``    'refresh_seconds' : '1',
``    'schema' : '{
``        fields : {
``			task_id : {type : "uuid"},
``			name  : {type : "text", analyzer: "english"},
``			creation_timestamp  : (type : "timestamp"),
``                      priority : {type : "text". analyzer: "english"}
``        }
``    }'
``};

The query is being run on my Windows 7 laptop from the DataStax DevCenter program, with an established connection to the Cassandra cluster

**Comment by alextobias48** [comment]
I'm still having this issue, unable to find a fix for it.

**Comment by ealonsodb** [comment]
Hi @alextobias48:
I need to know which **cassandra** and **cassandra-lucene-index** **versions** are you using ??

There are some Typos in your query 
```
CREATE CUSTOM INDEX tasks_index ON tasks (lucene) 
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {  
    'refresh_seconds' : '1',
    'schema' : '{  
        fields : {
            task_id : {type : "uuid"},  
            name : {type : "text", analyzer: "english"},
            creation_timestamp : (type : "timestamp"),  
            priority : {type : "text". analyzer: "english"}
        }  
    }'
};
```

should be: 

```
CREATE CUSTOM INDEX tasks_index ON tasks (lucene) 
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {  
    'refresh_seconds' : '1',
    'schema' : '{  
        fields : {
            task_id : {type : "uuid"},  
            name : {type : "text", analyzer: "english"},
            creation_timestamp : {type : "timestamp"},  
            priority : {type : "text", analyzer: "english"}
        }  
    }'
};
```

Can you show us the **table creation query**, please?

Cheers

**Comment by alextobias48** [comment]
Cassandra - 2.1.11
Cassandra-lucene-index - 3.0.5.1

The error still happens with the corrected query.

I'll try and find the table creation query and update this post when I get it.

Thanks!

**Comment by ealonsodb** [comment]
Hi @alextobias48: 

The problem is you are using a bad cassandra-lucene-index version. 
-For cassandra 2.1.11 you must use the last cassandra-lucene-index:2.1.11.x (2.1.11.1)
-cassandra-lucene-index:3.0.5.1 is only for cassandra:3.0.5

You can get it so:

```
git clone http://www.github.com/stratio/cassandra-lucene-index
cd cassandra-lucene-index
git checkout 2.1.11.1
mvn clean package -Ppatch -Dcassandra_home=<CASSANDRA_HOME>
```

Cheers

**Comment by alextobias48** [comment]
Okay, I've built version 2.1.11.1, added it to the /lib/ folder on my server, restarted the server, and am still getting the same message. Is there a specific name that the .jar file should have or some config I should change to make Cassandra aware of the plugin? 

To me it seems like its not finding the plugin because when I change this line in my query

``USING 'com.stratio.cassandra.lucene.Index'

to

``USING 'com.stratio.cassandra.lucene.Index2'

the change is reflected in the error message.

Thanks again for your help!

**Comment by jamesajones** [comment]
Checked this for a while but finally forgot about it. Thanks for the answer
Currently Cassandra 3.0.13 and plugin branch-3.0.13 but struggling with mvn version 
Thanks
