### ISSUE TITLE
2.1.11.0 branch for cassandra 2.1.12?

### ISSUE THREAD

**Issue by dejwsz** [Stratio/cassandra-lucene-index#84]
Should the branch 2.1.11.0 of lucene index be used within cassandra 2.1.12 ? Is that ok? I cannot see corresponding version match.

**Comment by ealonsodb** [comment]
We released yesterday [cassandra-lucene-index-2.1.12.0](https://github.com/Stratio/cassandra-lucene-index/releases/tag/2.1.12.0) for cassandra-2.1.12

Thank you

**Comment by dejwsz** [comment]
Thank you!
