### ISSUE TITLE
Null items in udt stops lucene indexing

### ISSUE THREAD

**Issue by nlacey** [Stratio/cassandra-lucene-index#85]
This example come from 
https://github.com/Stratio/cassandra-lucene-index/blob/branch-2.2.4/doc/src/site/sphinx/documentation.rst#user-defined-types

CREATE TYPE address_udt (
    street text,
    city text,
    zip int
);

CREATE TABLE user_profiles (
    login text PRIMARY KEY,
    first_name text,
    last_name text,
    address frozen<address_udt>,
    lucene text
);

CREATE CUSTOM INDEX test_index ON user_profiles(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            "address.city" : { type : "string"},
            "address.zip"  : { type : "integer"}
        }
    }'
};

insert into user_profiles (login,address) values ('name',{city:'San Fransisco'});

select * from user_profiles;
returns the item

SELECT * FROM user_profiles
WHERE lucene='{ filter : { type  : "match",field : "address.city", value : "San Fransisco"} }';

returns emtpy

insert another record
insert into user_profiles (login,address) values ('name2',{city:'San Fransisco',zip:12345,street:'hill'});
SELECT * FROM user_profiles
WHERE lucene='{ filter : { type  : "match",field : "address.city", value : "San Fransisco"} }';

returns the full record only

I'm using cassandra 2.2.3
Thanks

**Comment by ealonsodb** [comment]
Hi, it is already fixed in [branch-2.2.4](https://github.com/Stratio/cassandra-lucene-index/tree/branch-2.2.4) and soon (maybe next week) it will be included in next release.

Thank you for your effort
