### ISSUE TITLE
Is it really that bad to use id fields as lucene index?

### ISSUE THREAD

**Issue by masumsoft** [Stratio/cassandra-lucene-index#93]
Say I have a cassandra table where posts by users are stored in a schema like this:

```
CREATE TABLE posts (
    id ascii,
    user_id ascii,
    content text,
    created_time timestamp
    PRIMARY KEY (user_id, created_time)
)
```

Note that the primary key is not the `id` field, instead it has used the `user_id` as the partition key and `created_time` as the clustering key. Because I need to find posts by a certain user sorted by created time. 

Now I also need to get a post by it's id only. I know I can create a denormalised table to fix this. But I don't want to, as there are large amount of post data and denormalising it would just double my disk space requirement. 

So I thought why I don't use the id field in a lucene index and serve my id only requests from the lucene index. Will that be too slow? I guess lucene won't have to deal with a large search space as there will be only a single record with a each id and it should be possible to get the post in constant time theoretically.

**Comment by adelapena** [comment]
Hi,

If you are going to index just a single column with a high cardinality and searches are going to always use an equality operator, standard C* secondary indexes could be a better choice since they support this feature with lower resources consumption:
```
CREATE INDEX post_id_idx ON posts (id);
```
Alternatively, you can manually create an index table:
```
CREATE TABLE post_id_idx (
    id ascii,
    user_id ascii,
    created_time timestamp
    PRIMARY KEY (id, user_id, created_time)
)
```
You would query this auxiliary table to retrieve the primary keys of the main table:
```
SELECT user_id, created_time FROM post_keys_by_id WHERE id=?;
SELECT content FROM posts WHERE user_id=? AND created_time=?;
```
This would involve two or more cluster lookups instead of one, but each of these lookups will be probably faster than a single secondary index lookup, specially if you have many C* nodes. 

I hope it helps.

**Comment by masumsoft** [comment]
Thanks a lot for the explanation, I was a bit confused looking into this: https://docs.datastax.com/en/cql/3.1/cql/ddl/ddl_when_use_index_c.html

The above document discouraged me using a secondary index on high cardinality columns. If secondary indexes does hit all nodes for a query over it, I was wondering why didn't the secondary index implementation do the auxiliary table trick under the hood?

**Comment by adelapena** [comment]
Both secondary indexes implementations take a **local indexing** approach, where each node indexes its own data. They are best suited for search and analytical use cases. Indeed, secondary indexes play particularly well with MapReduce frameworks such as Spark and Hadoop, and most search engines such Solr and ElasticSearch take a local indexing approach. Also, index locality use to offer a higher write throughput and eases index rebuilding.

The suggested index table uses a **global indexing** strategy, which is best suited for real-time use cases when it's possible. The tradeoff of global indexes is that usually they don't allow complex queries and neither they are such adequate for retrieving big amounts of data. Also, they aren't suitable to be used by MapReduce frameworks. As long as I know, there aren't currently any global index implementation for C*, although [materialized views started as an attempt of creating this kind of indexing](https://issues.apache.org/jira/browse/CASSANDRA-6477).

**Comment by masumsoft** [comment]
Hmm that's enlightening, thanks a lot!
