### ISSUE TITLE
MarshalException: Invalid UTF-8 bytes 56c70d16

### ISSUE THREAD

**Issue by ankit92agrawal** [Stratio/cassandra-lucene-index#95]
Say I have this table
CREATE TABLE sample(
     id VARCHAR,
     feedback_rating FLOAT,
     feedback_comments TEXT,
     service_type TEXT,
     date_entered TIMESTAMP,
     cust_name VARCHAR,
     email VARCHAR,
     lucene TEXT,
     PRIMARY KEY(id,date_entered)
);
I am using java to dump values in this table.I have created following index on this table

CREATE CUSTOM INDEX sample ON sample(lucene)
USING ‘com.stratio.cassandra.lucene.Index’
WITH OPTIONS = {
    ‘refresh_seconds’ : ‘1’,
    ‘schema’ : ‘{
        fields : {
            id    : {type : “string”},
            feedback_rating : {type : “float”},
            feedback_comments:{type:”text”,analyzer:”english”},
            date_entered:{type:”date”},
         }
    }’
};
After creation of index if i try to insert more rows I am running into this exception

Exception in thread "main" com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on localhost/127.0.0.1:9042: org.apache.cassandra.serializers.MarshalException: Invalid UTF-8 bytes 56c70d16))

**Comment by adelapena** [comment]
Which version of Cassandra and which version of the plugin are you using? Can you provide a failing INSERT statement?
