### ISSUE TITLE
README missing info

### ISSUE THREAD

**Issue by dkatten** [Stratio/cassandra-lucene-index#96]
From the readme:

```
CREATE KEYSPACE demo
WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};
USE demo;
CREATE TABLE tweets (
    id INT PRIMARY KEY,
    user TEXT,
    body TEXT,
    time TIMESTAMP,
    latitude FLOAT,
    longitude FLOAT
);
```
    We have created a column called lucene to link the index searches. This column will not store data. Now you can create a custom Lucene index on it with the following statement:

However, there's no column called `lucene`. Should it be a `text` type?

**Comment by ealonsodb** [comment]
No, this is an error in README. 

From version 3.X there is no more 'lucene' column because the way the secondary index is queried has changed from 'WHERE lucene='query'' to 'WHERE expr(index_name,query)'

**Comment by adelapena** [comment]
More about this at [CASSANDRA-10217](https://issues.apache.org/jira/browse/CASSANDRA-10217).

**Comment by masumsoft** [comment]
So will my previous way of `where lucene=query` continue to work or is it a backwards incompatible change?

**Comment by adelapena** [comment]
No, the old fake-column-based ``where lucene=query`` syntax is not supported by all the versions based on Apache Cassandra 3.x. You must use the new row-based ``where expr(index, query)`` syntax.
