### ISSUE TITLE
Query with modifiers

### ISSUE THREAD

**Issue by favalos** [Stratio/cassandra-lucene-index#98]
Hi,

I have a requirement to search in the following way.

field: "body" 
value: "Comic +Spiderman -Batman"

Comic must be in the field.
Spiderman could be in the field.
Batman must not be in the field.

What is the best way to handle it? Do you have any suggestion?

Regards,

**Comment by adelapena** [comment]
Hi,

You may take a look at the [documentation about boolean search](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.3/doc/documentation.rst#boolean-search), and write something like:
```
{filter: {
   type: "boolean",
   must: [{type: "match", field: "body", value: "Comic"}],
   should: [{type: "match", field: "body", value: "Spiderman"}],
   not: [{type: "match", field: "body", value: "Batman"}]
}}
```
The field named "body" should be indexed with a [text mapper](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.3/doc/documentation.rst#text-mapper) with a proper analyzer.

Regards,

**Comment by favalos** [comment]
Sounds great, working on it.

Saludos y muchas gracias.
