### ISSUE TITLE
ReadFailure: code=1300

### ISSUE THREAD

**Issue by ttessarolo** [Stratio/cassandra-lucene-index#99]
Hi –
I've Cassandra 3.3 up and running with cassandra-lucene-index-plugin-3.0.3.0.jar downloaded from MAVEN REPOSITORY (http://mvnrepository.com/artifact/com.stratio.cassandra/cassandra-lucene-index-plugin/3.0.3.0)  and copied in <CASSANDRA HOME>/lib directory.

I'm getting every query I try the same error. To give you exactly what I do please find below the sequence I type on CQLSH:

cqlsh> CREATE KEYSPACE demo
   ... WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};
cqlsh> USE demo;
cqlsh:demo> CREATE TABLE tweets (
        ...     id INT PRIMARY KEY,
        ...     user TEXT,
        ...     body TEXT,
        ...     time TIMESTAMP,
        ...     latitude FLOAT,
        ...     longitude FLOAT
        ... );
cqlsh:demo> CREATE CUSTOM INDEX tweets_index ON tweets ()
        ... USING 'com.stratio.cassandra.lucene.Index'
        ... WITH OPTIONS = {
        ...     'refresh_seconds' : '1',
        ...     'schema' : '{
        ...         fields : {
        ...             id    : {type : "integer"},
        ...             user  : {type : "string"},
        ...             body  : {type : "text", analyzer : "english"},
        ...             time  : {type : "date", pattern : "yyyy/MM/dd", sorted : true},
        ...             place : {type : "geo_point", latitude:"latitude", longitude:"longitude"}
        ...         }
        ...     }'
        ... };
cqlsh:demo> SELECT * FROM tweets WHERE expr(tweets_index,'{refresh:true}');

**Traceback (most recent call last):
  File "./cqlsh.py", line 1249, in perform_simple_statement
    result = future.result()
  File "/Applications/apache-cassandra-3.3/bin/../lib/cassandra-driver-internal-only-3.0.0-6af642d.zip/cassandra-driver-3.0.0-6af642d/cassandra/cluster.py", line 3122, in result
    raise self._final_exception
ReadFailure: code=1300 [Replica(s) failed to execute read] message="Operation failed - received 0 responses and 1 failures" info={'failures': 1, 'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}**

**Comment by adelapena** [comment]
cassandra-lucene-index-plugin-3.0.3.0.jar is intended to be used with Apache Cassandra 3.0.3. As you can read in [the documentation about requirements](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.3/doc/documentation.rst#requirements), each version of the plugin targets a specific Apache Cassandra release identified by the three first numbers of the plugin version. We don't provide support for [Cassandra tick-tock releases](http://www.planetcassandra.org/blog/cassandra-2-2-3-0-and-beyond/), just for production-ready ones.

**Comment by ttessarolo** [comment]
OK I've installed Cassandra 3.0.3 –– copied all the data and now works perfectly. Thank you so much!

**Comment by adelapena** [comment]
You are very welcome.
